<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PerforatedInvoice.type_active'] = "FAKTUR";
$lang['PerforatedInvoice.type_draft'] = "FAKTUR - DRAFT";
$lang['PerforatedInvoice.type_void'] = "FAKTUR - TIDAK BERLAKU";
$lang['PerforatedInvoice.lines_cost'] = "Biaya";
$lang['PerforatedInvoice.balance_heading'] = "Saldo";
$lang['PerforatedInvoice.detach_remit_to'] = "Kirim ke:";
$lang['PerforatedInvoice.detach_total_due'] = "Jumlah total jatuh tempo :";
?>