<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Vesta.package_fields.package_name'] = "Nama Paket Vesta";
$lang['Vesta.service_field.username'] = "Username";
$lang['Vesta.tab_client_actions.password'] = "Password";
?>