<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Cpanel.module_row'] = "Server";
$lang['Cpanel.module_group'] = "Kelompok Server";
$lang['Cpanel.add_module_row'] = "Tambah Server";
$lang['Cpanel.add_module_group'] = "Tambahkan Server Group";
$lang['Cpanel.manage.module_rows_title'] = "Servers";
$lang['Cpanel.manage.module_groups_title'] = "Grup Server";
$lang['Cpanel.manage.module_rows_heading.name'] = "Label Server";
$lang['Cpanel.manage.module_rows_heading.accounts'] = "Akun";
$lang['Cpanel.manage.module_groups_heading.name'] = "Nama Kelompok";
$lang['Cpanel.manage.module_groups_heading.options'] = "Pilihan";
$lang['Cpanel.manage.module_rows.count'] = "%1\$s / %2\$s"; // %1$s is the current number of accounts, %2$s is the total number of accounts available
$lang['Cpanel.manage.module_groups.edit'] = "Mengedit";
$lang['Cpanel.manage.module_groups.delete'] = "Hapus";
$lang['Cpanel.manage.module_rows.confirm_delete'] = "Anda yakin ingin menghapus server ini?";
$lang['Cpanel.manage.module_groups.confirm_delete'] = "Apakah Anda yakin ingin menghapus grup server ini?";
$lang['Cpanel.add_row.box_title'] = "Tambahkan cPanel Server";
$lang['Cpanel.add_row.basic_title'] = "Pengaturan Dasar";
$lang['Cpanel.add_row.name_servers_title'] = "Name Servers";
$lang['Cpanel.add_row.notes_title'] = "Catatan";
$lang['Cpanel.add_row.name_server_host_col'] = "Hostname";
$lang['Cpanel.add_row.name_server'] = "Name server %1\$s"; // %1$s is the name server number (e.g. 3)
$lang['Cpanel.add_row.remove_name_server'] = "Hapus";
$lang['Cpanel.edit_row.box_title'] = "Mengedit cPanel Server";
$lang['Cpanel.edit_row.basic_title'] = "Pengaturan Dasar";
$lang['Cpanel.edit_row.name_servers_title'] = "Nama Server";
$lang['Cpanel.edit_row.notes_title'] = "Catatan";
$lang['Cpanel.edit_row.name_server_btn'] = "Tambahkan Nama Server tambahan";
$lang['Cpanel.edit_row.name_server_col'] = "Name Server";
$lang['Cpanel.edit_row.name_server_host_col'] = "Hostname";
$lang['Cpanel.edit_row.remove_name_server'] = "Hapus";
$lang['Cpanel.edit_row.add_btn'] = "Mengedit Server";
$lang['Cpanel.row_meta.use_ssl'] = "Gunakan SSL saat menghubungkan ke API (dianjurkan)";
$lang['Cpanel.row_meta.account_limit'] = "Batas akun";
$lang['Cpanel.!error.server_name_valid'] = "Anda harus memasukkan Label Server.";
$lang['Cpanel.!error.user_name_valid'] = "User Name tidak valid.";
$lang['Cpanel.!error.remote_key_valid'] = "Token (atau Remote Key) tampaknya tidak valid.";
$lang['Cpanel.!error.account_limit_valid'] = "Limit / pembatasan akun harus dikosongkan (untuk akun unlimited) atau set ke beberapa nilai integer.";
$lang['Cpanel.package_fields.type_standard'] = "Standar";
$lang['Cpanel.package_fields.type_reseller'] = "Reseller";
$lang['Cpanel.package_fields.acl'] = "Daftar Akses Control";
$lang['Cpanel.service_field.username'] = "Username";
$lang['Cpanel.tab_stats.info_title'] = "Informasi";
$lang['Cpanel.tab_stats.info_heading.value'] = "Nilai";
$lang['Cpanel.tab_stats.info.domain'] = "Domain";
$lang['Cpanel.tab_stats.bandwidth_title'] = "Bandwidth";
$lang['Cpanel.tab_stats.bandwidth_heading.used'] = "Digunakan";
$lang['Cpanel.tab_stats.bandwidth_value'] = "%1\$s MB"; // %1$s is the amount of bandwidth in MB
$lang['Cpanel.tab_stats.disk_title'] = "Disk";
$lang['Cpanel.tab_stats.disk_heading.used'] = "Digunakan";
$lang['Cpanel.tab_stats.disk_value'] = "%1\$s MB"; // %1$s is the amount of disk in MB
$lang['Cpanel.service_info.username'] = "Nama pengguna";
$lang['Cpanel.service_info.password'] = "Kata Sandi";
$lang['Cpanel.service_info.option_login'] = "Masuk";
$lang['Cpanel.tab_client_stats'] = "Statistika";
$lang['Cpanel.manage.module_rows_no_results'] = "Tidak ada server.";
$lang['Cpanel.tab_client_stats.info_heading.field'] = "Bidang";
$lang['Cpanel.tab_client_stats.info_heading.value'] = "Nilai";
$lang['Cpanel.!error.cpanel_password.valid'] = "Sandi harus minimal 8 karakter.";
$lang['Cpanel.!error.cpanel_password.matches'] = "Password dan konfirmasi Password tidak cocok.";
$lang['Cpanel.service_field.tooltip.username'] = "Anda dapat meninggalkan username kosong dan secara otomatis akan dibuatkan.";
$lang['Cpanel.!error.module_row.missing'] = "Terjadi kesalahan internal. Modul baris tidak tersedia.";
$lang['Cpanel.tab_client_actions.field_password_submit'] = "Update Password";
$lang['Cpanel.tab_client_stats.disk_title'] = "Pemakaian Disk";
?>