<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Quantum_gateway.!error.gateway_login.empty'] = "Silakan masukkan Gateway Login.";
$lang['Quantum_gateway.name'] = "QuantumGateway";
$lang['Quantum_gateway.gateway_login'] = "Gateway Login";
$lang['Quantum_gateway.restrict_key'] = "Larangan utama";
$lang['Quantum_gateway.maxmind'] = "Gunakan Maxmind";
$lang['Quantum_gateway.tooltip_maxmind'] = "Centang kotak untuk mengaktifkan Control Penipuan MaxMind. Periksa panel kontrol QuantumGateway Anda untuk pengaturan tambahan MaxMind .";
?>