<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ThesslstoreModule.!error.empty_package_group'] = "Opps, Tampaknya Anda belum membuat grup paket apa pun. Anda harus terlebih dahulu membuat grup sebelum mengimpor produk apa pun. Setelah Anda selesai melakukannya, kembalilah dan lanjutkan dengan impor.";
$lang['ThesslstoreModule.add_row.box_title'] = "Pengaturan";
$lang['ThesslstoreModule.reseller_price.box_title'] = "Harga Produk Pengecer";
$lang['ThesslstoreModule.setup_price.update_mode'] = "Sepertinya Anda telah mengganti \"Mode Operasi\" ke \"LIVE\"! Jika harga produk saat ini akan ditest terlebih dahulu, silahkan perbarui dari sini";
$lang['ThesslstoreModule.row_meta.product_group'] = "Pilih Paket Grup";
$lang['ThesslstoreModule.package_fields.product_code'] = "Kode Produk";
$lang['TheSSLStore.!error.meta[thesslstore_validation_type].valid'] = "Jenis Validasi Tidak Valid";
$lang['ThesslstoreModule.tab_client_cert_details.tech_details'] = "Detail teknis";
$lang['ThesslstoreModule.tab_client_cert_details.tech_email'] = "Email";
$lang['ThesslstoreModule.service_field.thesslstore_tech_last_name'] = "Nama Akhir";
$lang['ThesslstoreModule.!error.thesslstore_admin_email.empty'] = "Silahkan masukkan Email Admin";
?>