<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Ccavenue.name'] = "Pembayaran CCAvenue";
$lang['Ccavenue.buildprocess.submit'] = "Membayar melalui CCAvenue";
$lang['Ccavenue.!error.merchant_id.valid'] = "Cukup masukkan ID pedagang yang valid.";
$lang['Ccavenue.!error.pending.log'] = "Status pembayaran yang diterima tertunda dari gateway.";
$lang['Ccavenue.access_code'] = "Kode Akses";
$lang['Ccavenue.access_code_note'] = "Hal ini dapat ditemukan di akun CCAvenue Anda di bawah Keys API.";
$lang['Ccavenue.test_mode_note'] = "Jika dicentang, gateway akan mengirimkan permintaan pembayaran ke URL test";
$lang['Ccavenue.!error.encryption_key.valid'] = "Masukkan kunci enkripsi.";
?>