<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Stripe_gateway.!error.auth'] = "ateway tidak bisa mengotentikasi.";
$lang['Stripe_gateway.!error.api_key.empty'] = "Silahkan masukkan kunci API";
$lang['Stripe_gateway.!error.json_required'] = "JSON ekstensi diperlukan untuk gateway ini.";
$lang['Stripe_gateway.name'] = "Garis";
$lang['Stripe_gateway.api_key'] = "API Secret Key";
?>