<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Bitpay.name'] = "Bitpay";
$lang['Bitpay.transaction_speed'] = "Kecepatan transaksi";
$lang['Bitpay.transaction.speed.high'] = "Tinggi";
$lang['Bitpay.transaction.speed.medium'] = "Medium";
$lang['Bitpay.transaction_speed_note'] = "Kecepatan transaksi menentukan seberapa cepat faktur (di Bitpay) dapat dianggap 'dikonfirmasi'.";
$lang['Bitpay.buildprocess.submit'] = "Bayar menggunakan Bitcoin";
$lang['Bitpay.!error.api_key.valid'] = "Masukkan kunci API yang valid.";
$lang['Bitpay.!error.transaction_speed.valid'] = "Silakan pilih kecepatan transaksi yang valid.";
$lang['Bitpay.!error.payment.invalid'] = "Transaksi gagal dan tidak dapat diproses";
$lang['Bitpay.!error.payment.expired'] = "Transaksi telah berakhir dan tidak dapat diproses.";
?>