<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Pagseguro.email_id'] = "Email";
$lang['Pagseguro.email_note'] = "Masukkan alamat email PagSeguro akun Anda.";
$lang['Pagseguro.!error.dom_required'] = "Ekstensi dom diperlukan untuk gateway ini.";
$lang['Pagseguro.!error.notification.invalid'] = "Parameter notifikasi tidak cocok";
?>