<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Ispconfig.edit_row.box_title'] = "Edit ISPConfig Server";
$lang['Ispconfig.edit_row.name_server_host_col'] = "Hostname";
$lang['Ispconfig.row_meta.server_name'] = "Label Server";
$lang['Ispconfig.package_fields.ssh_options'] = "SSH Option";
$lang['Ispconfig.service_field.username'] = "Username";
$lang['Ispconfig.!error.ispconfig_domain.format'] = "Silahkan masukkan nama hostname yang benar, mis: domain.com.";
?>