<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PhpidsManagePlugin.index.page_title'] = "PHPIDS> Pengaturan";
$lang['PhpidsManagePlugin.index.boxtitle_phpids'] = "PHPIDS";
$lang['PhpidsManagePlugin.index.tab_settings'] = "Pengaturan";
$lang['PhpidsManagePlugin.index.heading_general'] = "Pilihan Dasar ";
$lang['PhpidsManagePlugin.index.heading_email'] = "Email Alert";
$lang['PhpidsManagePlugin.index.field.email_min_score'] = "Dampak Minimum Penilaian ke Email";
$lang['PhpidsManagePlugin.index.field.email_addresses'] = "Alamat ke Email peringatan (dipisahkan koma)";
$lang['PhpidsManagePlugin.index.text.edit_template'] = "Edit Template Email";
$lang['PhpidsManagePlugin.index.field.submit'] = "Pembaruan Pengaturan";
$lang['PhpidsManagePlugin.getIntervals.mins_singular'] = "%1\$s Menit"; // %1$s is the number of minutes
$lang['PhpidsManagePlugin.getDays.days_singular'] = "%1\$s hari"; // %1$s is the number of days
$lang['PhpidsManagePlugin.getDays.days_plural'] = "%1\$s Hari"; // %1$s is the number of days
$lang['PhpidsManagePlugin.logs.heading.uri'] = "URI";
$lang['PhpidsManagePlugin.logs.heading.ip'] = "IP";
$lang['PhpidsManagePlugin.logs.heading.user_id'] = "Identitas pengguna";
?>