<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['CmsManagePlugin.index.boxtitle_portal'] = "Portal";
$lang['CmsManagePlugin.index.field_tags'] = "Tag Yang Tersedia";
$lang['CmsManagePlugin.index.field_content'] = "Indeks Halaman Konten";
?>