<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['CmsPages.!error.uri.empty'] = "Silakan masukkan path URL ke halaman.";
$lang['CmsPages.!error.company_id.exists'] = "ID perusahaan tidak valid.
";
$lang['CmsPages.!error.title.empty'] = "Masukkan judul halaman.";
?>