<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Virtualmin.add_module_row'] = "Tambahkan server";
$lang['Virtualmin.manage.module_rows.delete'] = "Hapus";
$lang['Virtualmin.manage.module_groups.confirm_delete'] = "Anda yakin ingin menghapus grup server ini?";
$lang['Virtualmin.row_meta.user_name'] = "Nama Pengguna";
?>