<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AgingInvoices.name'] = "Aging Invoices";
$lang['AgingInvoices.options.field_status'] = "Status";
$lang['AgingInvoices.heading.client_id_code'] = "Klien #";
$lang['AgingInvoices.heading.total'] = "Total";
$lang['AgingInvoices.heading.currency'] = "Mata uang";
$lang['AgingInvoices.heading.date_billed'] = "Tanggal Ditagih";
$lang['AgingInvoices.heading.date_due'] = "Tanggal jatuh tempo";
$lang['AgingInvoices.heading.past90'] = "90+";
$lang['AgingInvoices.heading.client_email'] = "Email Klien";
$lang['AgingInvoices.heading.client_numbers'] = "Nomor Telepon Klien";
?>