<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMain.!success.feed_added'] = "Feed berhasil ditambahkan";
$lang['AdminMain.index.last_updated'] = "Terakhir Diperbarui: %1\$s"; // %1$s is a date/time stamp of the last time the feed was updated
$lang['AdminMain.add.boxtitle_feed'] = "Tambah sebuah Feed";
$lang['AdminMain.add.submit_add'] = "Tambahkan feed";
$lang['AdminMain.settings.no_feeds'] = "Tidak ada feed.";
$lang['AdminMain.settings.add_feed'] = "Tambah sebuah Feed";
$lang['AdminMain.settings.heading_url'] = "URL";
$lang['AdminMain.settings.heading_options'] = "Pilihan";
$lang['AdminMain.settings.option_refresh'] = "Refresh";
$lang['AdminMain.settings.option_remove'] = "hapus";
?>