<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['FeedReaderManagePlugin.!success.feed_added'] = "feed telah ditambahkan.";
$lang['FeedReaderManagePlugin.index.add_feed'] = "Tambahkan Feed";
$lang['FeedReaderManagePlugin.index.heading_url'] = "URL";
$lang['FeedReaderManagePlugin.index.heading_lastupdated'] = "Terakhir Diperbarui";
$lang['FeedReaderManagePlugin.index.option_refresh'] = "Menyegarkan";
$lang['FeedReaderManagePlugin.index.option_remove'] = "Menghapus";
$lang['FeedReaderManagePlugin.add.boxtitle_feed'] = "Tambahkan Feed";
$lang['FeedReaderPlugin.add.submit_cancel'] = "Batal";
$lang['FeedReaderManagePlugin.add.page_title'] = "Pembaca Umpan > Tambahkan Umpan";
$lang['FeedReaderManagePlugin.index.text_confirm_delete'] = "Yakin menghapus feed ini?";
?>