<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['FeedReaderPlugin.!error.libxml_required'] = "extension libxml diperlukan untuk plugin ini.";
$lang['FeedReaderPlugin.!error.dom_required'] = "dom extension diperlukan untuk plugin ini.";
$lang['FeedReaderPlugin.name'] = "Feed Reader";
?>