<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['QuickbooksInvoice.name'] = "Quickbooks";
$lang['QuickbooksInvoice.page_of'] = "Halaman %1\$s dari %2\$s"; // %1$s is the current page number, %2$s is the total number of pages
$lang['QuickbooksInvoice.terms_heading'] = "Persyaratan";
$lang['QuickbooksInvoice.type_draft'] = "FAKTUR - DRAFT";
$lang['QuickbooksInvoice.type_void'] = "FAKTUR - BATAL";
$lang['QuickbooksInvoice.invoice_id_code'] = "No. Faktur";
$lang['QuickbooksInvoice.client_id_code'] = "No. Pelanggan ";
$lang['QuickbooksInvoice.date_billed'] = "Tanggal";
$lang['QuickbooksInvoice.date_due'] = "Tanggal Jatuh Tempo ";
$lang['QuickbooksInvoice.notes_heading'] = "Catatan";
$lang['QuickbooksInvoice.subtotal_heading'] = "Subtotal";
$lang['QuickbooksInvoice.lines_quantity'] = "Kuantitas";
$lang['QuickbooksInvoice.address_city_state'] = "%1\$s, %2\$s %3\$s %4\$s"; // %1$s is the city, %2$s is the state code, %3$s is the zip/postal code, %4$s is the country code
$lang['QuickbooksInvoice.watermark_paid'] = "DIBAYAR";
$lang['QuickbooksInvoice.client_tax_id'] = "Pajak ID Pelanggan / Vatin: %1\$s"; // %1$s is the tax ID/VATIN
$lang['QuickbooksInvoice.payments_applied_date'] = "Tanggal Diterapkan";
$lang['QuickbooksInvoice.payments_type_name'] = "Jenis";
$lang['QuickbooksInvoice.balance_heading'] = "Balance";
$lang['QuickbooksInvoice.draft_id_code'] = "Draft No.";
?>