<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Tcadmin.module_row'] = "Server";
$lang['Tcadmin.manage.module_rows_heading.name'] = "Server Label";
$lang['Tcadmin.manage.module_rows_heading.port'] = "Port";
$lang['Tcadmin.package_fields.no'] = "Tidak";
$lang['Tcadmin.!error.port_valid'] = "Port tampaknya tidak valid.";
$lang['Tcadmin.!error.meta[startup].valid'] = "Silahkan pilih opsi startup yang valid";
?>