<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminStaff.!success.staff_added'] = "Anggota staf telah berhasil ditambahkan.";
$lang['AdminStaff.!success.staff_deleted'] = "Anggota staf telah berhasil dihapus.";
$lang['AdminStaff.!tooltip.all_day'] = "Centang kotak ini untuk membuat anggota staf yang tersedia sepanjang hari.";
$lang['AdminStaff.!tooltip.mobile_ticket_emails'] = "Centang kotak masing-masing prioritas tiket yang staf harus menerima email tiket secara mobile.";
$lang['AdminStaff.index.page_title'] = "Support Manager > Staff";
$lang['AdminStaff.add.page_title'] = "Support Manager > Tambah Staff";
$lang['AdminStaff.index.categorylink_addstaff'] = "Tambahkan Staf";
$lang['AdminStaff.index.boxtitle_staff'] = "Staf";
$lang['AdminStaff.index.heading_email'] = "Email";
$lang['AdminStaff.index.heading_mobile_ticket_emails'] = "Menerima Email Ponsel Tiket";
$lang['AdminStaff.index.option_edit'] = "Edit";
$lang['AdminStaff.index.option_delete'] = "Hapus";
$lang['AdminStaff.index.confirm_delete'] = "Menghapus anggota staf ini akan membatalkan penetapan semua tiket saat ini yang ditangani anggota staf ini. Apakah Anda yakin ingin menghapus anggota staf ini?";
$lang['AdminStaff.index.no_results'] = "Saat ini sedang tidak ada staff yang bertugas pada support system";
$lang['AdminStaff.add.boxtitle_addstaff'] = "Tambah Staf";
$lang['AdminStaff.add.heading_staff'] = "Staff";
$lang['AdminStaff.add.heading_schedule'] = "Jadwal";
$lang['AdminStaff.add.heading_settings'] = "Setting";
$lang['AdminStaff.add.heading_all_day'] = "Sepanjang Hari";
$lang['AdminStaff.add.heading_start_time'] = "Waktu mulai";
$lang['AdminStaff.add.heading_end_time'] = "Akhir Waktu";
$lang['AdminStaff.add.text_assigneddepartments'] = "Ditetapkan di departemen";
$lang['AdminStaff.add.text_availabledepartments'] = "Departemen yang Tersedia";
$lang['AdminStaff.add.field_addsubmit'] = "Tambah Staf";
$lang['AdminStaff.edit.heading_schedule'] = "Jadual";
$lang['AdminStaff.edit.heading_day'] = "Hari";
$lang['AdminStaff.edit.heading_end_time'] = "Selesai";
$lang['AdminStaff.edit.text_availabledepartments'] = "Departemen Yang Tersedia";
$lang['AdminStaff.schedule_list.heading_schedule'] = "Rencana";
$lang['AdminStaff.schedule_list.heading_day'] = "Hari";
$lang['AdminStaff.schedule_list.heading_start_time'] = "Waktu Mulai";
$lang['AdminStaff.schedule_list.no_results'] = "Anggota staf ini tidak dijadwalkan untuk setiap hari.";
$lang['AdminStaff.add.signature'] = "Tanda tangan";
?>