<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyEmails.templates.SupportManager.staff_ticket_updated_name'] = "Tiket Staf Diperbarui";
$lang['AdminCompanyEmails.templates.SupportManager.staff_ticket_updated_mobile_name'] = "Tiket Staff Diperbaharui (Seluler)";
$lang['AdminCompanyEmails.templates.SupportManager.staff_ticket_updated_mobile_desc'] = "Pemberitahuan via ponsel dikirim ke anggota staf ketika tiket diperbarui.";
$lang['AdminCompanyEmails.templates.SupportManager.ticket_updated_name'] = "Tiket Diperbarui";
$lang['AdminCompanyEmails.templates.SupportManager.ticket_updated_desc'] = "Pemberitahuan dikirim saat tiket diperbarui.";
$lang['AdminCompanyEmails.templates.SupportManager.ticket_bounce_name'] = "Bounce Tiket";
?>