<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminTickets.!success.ticket_updated'] = "Tiket #%1\$s telah berhasil diperbarui."; // %1$s is the ticket number
$lang['AdminTickets.reply.page_title'] = "Support Manager > Ticket #%1\$s"; // %1$s is the ticket number
$lang['AdminTickets.search.page_title'] = "Hasil pencarian untuk \"%1\$s\""; // %1$s is the search keywords
$lang['AdminTickets.text.unassigned'] = "Tidak Ditugaskan";
$lang['AdminTickets.index.categorylink_createticket'] = "Buka Tiket";
$lang['AdminTickets.index.boxtitle_tickets'] = "Tiket";
$lang['AdminTickets.index.heading_priority'] = "Prioritas";
$lang['AdminTickets.index.heading_department_name'] = "Departemen";
$lang['AdminTickets.add.heading_search_client'] = "Mencari Klien";
$lang['AdminTickets.add.text_no_clients'] = "Tidak ada klien ditemukan. Silahkan dicoba lagi.";
$lang['AdminTickets.add.heading_client'] = "Klien";
$lang['AdminTickets.add.heading_department'] = "Departemen";
$lang['AdminTickets.add.heading_priority'] = "Prioritas";
$lang['AdminTickets.add.heading_status'] = "Status";
$lang['AdminTickets.add.text_add_attachment'] = "Tambahkan Lampiran";
$lang['AdminTickets.add.field_addsubmit'] = "Buka Tiket";
$lang['AdminTickets.reply.boxtitle_reply'] = "Tiket #%1\$s"; // %1$s is the ticket number
$lang['AdminTickets.reply.heading_summary'] = "Ringkasan";
$lang['AdminTickets.reply.heading_client'] = "Klien";
$lang['AdminTickets.reply.heading_department'] = "Departemen";
$lang['AdminTickets.reply.heading_staff_id'] = "Ditugaskan Untuk";
$lang['AdminTickets.reply.heading_priority'] = "Prioritas";
$lang['AdminTickets.reply.heading_status'] = "Status";
$lang['AdminTickets.reply.heading_date_added'] = "Tanggal Dibuka";
$lang['AdminTickets.reply.heading_reply'] = "Tambahkan Balasan";
$lang['AdminTickets.reply.field_reply'] = "Balas";
$lang['AdminTickets.reply.field_note'] = "Catatan";
$lang['AdminTickets.reply.field_attachments'] = "Lampiran";
$lang['AdminTickets.reply.text_add_attachment'] = "Tambahkan Lampiran";
$lang['AdminTickets.reply.field_replysubmit'] = "Perbarui Tiket";
$lang['AdminTickets.reply.reply_date'] = "Pada %1\$s %2\$s %3\$s menjawab"; // %1$s is the ticket reply date, %2$s is the first name of the reply author, %3$s is the last name of the reply author
$lang['AdminTickets.reply.system'] = "Sistem";
$lang['AdminTickets.reply.staff_title'] = "Staf pendukung";
$lang['AdminTickets.client.category_awaiting_reply'] = "Menunggu Balas";
$lang['AdminTickets.client.category_closed'] = "Tertutup";
$lang['AdminTickets.client.categorylink_createticket'] = "Buka Tiket";
$lang['AdminTickets.client.heading_summary'] = "Ringkasan";
$lang['AdminTickets.client.no_results'] = "Saat ini tidak ada tiket dengan status ini.";
$lang['AdminTickets.search.heading_code'] = "Nomor Tiket";
$lang['AdminTickets.search.heading_status'] = "Status";
$lang['AdminTickets.search.heading_last_reply_date'] = "Balasan Terakhir";
$lang['AdminTickets.search.no_results'] = "Tidak ada tiket yang cocok dengan kriteria pencarian.";
$lang['AdminTickets.index.last_reply_by'] = "oleh";
$lang['AdminTickets.!success.ticket_update_status'] = "Tiket yang dipilih telah berhasil diperbarui.";
$lang['AdminTickets.index.heading_assigned_staff'] = "Ditugaskan Untuk";
$lang['AdminTickets.index.unassigned'] = "tidak dialokasikan";
$lang['AdminTickets.index.text_to_status'] = "Ubah :";
$lang['AdminTickets.index.text_no_tickets'] = "Tidak ada tiket terbuka ditemukan. Coba cari lagi.";
$lang['AdminTickets.index.field_actionsubmit'] = "Kirim";
$lang['AdminTickets.index.ticket_email'] = "#%1\$s %2\$s"; // %1$s is the ticket number, %2$s is the client's email address
$lang['AdminTickets.reply.text_with_selected'] = "Dengan balasan yang dipilih, lakukan:";
?>