<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminResponses.!success.response_updated'] = "Tanggapan %1\$s Berhasil diperbaharui."; // %1$s is the name of the predefined response
$lang['AdminResponses.!success.response_deleted'] = "Tanggapan %1\$s berhasil dihapus."; // %1$s is the name of the predefined response
$lang['AdminResponses.index.page_title'] = "Dukungan Manajer> Tanggapan Predefined";
$lang['AdminResponses.edit.page_title'] = "Support Manager > Edit Predefined Response";
$lang['AdminResponses.addcategory.page_title'] = "Support Manager> Tambah Kategori";
$lang['AdminResponses.!text.forward_slash'] = "/";
$lang['AdminResponses.!text.closed_parenthesis'] = ")";
$lang['AdminResponses.index.boxtitle_responses'] = "Penetapan Respon";
$lang['AdminResponses.index.add_category'] = "Tambahkan Kategori di sini";
$lang['AdminResponses.index.no_responses'] = "Tidak ada tanggapan di bagian ini.";
$lang['AdminResponses.modal.delete_category'] = "Apakah Anda yakin ingin menghapus kategori ini? Semua subkategori dan tanggapan yang telah ditetapkan dalam kategori ini akan dipindahkan ke kategori induk.";
$lang['AdminResponses.add.field_name'] = "Nama";
$lang['AdminResponses.add.field_details'] = "Detil Respon";
$lang['AdminResponses.edit.boxtitle_edit'] = "Mengedit Tanggapan Siap Pakai"; // %1$s is the name of the category
$lang['AdminResponses.edit.field_name'] = "Nama";
$lang['AdminResponses.edit.field_details'] = "Detail Response";
$lang['AdminResponses.addcategory.boxtitle_root'] = "Tambahkan Kategori";
$lang['AdminResponses.editcategory.boxtitle_editcategory'] = "Kategori diPerbarui ";
$lang['AdminResponses.editcategory.field_submit'] = "Update Kategori";
?>