<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminDepartments.!success.department_updated'] = "department %1\$s berhasil diperbarui."; // %1$s is the name of the department
$lang['AdminDepartments.!success.department_deleted'] = "The %1\$s departemen berhasil dihapus."; // %1$s is the name of the department
$lang['AdminDepartments.index.page_title'] = "Support Manager> Departemen";
$lang['AdminDepartments.add.page_title'] = "Support Manager > Departemen> Tambah Department";
$lang['AdminDepartments.edit.page_title'] = "Dukungan Manager> Departemen> Edit Departemen";
$lang['AdminDepartments.index.categorylink_adddepartment'] = "Tambahkan Departemen";
$lang['AdminDepartments.index.boxtitle_departments'] = "Departemen";
$lang['AdminDepartments.index.heading_name'] = "Nama";
$lang['AdminDepartments.index.heading_assigned_staff'] = "Staf yang ditugaskan";
$lang['AdminDepartments.index.option_edit'] = "Sunting";
$lang['AdminDepartments.index.option_delete'] = "Hapus";
$lang['AdminDepartments.index.confirm_delete'] = "Departemen dengan tiket yang ditetapkan kepada mereka tidak dapat dihapus sampai semua tiket telah kembali ditetapkan ke departemen alternatif. Apakah Anda yakin ingin menghapus departemen ini?";
$lang['AdminDepartments.assigned_staff.no_results'] = "Tidak ada staf yang ditugaskan untuk departemen ini.";
$lang['AdminDepartments.add.field_name'] = "Nama";
$lang['AdminDepartments.add.field_clients_only'] = "hanya klien yang bisa membuka atau membalas tiket";
$lang['AdminDepartments.add.field_piping_config'] = "Konfigurasi Piping";
$lang['AdminDepartments.add.field_default_priority'] = "Standar Prioritas";
$lang['AdminDepartments.add.field_mark_messages'] = "Tandai Pesan sebagai";
$lang['AdminDepartments.add.field_host'] = "Host";
$lang['AdminDepartments.add.field_pass'] = "Pass";
$lang['AdminDepartments.add.field_addsubmit'] = "Tambahkan Department";
$lang['AdminDepartments.edit.boxtitle_adddepartment'] = "Sunting Department";
$lang['AdminDepartments.edit.field_description'] = "Deskripsi";
$lang['AdminDepartments.edit.field_email'] = "Email";
$lang['AdminDepartments.edit.field_method'] = "Email Penanganan";
$lang['AdminDepartments.edit.field_default_priority'] = "Standar Prioritas";
$lang['AdminDepartments.edit.field_box_name'] = "Nama Kotak";
$lang['AdminDepartments.edit.field_mark_messages'] = "Tandai  Pesan sebagai";
$lang['AdminDepartments.edit.field_host'] = "Host";
$lang['AdminDepartments.edit.field_user'] = "Pemakai";
$lang['AdminDepartments.edit.field_status'] = "Status";
$lang['AdminDepartments.add.field_override_from_email'] = "Timpa alamat email yang ditetapkan dalam template dengan alamat email yang ditetapkan untuk departemen ini";
$lang['AdminDepartments.edit.field_override_from_email'] = "Menimpa alamat yang ditetapkan dalam template email dengan alamat email yang ditetapkan untuk departemen ini";
$lang['AdminDepartments.!tooltip.close_ticket_interval'] = "Semua tiket dengan status selain %1\$s yang terakhir adalah jawaban dari anggota staf akan ditutup secara otomatis jika tidak ada balasan telah dibuat dalam jumlah waktu yang ditentukan"; // %1$s is the ticket status In Progress
$lang['AdminDepartments.!text.remove_response'] = "hapus";
$lang['AdminDepartments.edit.field_response_id'] = "Otomatis-Tutup (Respons Tiket)";
?>