<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminKnowledgebase.!success.article_updated'] = "Artikel ini telah berhasil diperbarui.";
$lang['AdminKnowledgebase.!success.article_deleted'] = "Artikel ini telah berhasil dihapus.";
$lang['AdminKnowledgebase.index.page_title'] = "Manager Dukungan > Basis Pengetahuan";
$lang['AdminKnowledgebase.add.page_title'] = "Dukungan Manager> Basis Pengetahuan> tambah artikel";
$lang['AdminKnowledgebase.edit.page_title'] = "Dukungan Manager> Basis Pengetahuan>edit artikel";
$lang['AdminKnowledgebase.editcategory.page_title'] = "Support Manager> Pengetahuan Basis> Edit Kategori";
$lang['AdminKnowledgebase.index.boxtitle_knowledgebase'] = "Pengetahuan Dasar";
$lang['AdminKnowledgebase.index.go_back'] = "Naik tingkat";
$lang['AdminKnowledgebase.index.delete'] = "Hapus";
$lang['AdminKnowledgebase.modal.delete_article'] = "Apakah Anda yakin ingin menghapus artikel ini?";
$lang['AdminKnowledgebase.addcategory.field_name'] = "Nama";
$lang['AdminKnowledgebase.addcategory.field_description'] = "Deskripsi";
$lang['AdminKnowledgebase.addcategory.submit_add'] = "Buat Kategori";
$lang['AdminKnowledgebase.editcategory.boxtitle_editcategory'] = "Update Kategori";
$lang['AdminKnowledgebase.editcategory.field_parent_id'] = "Induk Kategori";
$lang['AdminKnowledgebase.add.boxtitle_add'] = "Tambahkan artikel";
$lang['AdminKnowledgebase.add.field_categories'] = "Kategori";
$lang['AdminKnowledgebase.edit.boxtitle_edit'] = "Perbarui Artikel";
$lang['AdminKnowledgebase.edit.field_access'] = "Aksesibilitas";
$lang['AdminKnowledgebase.edit.submit_edit'] = "Perbaharui Artikel";
$lang['AdminKnowledgebase.article_content.title'] = "Judul";
$lang['AdminKnowledgebase.article_content.content_type'] = "Jenis konten";
$lang['AdminKnowledgebase.!text.root_directory'] = "Home Directory";
$lang['AdminKnowledgebase.!text.closed_enclosure'] = ")";
$lang['AdminKnowledgebase.!text.enclosure_separator'] = "/";
$lang['AdminKnowledgebase.!text.directory_separator'] = "/";
$lang['AdminKnowledgebase.!tooltip.access_article'] = "Artikel publik dapat diakses oleh semua orang. Artikel pribadi dapat diakses hanya untuk pengguna yang login. Artikel Hidden tidak dapat diakses.";
$lang['AdminKnowledgebase.!tooltip.access_category'] = "Kategori publik dapat diakses oleh semua orang. Kategori pribadi hanya dapat diakses oleh pengguna yang masuk. Kategori tersembunyi tidak dapat diakses.";
?>