<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientTickets.!success.ticket_updated'] = "Tiket #%1\$s telah berhasil diperbarui."; // %1$s is the ticket number
$lang['ClientTickets.!success.ticket_closed'] = "Tiket # %1\$s telah berhasil ditutup."; // %1$s is the ticket number
$lang['ClientTickets.reply.page_title'] = "Dukungan> Update Tiket";
$lang['ClientTickets.index.category_open'] = "Terbuka";
$lang['ClientTickets.index.category_closed'] = "Tertutup";
$lang['ClientTickets.index.categorylink_createticket'] = "Buka Tiket";
$lang['ClientTickets.index.boxtitle_tickets'] = "Tiket";
$lang['ClientTickets.index.heading_code'] = "Nomor Tiket";
$lang['ClientTickets.index.heading_priority'] = "Prioritas";
$lang['ClientTickets.index.heading_department_name'] = "Departemen";
$lang['ClientTickets.index.heading_last_reply_date'] = "Balasan Terakhir";
$lang['ClientTickets.index.confirm_close'] = "Apakah Anda yakin ingin menutup tiket ini?";
$lang['ClientTickets.add.boxtitle_add'] = "Buka Tiket";
$lang['ClientTickets.add.field_email'] = "Email";
$lang['ClientTickets.add.field_summary'] = "Ringkasan";
$lang['ClientTickets.add.field_details'] = "Detail";
$lang['ClientTickets.add.field_addsubmit'] = "Buka Tiket";
$lang['ClientTickets.reply.boxtitle_reply'] = "Tiket #%1\$s"; // %1$s is the ticket number
$lang['ClientTickets.reply.heading_date_added'] = "Tanggal Dibuka";
$lang['ClientTickets.reply.heading_reply'] = "Tambahkan Balasan";
$lang['ClientTickets.reply.text_add_attachment'] = "Tambahkan Lampiran";
$lang['ClientTickets.reply.reply_date'] = "Pada %1\$s %2\$s %3\$s menjawab"; // %1$s is the ticket reply date, %2$s is the first name of the reply author, %3$s is the last name of the reply author
$lang['ClientTickets.reply.system'] = "Sistem";
$lang['ClientTickets.reply.staff_title'] = "Staf Support";
$lang['ClientTickets.index.option_reply'] = "Membalas";
$lang['ClientTickets.add.placeholder_summary'] = "Masukkan Ringkasan";
$lang['ClientTickets.add.placeholder_details'] = "Masukkan Detail";
$lang['ClientTickets.reply.placeholder_reply'] = "Masukkan Detail";
$lang['ClientTickets.reply.field_closesubmit'] = "Tutup";
$lang['ClientTickets.reply.field_replysubmit'] = "Membalas";
?>