<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Global.time_since.hour'] = "%1\$s jam"; // %1$s is the number of hours
$lang['Global.action.split'] = "Belah";
$lang['Global.action.update_status'] = "Memperbaharui Status";
$lang['Global.action.quote'] = "Kutipan";
?>