<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Knowledgebase.index.page_title'] = "Pengetahuan Dasar";
$lang['Knowledgebase.view.page_title'] = "%1\$s"; // %1\$s is the title of the knowledge base article
$lang['Knowledgebase.search.placeholder'] = "Ada pertanyaan? Cari Basis Pengetahuan kami di sini.";
$lang['Knowledgebase.search.form_submit'] = "Pencarian";
$lang['Knowledgebase.index.heading_categories'] = "Kategori";
$lang['Knowledgebase.index.heading_subcategories'] = "Sub Kategori";
$lang['Knowledgebase.index.category_items'] = "(%1\$s)"; // %1$s is the number of items within this category
$lang['Knowledgebase.index.categories_no_results'] = "Tidak ada kategori yang tersedia.";
$lang['Knowledgebase.index.heading_popular'] = "Artikel populer";
$lang['Knowledgebase.index.articles_description'] = "Artikel untuk %1\$s."; // %1$s is the name of the category
$lang['Knowledgebase.search.heading_articles'] = "Article Matching '%1\$s'"; // %1$s is the search criteria
$lang['Knowledgebase.view.text_rate'] = "Silakan menilai artikel ini untuk membantu kami meningkatkan Basis Pengetahuan kami.";
$lang['Knowledgebase.view.edit'] = "Edit";
$lang['Knowledgebase.view.text_vote_thanks'] = "Terima kasih untuk voting pada artikel ini!";
$lang['Knowledgebase.!text.root_directory'] = "Home";
?>