<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SupportManagerKbCategories.!error.parent_id.valid_parent'] = "Kategori ini tidak bisa menjadi Upline untuk dirinya sendiri.";
$lang['SupportManagerKbCategories.!error.name.length'] = "Nama kategori tidak boleh melebihi 255 karakter.";
$lang['SupportManagerKbCategories.access_types.public'] = "Publik";
$lang['SupportManagerKbCategories.access_types.private'] = "Pribadi";
?>