<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SupportManagerKbArticles.!error.company_id.exists'] = "ID perusahaan tidak valid.";
$lang['SupportManagerKbArticles.!error.content.empty'] = "Ketikkan judul dan konten untuk setidaknya satu bahasa.";
$lang['SupportManagerKbArticles.!error.content[][lang].length'] = "Setiap kode bahasa harus 5 karakter.";
$lang['SupportManagerKbArticles.!error.content[][title].length'] = "Setiap judul konten tidak boleh melebihi 255 karakter.";
$lang['SupportManagerKbArticles.!error.article_id.exists'] = "ID kategori tidak valid.";
$lang['SupportManagerKbArticles.access_types.public'] = "Publik";
$lang['SupportManagerKbArticles.access_types.hidden'] = "Tersembunyi";
$lang['SupportManagerKbArticles.content_types.text'] = "Penurunan harga";
?>