<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SupportManagerDepartments.!error.company_id.exists'] = "ID perusahaan tidak valid.";
$lang['SupportManagerDepartments.!error.email.format'] = "Silakan masukkan alamat email yang valid.";
$lang['SupportManagerDepartments.!error.method.imap'] = "ekstensi PHP IMAP diperlukan untuk men-download pesan melalui POP3 atau IMAP.";
$lang['SupportManagerDepartments.!error.default_priority.format'] = "Jenis prioritas bawaan tidak valid.";
$lang['SupportManagerDepartments.!error.host.format'] = "Masukkan nama host yang valid.";
$lang['SupportManagerDepartments.!error.host.length'] = "Nama host tidak boleh melebihi 128 karakter.";
$lang['SupportManagerDepartments.!error.user.length'] = "Nama pengguna tidak boleh melebihi 64 karakter.";
$lang['SupportManagerDepartments.!error.password.format'] = "Silakan masukkan password.";
$lang['SupportManagerDepartments.!error.port.length'] = "port tidak dapat melebihi 6 digit.";
$lang['SupportManagerDepartments.!error.service.format'] = "Silahkan memilih tipe layanan yang valid.";
$lang['SupportManagerDepartments.!error.security.format'] = "Silakan memilih jenis keamanan yang valid.";
$lang['SupportManagerDepartments.!error.mark_messages.valid'] = "Pesan menggunakan POP3 hanya dapat ditandai sebagai dihapus.";
$lang['SupportManagerDepartments.!error.status.format'] = "Jenis Status keliru";
$lang['SupportManagerDepartments.!error.department_id.exists'] = "ID departemen tidak valid.";
$lang['SupportManagerDepartments.methods.none'] = "Tidak Ada";
$lang['SupportManagerDepartments.methods.pipe'] = "Piping";
$lang['SupportManagerDepartments.methods.pop3'] = "POP3";
$lang['SupportManagerDepartments.statuses.hidden'] = "Tersembunyi";
$lang['SupportManagerDepartments.priorities.emergency'] = "Keadaan darurat";
$lang['SupportManagerDepartments.priorities.critical'] = "Kritis";
$lang['SupportManagerDepartments.priorities.medium'] = "Medium";
$lang['SupportManagerDepartments.priorities.low'] = "Rendah";
$lang['SupportManagerDepartments.security_types.none'] = "Tak satupun";
$lang['SupportManagerDepartments.security_types.tls'] = "TLS";
$lang['SupportManagerDepartments.message_types.deleted'] = "Dihapus";
$lang['SupportManagerDepartments.!error.override_from_email.format'] = "Apakah mengizinkan alamat email departemen ini yang akan digunakan sebagai dari alamat email template, harus diatur ke 0 atau 1.";
$lang['SupportManagerDepartments.!error.close_ticket_interval.format'] = "Silakan pilih interval tiket terdekat yang valid.";
$lang['SupportManagerDepartments.ticket_intervals.days'] = "%1\$s hari"; // %1$s is the number of days
?>