<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SupportManagerPlugin.cron.poll_tickets_desc'] = "Menghubungkan ke server POP3 / IMAP untuk men-download email dan mengubahnya menjadi tiket.";
$lang['SupportManagerPlugin.nav_primary_staff.tickets'] = "Tiket";
$lang['SupportManagerPlugin.nav_primary_staff.departments'] = "Departemen";
$lang['SupportManagerPlugin.nav_primary_staff.staff'] = "Staf";
$lang['SupportManagerPlugin.widget_staff_client.tickets'] = "Tiket";
$lang['SupportManagerPlugin.event_getsearchoptions.tickets'] = "Pnecarian Tiket";
$lang['SupportManagerPlugin.permission.admin_main'] = "Support";
$lang['SupportManagerPlugin.permission.admin_tickets_client'] = "Widget Profil Klien";
$lang['SupportManagerPlugin.permission.admin_responses'] = "Tanggapan";
$lang['SupportManagerPlugin.permission.admin_staff'] = "Staff";
$lang['SupportManagerPlugin.cron.close_tickets_name'] = "Tutup Tiket";
$lang['SupportManagerPlugin.cron.close_tickets_desc'] = "Otomatis menutup tiket terbuka sebagai sedang dikonfigurasi untuk departemen Support Manager.";
?>