<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SupportManagerStaff.!error.staff_id.belongs'] = "Anggota staf bukan karyawan perusahaan yang sedang ditugaskan.";
$lang['SupportManagerStaff.!error.staff_id.duplicate'] = "Anggota staf yang dipilih sudah ada di support system.";
$lang['SupportManagerStaff.!error.schedules.minimum'] = "Silakan menetapkan jadwal waktu mulai dan akhir untuk setidaknya satu hari.";
$lang['SupportManagerStaff.!error.schedules[][start_time].format'] = "Silakan pilih waktu mulai untuk setiap hari yang telah dijadwalkan";
$lang['SupportManagerStaff.!error.schedules[][end_time].format'] = "Silakan pilih waktu akhir untuk setiap jadwal harian";
$lang['SupportManagerStaff.days.sun'] = "Minggu";
$lang['SupportManagerStaff.days.mon'] = "Senin";
$lang['SupportManagerStaff.days.tue'] = "Selasa";
$lang['SupportManagerStaff.days.wed'] = "Rabu";
?>