<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SupportManagerTickets.!error.code.format'] = "Kode tiket harus berisi angka saja.";
$lang['SupportManagerTickets.!error.staff_id.exists'] = "Anggota staf yang dipilih untuk tiket ini tidak ada.";
$lang['SupportManagerTickets.!error.service_id.exists'] = "Layanan yang dipilih untuk tiket ini tidak ada.";
$lang['SupportManagerTickets.!error.client_id.exists'] = "Klien terpilih untuk tiket ini tidak ada";
$lang['SupportManagerTickets.!error.email.format'] = "Silahkan Masukkan alamat email yang valid.";
$lang['SupportManagerTickets.!error.status.format'] = "Silakan pilih status valid.";
$lang['SupportManagerTickets.!error.type.new_valid'] = "Tiket baru harus memiliki tulisan dari 'balasan'.";
$lang['SupportManagerTickets.priority.emergency'] = "Keadaan darurat";
$lang['SupportManagerTickets.priority.high'] = "Tinggi";
$lang['SupportManagerTickets.priority.low'] = "Rendah";
$lang['SupportManagerTickets.status.open'] = "Terbuka";
$lang['SupportManagerTickets.type.reply'] = "Balas";
$lang['SupportManagerTickets.log.summary'] = "Ringkasan telah diperbarui.";
$lang['SupportManagerTickets.log.priority'] = "Prioritas telah diubah untuk %1\$s."; // %1$s is the priority
$lang['SupportManagerTickets.log.status'] = "Status telah diubah menjadi %1\$s."; // %1$s is the status
$lang['SupportManagerTickets.log.unassigned'] = "tidak Ditugaskan";
$lang['SupportManagerTickets.status.awaiting_reply'] = "Menunggu Balasan";
$lang['SupportManagerTickets.!error.replies.valid'] = "Setidaknya satu tiket balasan dengan ID tidak valid, atau semua balasan telah dipilih. Anda harus meninggalkan setidaknya satu balasan yang tersisa.";
$lang['SupportManagerTickets.!error.tickets.valid'] = "Setidaknya satu tiket yang dipilih tidak valid, ditutup, atau bukan milik klien yang sama sebagai tiket yang dipilih.";
$lang['SupportManagerTickets.!error.tickets.service_matches'] = "Setidaknya satu tiket tidak dapat ditetapkan untuk layanan yang diberikan karena bukan milik klien terkait.";
$lang['SupportManagerTickets.merge.reply'] = "Tiket ini telah bergabung ke dalam tiket #%1\$s."; // %1$s is the ticket number
$lang['SupportManagerTickets.!error.replies.notes'] = "Catatan balasan tiket tidak dapat dibagi menjadi tiket terpisah tanpa juga termasuk balasan tiket.";
?>