<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['TransactionsApplied.name'] = "Transaksi Diterapkan";
$lang['TransactionsApplied.options.field_start_date'] = "Tangga lMulai ";
$lang['TransactionsApplied.options.field_gateway'] = "Gateway";
$lang['TransactionsApplied.options.field_payment_type'] = "Jenis Pembayaran";
$lang['TransactionsApplied.heading.transaction_id'] = "ID transaksi";
$lang['TransactionsApplied.heading.client_id_code'] = "Klien #";
$lang['TransactionsApplied.heading.gateway_name'] = "Gateway Pembayaran";
$lang['TransactionsApplied.heading.type_name'] = "Tipe Pembayaran";
$lang['TransactionsApplied.heading.applied_amount'] = "Jumlah yang diterapkan";
$lang['TransactionsApplied.heading.status'] = "Status";
$lang['TransactionsApplied.heading.applied_date'] = "Tanggal Diterapkan";
?>