<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Payflow.!error.user.empty'] = "Masukkan pengguna yang berwenang untuk memproses transaksi.";
$lang['Payflow.!error.test_mode.valid'] = "Test mode harus diatur ke \"true\" jika diaktifkan";
$lang['Payflow.vendor'] = "Vendor / Merchant Login";
$lang['Payflow.user'] = "Pengguna";
$lang['Payflow.test_mode'] = "Test Mode";
$lang['Payflow.tooltip_user'] = "Jika Anda memiliki lebih dari satu pengaturan pengguna untuk account Anda, masukkan pengguna berwenang untuk memproses transaksi. Jika tidak, masukkan nilai yang sama dengan Vendor / Merchant Login.";
$lang['Payflow.tooltip_partner'] = "Ini adalah mitra merchant yang diberikan kepada Anda oleh reseller resmi PayPal yang mendaftarkaan Anda untuk SDK Payflow. Jika akun Anda dibeli dari PayPal langsung, gunakan \"PayPal\" sebagai gantinya.";
?>