<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['_2Checkout.name'] = "2Checkout";
$lang['_2Checkout.vendor_id'] = "Nomor rekening penjual";
$lang['_2Checkout.secret_word'] = "Kata Rahasia";
$lang['_2Checkout.api_username'] = "Nama Pengguna API";
$lang['_2Checkout.api_username_note'] = "Sandi API diperlukan untuk proses pengembalian uang melalui 2Checkout.";
$lang['_2Checkout.api_password'] = "Sandi API";
$lang['_2Checkout.test_mode'] = "Test Mode";
$lang['2Checkout.refund.comment'] = "Memulai pengembalian dana untuk %1\$s."; // %1$s is the refund amount
$lang['_2Checkout.buildprocess.submit'] = "Bayer dengan menggunakan 2Checkout.";
$lang['_2Checkout.!error.vendor_id.empty'] = "Masukan nomor penjual rekening anda";
$lang['_2Checkout.!error.secret_word.empty'] = "Masukan Kode Rahasia Anda";
$lang['_2Checkout.!error.test_mode.valid'] = "Tes mode harus diatur ke \"true\" atau \"false\"";
$lang['_2Checkout.!error.key.valid'] = "Kunci digunakan untuk verifikasi 2CheckOut tidak valid";
$lang['_2Checkout.!error.credit_card_processed.completed'] = "Proses Transaksi Tidak Berhasil !";
$lang['_2Checkout.!error.sid.valid'] = "Nomor rekening penjual tidak sesuai dengan nomor rekenig transaksi yang disediakan";
?>