<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PayJunction.name'] = "PayJunction";
$lang['PayJunction.api_key'] = "API Key";
$lang['PayJunction.password'] = "Kata sandi";
$lang['PayJunction.test_mode_note'] = "Mengaktifkan Mode Pengembang maka akan memposting transaksi ke PayJunction Labs mode demo. Anda harus menggunakan username dan password demo, serta Labs API Key anda, untuk menggunakan mode Developer.";
$lang['PayJunction.!error.password.empty'] = "Masukkan password akun Anda.";
?>