<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['TransactionsReceived.name'] = "Transaksi Diterima";
$lang['TransactionsReceived.options.field_start_date'] = "Mulai tanggal";
$lang['TransactionsReceived.options.field_end_date'] = "Tanggal Akhir";
$lang['TransactionsReceived.options.field_gateway'] = "Gateway";
$lang['TransactionsReceived.heading.id'] = "Transaksi #";
$lang['TransactionsReceived.heading.transaction_id'] = "ID transaksi";
$lang['TransactionsReceived.heading.reference_id'] = "ID Referensi ";
$lang['TransactionsReceived.heading.type_name'] = "Tipe pembayaran";
$lang['TransactionsReceived.heading.currency'] = "Mata Uang";
$lang['TransactionsReceived.heading.status'] = "Status";
?>