<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PaypalPaymentsStandard.name'] = "PayPal (Pembayaran Standar)";
$lang['PaypalPaymentsStandard.account_id'] = " Akun Email PayPal";
$lang['PaypalPaymentsStandard.api_username_note'] = "Ini, serta API Password dan API Signature, diperlukan untuk memproses pengembalian uang melalui PayPal.";
$lang['PaypalPaymentsStandard.api_password'] = "API Sandi";
$lang['PaypalPaymentsStandard.api_signature'] = "API Signature";
$lang['PaypalPaymentsStandard.pay_type'] = "Opsi Pembayaran";
$lang['PaypalPaymentsStandard.pay_type_subscribe'] = "Hanya Pembayaran Berlangganan";
$lang['PaypalPaymentsStandard.modify'] = "Memungkinkan pengguna untuk memodifikasi dan membuat langganan baru";
$lang['PaypalPaymentsStandard.buildprocess.submit'] = "Membayar dengan PayPal";
$lang['PaypalPaymentsStandard.!error.dev_mode.valid'] = "Mode pengembang harus diatur ke \"true\" jika diberikan.";
?>