<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Centoswebpanel.name'] = "CentOS WebPanel";
$lang['Centoswebpanel.tab_firewall'] = "Firewall";
$lang['Centoswebpanel.add_row.name_server_btn'] = "Tambahkan Name Server Tambahan";
$lang['Centoswebpanel.add_row.name_server_host_col'] = "Hostname";
$lang['Centoswebpanel.service_field.tooltip.username'] = "Anda dapat membiarkan nama pengguna kosong untuk diisi secara otomatis.";
?>