<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Plesk.!error.simplexml_required'] = "Ekstensi xml sederhana dibutuhkan untuk modul ini";
$lang['Plesk.!error.api.internal'] = "Sebuah kesalahan internal terjadi, atau server tidak menanggapi permintaan tersebut.";
$lang['Plesk.!error.server_name.empty'] = "Anda harus memasukkan Label Server.";
$lang['Plesk.!error.port.format'] = "Nomor port harus berupa angka.";
$lang['Plesk.!error.username.empty'] = "Silakan masukkan nama pengguna.";
$lang['Plesk.!error.password.empty'] = "Masukkan password.";
$lang['Plesk.!error.meta[plan].empty'] = "Silahkan pilih paket layanan.";
$lang['Plesk.!error.meta[reseller_plan].empty'] = "Silakan pilih plan untuk akun reseller.";
$lang['Plesk.!error.meta[type].valid'] = "Jenis Akun haruslah standar atau reseller.";
$lang['Plesk.!error.plesk_username.length'] = "Username harus antara 1 dan 60 karakter.";
$lang['Plesk.!error.plesk_confirm_password.matches'] = "Password tidak cocok.";
$lang['Plesk.!error.plesk_webspace_id.exists'] = "ID Berlangganan yang diberikan tidak ada di Plesk.";
$lang['Plesk.please_select'] = "Silahkan pilih";
$lang['Plesk.tab_stats'] = "Statistik";
$lang['Plesk.tab_client_stats'] = "Statistik";
$lang['Plesk.stats.unlimited'] = "Unlimited";
$lang['Plesk.tab_stats.info_heading.value'] = "Nilai";
$lang['Plesk.tab_stats.bandwidth_heading.used'] = "Terpakai";
$lang['Plesk.tab_stats.bandwidth_heading.limit'] = "Batas";
$lang['Plesk.tab_stats.disk_heading.used'] = "Digunakan";
$lang['Plesk.tab_stats.disk_heading.limit'] = "Limit";
$lang['Plesk.tab_stats.info.domain'] = "Domain";
$lang['Plesk.tab_client_stats.info_heading.field'] = "Bidang";
$lang['Plesk.name'] = "Plesk";
$lang['Plesk.module_row_plural'] = "Server";
$lang['Plesk.module_group'] = "Server Group";
$lang['Plesk.service_field.password'] = "Password";
$lang['Plesk.service_field.confirm_password'] = "Konfirmasi Kata Sandi";
$lang['Plesk.service_field.webspace_id'] = "Berlangganan (Webspace) ID";
$lang['Plesk.service_field.tooltip.password'] = "nda dapat membiarkan password kosong untuk menghasilkannya secara otomatis.";
$lang['Plesk.service_field.tooltip.webspace_id_edit'] = "ID Berlangganan hanya akan berubah secara lokal. Ini tidak akan berubah dalam Plesk.";
$lang['Plesk.package_fields.plan'] = "Rencana Layanan Plesk";
$lang['Plesk.package_fields.type'] = "Jenis Akun";
$lang['Plesk.service_info.username'] = "Username";
$lang['Plesk.add_row.box_title'] = "Tambahkan Plesk Server";
$lang['Plesk.add_row.basic_title'] = "Pengaturan Dasar";
$lang['Plesk.edit_row.basic_title'] = "Pengaturan Dasar";
$lang['Plesk.row_meta.username'] = "Username";
$lang['Plesk.row_meta.password'] = "Kata Sandi";
$lang['Plesk.row_meta.panel_version'] = "Plesk Panel Versi";
$lang['Plesk.add_module_row'] = "Tambahkan Server";
$lang['Plesk.add_module_group'] = "Tambahkan Server Group";
$lang['Plesk.manage.module_rows_title'] = "Server";
$lang['Plesk.manage.module_rows_heading.ip_address'] = "IP Address";
$lang['Plesk.manage.module_rows_heading.options'] = "Pilihan";
$lang['Plesk.manage.module_groups_heading.name'] = "Nama kelompok";
$lang['Plesk.manage.module_groups_heading.servers'] = "Hitungan Server ";
$lang['Plesk.manage.module_groups_heading.options'] = "Pilihan";
$lang['Plesk.manage.module_rows.edit'] = "Edit";
$lang['Plesk.manage.module_groups.edit'] = "Edit";
$lang['Plesk.manage.module_groups_no_results'] = "Tidak ada kelompok server";
$lang['Plesk.panel_version.plesk_type'] = "Plesk %1\$s for %2\$s"; // %1$s is the Plesk panel version number, %2$s is the OS type (i.e. Windows or Linux/Unix)
$lang['Plesk.panel_version.parallels'] = "Parallels Plesk Panel %1\$s"; // %1$s is the Plesk panel version number
$lang['Plesk.!error.api.webspace_delete_filter_missing'] = "Hilangakan filter untuk menghapus langganan tertentu.";
$lang['Plesk.service_info.options'] = "Pilihan";
$lang['Plesk.tab_client_stats.disk_title'] = "Penggunaan Diska";
?>