<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['MulticraftModule.!error.json.unavailable'] = "JSON extension diperlukan oleh modul ini.";
$lang['MulticraftModule.!error.server_name.empty'] = "Masukkan label untuk server ini.";
$lang['MulticraftModule.!error.panel_url.empty'] = "Cukup masukkan URL ke panel Multicraft Anda.";
$lang['MulticraftModule.!error.panel_api_url.empty'] = "Silahkan masukkan URL untuk Multicraft panel API Anda.";
$lang['MulticraftModule.!error.key.empty'] = "Masukkan API key Anda";
$lang['MulticraftModule.!error.ips.match'] = "Silahkan tetapkan sebuah alamat IP untuk setiap Daemon set.";
?>