<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['MulticraftService.!error.client'] = "Tidak ada klien ditemukan untuk membuat user Multicraft.";
$lang['MulticraftService.!error.server_id.format'] = "Server ID harus berupa angka, atau biarkan kosong.";
$lang['MulticraftService.!error.daemon_id.format'] = "Daemon ID harus integer, atau biarkan kosong.";
$lang['MulticraftService.!error.port.format'] = "Harap isikan nomor port yang benar, atau biarkan kosong";
$lang['MulticraftService.service_fields.server_id'] = "Server ID";
$lang['MulticraftService.service_fields.tooltip.user_id'] = "Atur ID unik dari Pengguna Multicraft yang mana layanan ini akan ditetapkan. atau Biarkan kosong untuk sebaliknya sebaliknya.";
$lang['MulticraftService.service_fields.tooltip.daemon_id'] = "Tentukan ID pada Multicraft daemon yang akan ditugaskan, atau biarkan kosong";
$lang['MulticraftService.service_fields.ip'] = "Alamat IP";
$lang['MulticraftService.service_fields.tooltip.ip'] = "Nama";
$lang['MulticraftService.service_fields.no'] = "Tidak";
$lang['MulticraftService.!error.configoptions[user_players].format'] = "Apakah pemilik server dapat mengatur jumlah pemain harus diatur ke 1 atau 0.";
$lang['MulticraftService.!error.configoptions[dedicated_ip].format'] = "Jika menggunakan IP dedicated harus di set ke 1 atau 0.";
?>