<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Multicraft.module_row.name'] = "Server";
$lang['Multicraft.add_module_row'] = "Tambah Server";
$lang['Multicraft.manage.module_rows_title'] = "Server";
$lang['Multicraft.manage.module_rows_heading.username'] = "Nama Pengguna";
$lang['Multicraft.manage.module_rows_heading.server_name'] = "Label Server ";
$lang['Multicraft.manage.module_rows_heading.panel_api_url'] = "URL Panel API";
$lang['Multicraft.manage.module_rows_heading.options'] = "Pilihan";
$lang['Multicraft.manage.module_rows.delete'] = "Hapus";
$lang['Multicraft.manage.module_rows.confirm_delete'] = "Apakah Anda yakin ingin menghapus server ini?";
$lang['Multicraft.manage.module_rows_no_results'] = "Tidak ada server.";
$lang['Multicraft.manage.module_rows_in_use_0'] = "Tidak";
$lang['Multicraft.service_info.options'] = "Pilihan";
$lang['Multicraft.service_info.option_login'] = "Masuk";
$lang['Multicraft.tab_client_actions.heading_server_address'] = "Alamat Server";
$lang['Multicraft.tab_client_actions.heading_server_actions'] = "Tindakan Server";
$lang['Multicraft.tab_client_actions.action_restart'] = "Mengulang Kembali";
$lang['Multicraft.tab_client_actions.action_stop'] = "Berhenti";
$lang['Multicraft.tab_client_console.field_server_name'] = "Nama Server";
$lang['Multicraft.tab_client_actions.submit_save'] = "Simpan";
$lang['Multicraft.tab_client_players.heading_player_name'] = "Nama Pemain";
$lang['Multicraft.tab_client_players.heading_action'] = "Tindakan";
$lang['Multicraft.tab_client_players.action_kick'] = "Tendang Pemain";
$lang['Multicraft.tab_client_players.no_results'] = "Tidak ada pemain yang terhubung.";
$lang['Multicraft.tab_client_players.heading_console'] = "Server Console";
$lang['Multicraft.tab_client_console.submit_send'] = "Mengirim";
$lang['Multicraft.tab_client_console.submit_clear_log'] = "Clear Log";
$lang['Multicraft.tab_client_players.heading_console_tab'] = "Log Konsol";
$lang['Multicraft.tab_client_players.heading_chat_tab'] = "Log chatting";
$lang['Multicraft.add_row.add_btn'] = "Tambahkan Server";
$lang['Multicraft.add_row.remove_ip'] = "Menghapus";
$lang['Multicraft.add_row.ip_col'] = "IP Address";
$lang['Multicraft.add_row.in_use_col'] = "Terpakai";
$lang['Multicraft.edit_row.add_btn'] = "Edit Server";
$lang['Multicraft.edit_row.ip_btn'] = "Tambah Alamat Ip";
$lang['Multicraft.edit_row.ip_col'] = "IP Address";
$lang['Multicraft.!tooltip.panel_url'] = "Masukkan URL untuk panel Multicraft Anda. misalnya http://multicraft.domain.com/";
$lang['Multicraft.!tooltip.key'] = "Masukkan kunci API yang telah dihasilkan untuk nama pengguna Anda di Multicraft.";
$lang['Multicraft.!tooltip.log_all'] = "Periksa semua log permintaan API, atau hapus centang hanya untuk log permintaan penting.";
$lang['Multicraft.row_meta.server_name'] = "Label Server ";
$lang['Multicraft.row_meta.username'] = "Nama pengguna";
$lang['Multicraft.row_meta.key'] = "API Key";
$lang['Multicraft.row_meta.log_all'] = "Log Semua Permintaan API";
?>