<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Accounts.!error.contact_id.exists'] = "ID kontak tidak valid.";
$lang['Accounts.!error.first_name.empty'] = "Tentukan nama pertama.";
$lang['Accounts.!error.last_name.empty'] = "Tentukan nama belakang.";
$lang['Accounts.!error.state.length'] = "Panjang negara tidak boleh melebihi 3 karakter.";
$lang['Accounts.!error.country.length'] = "Panjang negara tidak boleh melebihi 3 karakter.";
$lang['Accounts.!error.state.country_exists'] = "Silakan pilih negara yang sesuai dengan negara yang dipilih.";
$lang['Accounts.!error.account.length'] = "Silakan tentukan nomor rekening.";
$lang['Accounts.!error.routing.empty'] = "Silakan tentukan nomor routing.";
$lang['Accounts.!error.last4.empty_ach'] = "Masukkan empat digit terakhir dari nomor rekening.";
$lang['Accounts.!error.type.ach_format'] = "Tipe tidak valid.";
$lang['Accounts.!error.ach_account_id.exists'] = "ID akun tidak valid.";
$lang['Accounts.!error.number.valid'] = "Nomor kartu yang diberikan tidak valid.";
$lang['Accounts.!error.expiration.empty'] = "Masukkan tanggal kadaluarsa kartu kredit.";
$lang['Accounts.!error.expiration.valid'] = "The expiration date has already lapsed.";
$lang['Accounts.!error.last4.empty_cc'] = "Masukkan empat digit terakhir dari nomor kartu kredit.";
$lang['Accounts.!error.type.cc_format'] = "Jenis kartu tidak valid atau tidak dapat ditentukan.";
$lang['Accounts.!error.cc_account_id.exists'] = "ID akun tidak valid.";
$lang['Accounts.getTypes.cc'] = "Credit Card";
$lang['Accounts.getTypes.ach'] = "Automated Clearing House";
$lang['Accounts.getTypes.other'] = "Lain";
$lang['Accounts.getAchTypes.checking'] = "Memeriksa";
$lang['Accounts.getAchTypes.savings'] = "Tabungan";
$lang['Accounts.getCcTypes.amex'] = "American Express";
$lang['Accounts.getCcTypes.bc'] = "Bankcard";
$lang['Accounts.getCcTypes.cup'] = "China Union Pay";
$lang['Accounts.getCcTypes.dc-cb'] = "Diners Club Carte Blanche";
$lang['Accounts.getCcTypes.dc-er'] = "Diners Club Enroute";
$lang['Accounts.getCcTypes.dc-int'] = "Diners Club International";
$lang['Accounts.getCcTypes.dc-uc'] = "Diners Club AS dan Kanada";
$lang['Accounts.getCcTypes.disc'] = "Temukan";
$lang['Accounts.getCcTypes.ipi'] = "InstaPayment";
$lang['Accounts.getCcTypes.jcb'] = "Biro Kredit Jepang";
$lang['Accounts.getCcTypes.lasr'] = "Laser";
$lang['Accounts.getCcTypes.maes'] = "Maestro";
$lang['Accounts.getCcTypes.mc'] = "Master Card";
$lang['Accounts.getCcTypes.solo'] = "Solo";
$lang['Accounts.getCcTypes.switch'] = "Beralih";
$lang['Accounts.getCcTypes.visa'] = "Visa";
?>