<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSystemStaff.!success.group_added'] = "Staff group, \"%1\$s\", Berhasil dibuat!"; // %1$s is the name of the staff group
$lang['AdminSystemStaff.manage.category_inactive'] = "Non-aktif";
$lang['AdminSystemStaff.manage.categorylink_addstaff'] = "Tambahkan Staf";
$lang['AdminSystemStaff.manage.heading_email'] = "E-mail";
$lang['AdminSystemStaff.manage.no_results'] = "Tidak ada anggota staf dengan status ini.";
$lang['AdminSystemStaff.manage.confirm_reactivate'] = "Benar-benar mengaktifkan kembali anggota staff ini?";
$lang['AdminSystemStaff.manage.option_edit'] = "Edit";
$lang['AdminSystemStaff.manage.option_deactivate'] = "Menonaktifkan";
$lang['AdminSystemStaff.manage.option_reactivate'] = "Mengaktifkan kembali";
$lang['AdminSystemStaff.groups.option_delete'] = "Hapus";
$lang['AdminSystemStaff.add.heading_groups'] = "Grup";
$lang['AdminSystemStaff.add.field_firstname'] = "Nama Depan";
$lang['AdminSystemStaff.add.field_email'] = "E-mail";
$lang['AdminSystemStaff.add.field_username_username'] = "Masukkan username";
$lang['AdminSystemStaff.add.field_username_email'] = "Gunakan alamat email sebagai username";
$lang['AdminSystemStaff.add.field_confirmpass'] = "Konfirmasi Password";
$lang['AdminSystemStaff.add.field_twofactormode'] = "Otentikas iDua Faktor";
$lang['AdminSystemStaff.add.field_twofactorkey'] = "Kunci Dua Faktor";
$lang['AdminSystemStaff.add.text_membergroups'] = "Anggota Grup";
$lang['AdminSystemStaff.edit.boxtitle_editstaff'] = "Edit Staff";
$lang['AdminSystemStaff.edit.heading_contact'] = "Info kontak";
$lang['AdminSystemStaff.edit.field_firstname'] = "Nama";
$lang['AdminSystemStaff.edit.field_lastname'] = "Nama Belakang";
$lang['AdminSystemStaff.edit.field_username'] = "Nama Pengguna";
$lang['AdminSystemStaff.edit.field_email'] = "E-mail";
$lang['AdminSystemStaff.edit.field_confirmpass'] = "Konfirmasi Kata Sandi";
$lang['AdminSystemStaff.edit.text_membergroups'] = "Anggota Grup";
$lang['AdminSystemStaff.edit.text_availablegroups'] = "Grup yang tersedia";
$lang['AdminSystemStaff.groups.boxtitle_groups'] = "Staf Grup";
$lang['AdminSystemStaff.groups.categorylink_addgroup'] = "Buat Grup";
$lang['AdminSystemStaff.groups.heading_name'] = "Nama";
$lang['AdminSystemStaff.groups.heading_company_name'] = "Nama Perusahaan";
$lang['AdminSystemStaff.groups.heading_options'] = "Pilihan";
$lang['AdminSystemStaff.groups.option_edit'] = "Edit";
$lang['AdminSystemStaff.groups.modal_delete'] = "Apakah Anda yakin ingin menghapus kelompok staf ini?";
$lang['AdminSystemStaff.addgroup.boxtitle_addgroup'] = "Buat Grup";
$lang['AdminSystemStaff.addgroup.field_name'] = "Nama";
$lang['AdminSystemStaff.addgroup.field_company'] = "Perusahaan";
$lang['AdminSystemStaff.addgroup.field_groupsubmit'] = "Buat Grup";
$lang['AdminSystemStaff.addgroup.heading_general'] = "Umum";
$lang['AdminSystemStaff.addgroup.heading_permissions'] = "Access Control List";
$lang['AdminSystemStaff.editgroup.field_name'] = "Nama";
$lang['AdminSystemStaff.editgroup.field_company'] = "Perusahaan";
$lang['AdminSystemStaff.editgroup.field_groupsubmit'] = "edit Grup";
$lang['AdminSystemStaff.editgroup.dialog_confirm_edit_assigned'] = "Anda sedang ditugaskan untuk kelompok staf ini. Setiap perubahan yang Anda buat akan segera berlaku dan Anda mungkin tidak dapat mengakses daerah ini lagi. Apakah Anda yakin ingin membuat perubahan ini?";
$lang['AdminSystemStaff.manage.page_title'] = "Pengaturan > Sistem> Staf> Kelola Staf";
$lang['AdminSystemStaff.add.page_title'] = "Settings> System> Staf> Tambah Staf";
$lang['AdminSystemStaff.groups.page_title'] = "Pengaturan > Sistem > Staf > Staf Grup";
$lang['AdminSystemStaff.!groups.text_separator'] = "/";
$lang['AdminSystemStaff.!groups.text_group_start'] = "(";
$lang['AdminSystemStaff.!groups.text_group_end'] = ")";
$lang['AdminSystemStaff.addgroup.text_check_all'] = "Centang Semua";
$lang['AdminSystemStaff.addgroup.text_uncheck_all'] = "Hapus tanda centang Semua";
$lang['AdminSystemStaff.add.field_addsubmit'] = "Buat Staf";
$lang['AdminSystemStaff.edit.field_editsubmit'] = "Edit Staff";
$lang['AdminSystemStaff.addgroup.heading_subscription_email_notices'] = "Pemberitahuan Email Berlangganan";
$lang['AdminSystemStaff.editgroup.heading_subscription_email_notices'] = "Pemberitahuan Email Berlangganan";
?>