<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSettings.company.category_system'] = "Sistem";
$lang['AdminSettings.company.heading_general'] = "Umum";
$lang['AdminSettings.company.text_billing'] = "Konfigurasikan opsi faktur dan kustomisasi, pembayaran otomatis, pemberitahuan pembayaran, dan kupon.";
$lang['AdminSettings.company.heading_emails'] = "Email";
$lang['AdminSettings.company.text_automation'] = "Akses dan kontrol tugas otomatis di Blesta.";
$lang['AdminSettings.company.heading_gateways'] = "Gateway Pembayaran";
$lang['AdminSettings.company.text_gateways'] = "Enable and disable merchant and non-merchant payment processors untuk penerimaan pembayaran.";
$lang['AdminSettings.company.heading_plugins'] = "Plugins";
$lang['AdminSettings.system.category_company'] = "Perusahaan";
$lang['AdminSettings.system.category_system'] = "Sistem";
$lang['AdminSettings.system.heading_companies'] = "Perusahaan
";
$lang['AdminSettings.system.text_companies'] = "Menambah atau memperbarui perusahaan.";
$lang['AdminSettings.system.text_api'] = "Mengontrol akses ke API instalasi ini.";
$lang['AdminSettings.system.text_automation'] = "Tentukan informasi Cron atau Scheduled Task";
$lang['AdminSettings.system.heading_staff'] = "Staff";
$lang['AdminSettings.system.heading_upgrade'] = "Pilihan Upgrade";
$lang['AdminSettings.system.text_upgrade'] = "Lihat upgrade informasi dan download.";
$lang['AdminSettings.system.heading_help'] = "Bantu";
$lang['AdminSettings.system.text_help'] = "Lihat bantuan untuk instalasi Blesta.";
$lang['AdminSettings.system.text_backup'] = "Konfigurasi backup otomatis menggunakan SFTP, atau Amazon S3, atau men-download backup ke komputer lokal Anda.";
$lang['AdminSettings.company.heading_lookandfeel'] = "Lihat dan rasakan";
$lang['AdminSettings.company.text_lookandfeel'] = "Sesuaikan tampilan dan nuansa dari Blesta dengan mengelola tema warna, atau memperbarui template antarmuka klien.";
?>