<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyGeneral.!success.localization_updated'] = "Pengaturan lokalisasi telah berhasil diperbarui.";
$lang['AdminCompanyGeneral.!success.encryption_updated'] = "Pengaturan enkripsi telah berhasil diperbarui.";
$lang['AdminCompanyGeneral.!success.contact_type_added'] = "Kontak jenis \"%1\$s\" telah berhasil ditambahkan."; // %1$s is the name of the contact type
$lang['AdminCompanyGeneral.!success.contact_type_deleted'] = "Tipe kontak \"%1\$s\" telah berhasil dihapus."; // %1$s is the name of the contact type
$lang['AdminCompanyGeneral.localization.text_monday'] = "Senin";
$lang['AdminCompanyGeneral.localization.text_datetimeformat'] = "Tanggal Format Waktu";
$lang['AdminCompanyGeneral.localization.text_localizationsubmit'] = "Update Setting";
$lang['AdminCompanyGeneral.international.boxtitle_international'] = "Internasionalisasi";
$lang['AdminCompanyGeneral.international.text_language'] = "Bahasa";
$lang['AdminCompanyGeneral.international.text_options'] = "Pilihan";
$lang['AdminCompanyGeneral.international.option_install'] = "Memasang";
$lang['AdminCompanyGeneral.international.option_uninstall'] = "Uninstall";
$lang['AdminCompanyGeneral.!notice.passphrase_set'] = "PERINGATAN: passphrase telah ditetapkan. Anda diminta untuk pembayaran batch passphras secara manual. Mengubah kata sandi untuk passphrase / kosong akan menghapus persyaratan ini.";
$lang['AdminCompanyGeneral.encryption.boxtitle_encryption'] = "Enkripsi";
$lang['AdminCompanyGeneral.encryption.field_current_passphrase'] = "Private Key Passphrase Saat ini";
$lang['AdminCompanyGeneral.encryption.field_private_key_passphrase'] = "Passphrase Private Key Baru";
$lang['AdminCompanyGeneral.encryption.field_confirm_new_passphrase'] = "Konfirmasikan Kombinasi Sandi Rahasia";
$lang['AdminCompanyGeneral.encryption.field_agree'] = "Saya telah menyimpan kata sandi ini ke lokasi yang aman";
$lang['AdminCompanyGeneral.contacttypes.boxtitle_types'] = "Jenis Kontak";
$lang['AdminCompanyGeneral.contacttypes.heading_name'] = "Nama";
$lang['AdminCompanyGeneral.contacttypes.option_delete'] = "Hapus";
$lang['AdminCompanyGeneral.addcontacttype.field_name'] = "Nama";
$lang['AdminCompanyGeneral.addcontacttype.field_is_lang'] = "Gunakan Bahasa Definisi";
$lang['AdminCompanyGeneral.addcontacttype.field_contacttypesubmit'] = "Buat Jenis Kontak";
$lang['AdminCompanyGeneral.editcontacttype.field_is_lang'] = "Gunakan Bahasa Definisi";
$lang['AdminCompanyGeneral.localization.page_title'] = "Pengaturan> Perusahaan> General> Lokalisasi";
$lang['AdminCompanyGeneral.international.page_title'] = "Pengaturan> Perusahaan> Umum> Internasionalisasi";
$lang['AdminCompanyGeneral.editcontacttype.page_title'] = "Settings > Company > General > Edit Contact Type";
$lang['AdminCompanyGeneral.!success.language_uninstalled'] = "Bahasa %1\$s telah berhasil dihapus."; // %1$s is the name of the language
$lang['AdminCompanyGeneral.!notice.international_languages'] = "Sebuah proyek terjemahan crowdsourced ada di translate.blesta.com. Anda dapat berkontribusi dan download terjemahan bahasa ada. Untuk menginstal, unzip isi file ke direktori instalasi Blesta Anda. Kemudian, refresh halaman ini, dan klik Install Link.";
$lang['AdminCompanyGeneral.international.confirm_uninstall'] = "Apakah Anda yakin ingin menghapus bahasa  %1\$s? Bahasa ini akan dihapus dan semua template email dalam bahasa ini akan dihapus secara permanen."; // %1$s is the name of the language
$lang['AdminCompanyGeneral.!notice.passphrase'] = "PERINGATAN: Menetapkan passphrase akan mencegah rekening pembayaran disimpan secara lokal dari yang otomatis diproses. Anda akan diminta secara manual untuk pembayaran batch dengan memasukkan passphrase Anda. Untuk informasi lebih lanjut mengenai fitur ini, silakan berkonsultasi panduan manual.";
?>