<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSystemCompanies.!success.company_added'] = "Perusahaan %1\$s berhasil dibuat"; // %1$s is the name of the company
$lang['AdminSystemCompanies.!success.company_edited'] = "Perusahaan %1\$s telah berhasil diperbarui!"; // %1$s is the name of the company
$lang['AdminSystemCompanies.index.categorylink_addcompany'] = "Tambahkan Perusahaan";
$lang['AdminSystemCompanies.index.text_options'] = "Pilihan";
$lang['AdminSystemCompanies.add.field_name'] = "Nama";
$lang['AdminSystemCompanies.add.field_phone'] = "Telepon";
$lang['AdminSystemCompanies.add.field_fax'] = "Fax";
$lang['AddSystemCompanies.add.field_companysubmit'] = "Buat Perusahaan";
$lang['AdminSystemCompanies.edit.boxtitle_editcompany'] = "Edit Perusahaan";
$lang['AdminSystemCompanies.edit.field_hostname'] = "Hostname";
$lang['AdminSystemCompanies.edit.field_phone'] = "Phone";
$lang['AdminSystemCompanies.edit.field_fax'] = "Fax";
$lang['AddSystemCompanies.edit.field_companysubmit'] = "Sunting Perusahaan";
$lang['AdminSystemCompanies.index.page_title'] = "Settings> System> perusahaan";
$lang['AdminSystemCompanies.index.text_hostname'] = "Hostname";
$lang['AdminSystemCompanies.add.page_title'] = "Settings> System> perusahaan> tambah Perusahaan";
$lang['AdminSystemCompanies.index.option_delete'] = "Hapus";
$lang['AdminSystemCompanies.!tooltip.hostname'] = "Hostname harus berisi hanya nama domain, TLD, dan nomor port opsional. Misalnya, 'domain.com' atau 'subdomain.domain.com:8080'.";
?>