<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSystemAutomation.!error.empty_cron_key'] = "Silakan set kunci cron.";
$lang['AdminSystemAutomation.index.boxtitle_automation'] = "Otomatisasi";
$lang['AdminSystemAutomation.index.heading_status'] = "Cron Status";
$lang['AdminSystemAutomation.index.field_cron_key'] = "Cron Key";
$lang['AdminSystemAutomation.index.text_update_key'] = "Pembaruan Cron Key";
$lang['AdminSystemAutomation.index.note_cron_command'] = "Pastikan untuk memperbarui perintah cron untuk menunjuk ke mana PHP diinstal jika hal itu berbeda dari apa yang ditampilkan.";
$lang['AdminSystemAutomation.index.page_title'] = "Settings> System> Otomasi
";
$lang['AdminSystemAutomation.index.text_cron_currently_running'] = "Cron sedang berjalan";
?>