<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminLogin.index.field_password'] = "Kata sandi";
$lang['AdminLogin.index.field_loginsubmit'] = "Masuk";
$lang['AdminLogin.index.link_resetpassword'] = "Reset Password saya";
$lang['AdminLogin.otp.link_login'] = "Batal, Masuk";
$lang['AdminLogin.reset.title_adminarea'] = "%1\$s | Reset Password"; // %1$s is the company name
$lang['AdminLogin.reset.link_login'] = "Batal, Log In";
$lang['AdminLogin.confirmreset.field_new_password'] = "kata sandi baru";
$lang['AdminLogin.confirmreset.link_login'] = "Batal, masuk";
$lang['AdminLogin.!error.unknown_user'] = "Username yang tidak diakui atau password tidak bisa di reset";
$lang['AdminLogin.confirmreset.page_title'] = "Konfirmasi Password Reset";
$lang['AdminLogin.setup.heading_create_account'] = "Buat akun Staf Anda";
$lang['AdminLogin.setup.field_last_name'] = "Nama Terakhir";
$lang['AdminLogin.setup.field_username'] = "Nama Pengguna";
$lang['AdminLogin.setup.field_confirm_password'] = "Konfirmasi Password";
$lang['AdminLogin.setup.field_enter_key_true'] = "Saya memiliki kunci lisensi untuk masuk";
$lang['AdminLogin.setup.field_enter_key_false'] = "Saya ingin memulai percobaan gratis 30 hari";
$lang['AdminLogin.reset.field_username'] = "Nama user";
?>