<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSystemApi.!success.key_added'] = "API Pengguna telah ditambahkan.";
$lang['AdminSystemApi.!success.key_updated'] = "API user berhasil diperbarui.";
$lang['AdminSystemApi.index.boxtitle_api'] = "API Access";
$lang['AdminSystemApi.index.heading_company'] = "Perusahaan";
$lang['AdminSystemApi.index.heading_options'] = "Pilihan";
$lang['AdminSystemApi.index.option_edit'] = "Edit";
$lang['AdminSystemApi.index.option_delete'] = "Hapus";
$lang['AdminSystemApi.index.no_results'] = "Tidak ada API pengguna";
$lang['AdminSystemApi.index.confirm_delete'] = "Benar-benar menghapus pengguna API ini?";
$lang['AdminSystemApi.add.boxtitle_add'] = "Tambah Pengguna API";
$lang['AdminSystemApi.add.field_company'] = "Perusahaan";
$lang['AdminSystemApi.add.field_notes'] = "Catatan";
$lang['AdminSystemApi.add.field_apisubmit'] = "Tambahkan Pengguna";
$lang['AdminSystemApi.edit.field_user'] = "User";
$lang['AdminSystemApi.edit.field_notes'] = "Catatan";
?>