<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSearch.!notice.results_truncated'] = "Jumlah hasil telah dipotong. Anda mungkin ingin mempersempit pencarian Anda";
$lang['AdminSearch.index.boxtitle_search'] = "Hasil pencarian untuk \"%1\$s\""; // %1$s is the criteria being searched for
$lang['AdminSearch.clients.heading_client_id'] = "ID Klien";
$lang['AdminSearch.clients.heading_group'] = "Kelompok";
$lang['AdminSearch.clients.heading_name'] = "nama";
$lang['AdminSearch.clients.heading_company'] = "Perusahaan";
$lang['AdminSearch.clients.heading_address'] = "Alamat";
$lang['AdminSearch.clients.no_results'] = "Tidak ada klien yang cocok dengan kriteria pencarian.";
$lang['AdminSearch.invoices.heading'] = "Faktur";
$lang['AdminSearch.invoice.heading_invoice'] = "Faktur #";
$lang['AdminSearch.invoice.heading_amount'] = "Pilihan";
$lang['AdminSearch.invoice.heading_paid'] = "Dibayar";
$lang['AdminSearch.invoice.heading_due'] = "Karena";
$lang['AdminSearch.invoice.heading_date_due'] = "Tanggal jatuh tempo";
$lang['AdminSearch.invoice.heading_sent'] = "Dikirim";
$lang['AdminSearch.invoice.heading_status'] = "Status";
$lang['AdminSearch.invoice.option_view'] = "Lihat";
$lang['AdminSearch.invoices.status_void'] = "Voided";
$lang['AdminSearch.invoices.status_draft'] = "Draft";
$lang['AdminSearch.invoices.status_unsent'] = "Belum terkirim";
$lang['AdminSearch.invoice.no_results'] = "Tidak ada faktur yang cocok dengan kriteria pencarian.";
$lang['AdminSearch.transactions.heading'] = "Transaksi";
$lang['AdminSearch.transactions.heading_client_id'] = "ID klien";
$lang['AdminSearch.transactions.heading_status'] = "Status";
$lang['AdminSearch.transactions.heading_options'] = "Pilihan";
$lang['AdminSearch.transactions.option_edit'] = "Edit";
$lang['AdminSearch.transactions.no_results'] = "Tidak ada transaksi yang cocok dengan kriteria pencarian.";
$lang['AdminSearch.packages.no_results'] = "Tidak ada paket yang cocok dengan kriteria pencarian.";
$lang['AdminSearch.services.heading'] = "Layanan";
$lang['AdminSearch.services.heading_date_added'] = "Tanggal Pembuatan";
?>