<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSystemGeneral.!success.basic_updated'] = "Pengaturan Dasar berhasil diperbarui!";
$lang['AdminSystemGeneral.!success.geoip_updated'] = "Pengaturan GeoIP berhasil diperbarui!";
$lang['AdminSystemGeneral.!success.maintenance_updated'] = "Pengaturan Pemeliharaan berhasil diperbarui!";
$lang['AdminSystemGeneral.!success.license_updated'] = "Kode Lisensi anda elah berhasil di update!";
$lang['AdminSystemGeneral.!success.addtype_created'] = "Jenis pembayaran \"%1\$s\" telah berhasil dibuat!"; // %1$s is the name of the payment type
$lang['AdminSystemGeneral.!success.edittype_updated'] = "Jenis pembayaran  \"%1\$s\" telah berhasil diperbarui!"; // %1$s is the name of the payment type
$lang['AdminSystemGeneral.!success.deletetype_deleted'] = "The jenis pembayaran \"%1\$s\" telah terhapus dengan sukses!"; // %1$s is the name of the payment type
$lang['AdminSystemGeneral.basic.boxtitle_basic'] = "Dasar Pengaturan";
$lang['AdminSystemGeneral.basic.field_basicsubmit'] = "Pembaruan Pengaturan";
$lang['AdminSystemGeneral.basic.text_unwritable'] = "Tidak bisa ditulisi";
$lang['AdminSystemGeneral.basic.text_day'] = "Hari";
$lang['AdminSystemGeneral.basic.text_days'] = "Hari";
$lang['AdminSystemGeneral.geoip.text_setup'] = "GeoIP dapat diaktifkan di sini, memberikan fungsi layanan lokasi GeoIP untuk Blesta. Mengaktifkan itu akan memungkinkan fitur tertentu untuk mengambil manfaat dari layanan lokasi.";
$lang['AdminSystemGeneral.geoip.text_database_exists'] = "%1\$s ada."; // %1$s is a file system path to the GeoIP database file
$lang['AdminSystemGeneral.geoip.text_database_not_exists'] = "%1\$s tidak ada."; // %1$s is a file system path to the GeoIP database file
$lang['AdminSystemGeneral.geoip.field_geoip_enabled'] = "Aktifkan GeoIP";
$lang['AdminSystemGeneral.geoip.field_geoipsubmit'] = "Pembaruan Pengaturan";
$lang['AdminSystemGeneral.maintenance.boxtitle_maintenance'] = "Pemeliharaan";
$lang['AdminSystemGeneral.maintenance.field_maintenancemode'] = "Aktifkan Maintenance Mode";
$lang['AdminSystemGeneral.maintenance.field_maintenancereason'] = "Alasan Pemeliharaan";
$lang['AdminSystemGeneral.maintenance.field_maintenancesubmit'] = "Pengaturan pembaruan";
$lang['AdminSystemGeneral.license.field_license'] = "License Key";
$lang['AdminSystemGeneral.paymenttypes.categorylink_addtype'] = "Buat Jenis Pembayaran";
$lang['AdminSystemGeneral.paymenttypes.boxtitle_types'] = "Jenis Pembayaran";
$lang['AdminSystemGeneral.paymenttypes.heading_is_lang'] = "Gunakan Definisi Bahasa";
$lang['AdminSystemGeneral.paymenttypes.option_edit'] = "Edit";
$lang['AdminSystemGeneral.paymenttypes.option_delete'] = "Hapus";
$lang['AdminSystemGeneral.paymenttypes.text_yes'] = "Ya";
$lang['AdminSystemGeneral.paymenttypes.text_no'] = "Tidak";
$lang['AdminSystemGeneral.addtype.boxtitle_addtype'] = "Buat Jenis Pembayaran";
$lang['AdminSystemGeneral.edittype.boxtitle_edittype'] = "Sunting Jenis Pembayaran";
$lang['AdminSystemGeneral.edittype.field_name'] = "Nama";
$lang['AdminSystemGeneral.maintenance.page_title'] = "Settings> System> General> Pemeliharaan";
$lang['AdminSystemGeneral.license.page_title'] = "Pengaturan > Sistem>  Umum > License Key";
$lang['AdminSystemGeneral.paymenttypes.page_title'] = "Pengaturan > Sistem> Umum > Jenis Pembayaran";
$lang['AdminSystemGeneral.addtype.page_title'] = "Pengaturan > System> General/Umum > Buat Jenis Pembayaran";
$lang['AdminSystemGeneral.basic.text_no_log'] = "Tidak pernah memutar Log";
$lang['AdminSystemGeneral.!paymenttypes.is_lang'] = "Hanya centang kotak ini jika Anda telah menambahkan definisi bahasa untuk jenis pembayaran ini dalam file bahasa kustom.";
$lang['AdminSystemGeneral.!error.geoip_mbstring_required'] = "mbstring extension diperlukan untuk fitur ini.";
?>