<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminPackageOptions.!success.option_deleted'] = "Pilihan paket telah berhasil dihapus.";
$lang['AdminPackageOptions.index.boxtitle_options'] = "Pilihan bisa dikonfigurasi";
$lang['AdminPackageOptions.index.category_groups'] = "Grup";
$lang['AdminPackageOptions.index.categorylink_creategroup'] = "Buat Grup";
$lang['AdminPackageOptions.index.heading_name'] = "Nama";
$lang['AdminPackageOptions.index.option_delete'] = "Hapus";
$lang['AdminPackageOptions.index.confirm_delete_group'] = "Apakah anda yakin ingin menghapus pilihan paket grup?";
$lang['AdminPackageOptions.index.confirm_delete_option'] = "Apakah Anda yakin ingin menghapus opsi paket ini?";
$lang['AdminPackageOptions.index.no_results_options'] = "Tidak ada pilihan konfigurasi.";
$lang['AdminPackageOptions.groupinfo.option_edit'] = "Edit";
$lang['AdminPackageOptions.groupinfo.option_remove'] = "Hapus dari Grup";
$lang['AdminPackageOptions.optioninfo.heading_options'] = "Nilai opsi";
$lang['AdminPackageOptions.optioninfo.heading_name'] = "Nama";
$lang['AdminPackageOptions.optioninfo.heading_value'] = "Nilai";
$lang['AdminPackageOptions.optioninfo.heading_min'] = "Min";
$lang['AdminPackageOptions.optioninfo.heading_max'] = "Max";
$lang['AdminPackageOptions.optioninfo.heading_step'] = "Langkah";
$lang['AdminPackageOptions.optioninfo.no_results'] = "Tidak ada nilai yang dipilih untuk pengaturan ini";
$lang['AdminPackageOptions.!tooltip.name'] = "Ini adalah nama form, dan tidak ditampilkan di mana saja. Modul mungkin menginginkan nama ini menjadi sesuatu yang spesifik, jika digunakan untuk provisioning/persediaan.";
$lang['AdminPackageOptions.!tooltip.type'] = "Jenis bentuk bidang yang harus ditampilkan.";
$lang['AdminPackageOptions.!tooltip.option_name'] = "Ini adalah nama tampilan untuk pilihan ini.";
$lang['AdminPackageOptions.!tooltip.option_min'] = "Nilai minimum yang diperbolehkan.";
$lang['AdminPackageOptions.!tooltip.option_max'] = "Nilai maksimum yang diperbolehkan.";
$lang['AdminPackageOptions.!tooltip.option_pricing_term'] = "Hanya penetapan pilihan harga yang sesuai dengan syarat dan mata uang untuk paket yang dipilih akan ditampilkan pada setiap formulir pemesanan.";
$lang['AdminPackageOptions.!tooltip.package_membership'] = "Paket dapat ditugaskan baik untuk kelompok pilihan paket di sini, atau kelompok pilihan paket individual.";
$lang['AdminPackageOptions.add.heading_basic'] = "Dasar";
$lang['AdminPackageOptions.add.field_label'] = "Label";
$lang['AdminPackageOptions.add.field_name'] = "Nama";
$lang['AdminPackageOptions.add.categorylink_addoption'] = "Tambahkan Opsi tambahan";
$lang['AdminPackageOptions.add.text_name'] = "Nama";
$lang['AdminPackageOptions.add.text_value'] = "Nilai";
$lang['AdminPackageOptions.add.text_min'] = "Min";
$lang['AdminPackageOptions.add.text_max'] = "Max";
$lang['AdminPackageOptions.add.text_step'] = "Langkah";
$lang['AdminPackageOptions.add.text_options'] = "Pilihan";
$lang['AdminPackageOptions.add.heading_prices'] = "Harga";
$lang['AdminPackageOptions.add.price_currency'] = "Mata Uang";
$lang['AdminPackageOptions.add.price_price'] = "Harga";
$lang['AdminPackageOptions.add.price_setup'] = "Biaya Pengaturan";
$lang['AdminPackageOptions.add.price_delete'] = "Hapus";
$lang['AdminPackageOptions.add.text_membergroups'] = "Anggota Grup";
$lang['AdminPackageOptions.add.text_availablegroups'] = "Grup yang tersedia";
$lang['AdminPackageOptions.edit.page_title'] = "Pilihan pembaharuan paket";
$lang['AdminPackageOptions.edit.boxtitle_editoption'] = " Pembaruan pilihan Paket";
$lang['AdminPackageOptions.edit.field_label'] = "Label";
$lang['AdminPackageOptions.edit.heading_options'] = "Pilihan";
$lang['AdminPackageOptions.edit.categorylink_editoption'] = "Tambahkan Opsi tambahan";
$lang['AdminPackageOptions.edit.text_name'] = "Nama";
$lang['AdminPackageOptions.edit.text_min'] = "Min";
$lang['AdminPackageOptions.edit.text_max'] = "Max";
$lang['AdminPackageOptions.edit.text_delete'] = "Hapus";
$lang['AdminPackageOptions.edit.heading_prices'] = "Harga";
$lang['AdminPackageOptions.edit.price_setup'] = "Biaya Setup";
$lang['AdminPackageOptions.edit.price_options'] = "Pilihan";
$lang['AdminPackageOptions.edit.price_delete'] = "Hapus";
$lang['AdminPackageOptions.edit.text_availablegroups'] = "Grup yang tersedia";
$lang['AdminPackageOptions.addgroup.page_title'] = "Paket baru Opsi Group ";
$lang['AdminPackageOptions.addgroup.field_name'] = "Nama";
$lang['AdminPackageOptions.addgroup.field_description'] = "Deskripsi";
$lang['AdminPackageOptions.addgroup.heading_packages'] = "Paket Keanggotaan";
$lang['AdminPackageOptions.addgroup.text_memberpackages'] = "Paket member";
$lang['AdminPackageOptions.addgroup.text_availablepackages'] = "Paket yang tersedia";
$lang['AdminPackageOptions.addgroup.field_addgroupsubmit'] = "Buat Kelompok";
$lang['AdminPackageOptions.editgroup.page_title'] = "Perbarui Pilihan Paket pada Group";
$lang['AdminPackageOptions.editgroup.heading_packages'] = "Paket Keanggotaan";
$lang['AdminPackageOptions.editgroup.text_memberpackages'] = "Paket Anggota";
$lang['AdminPackageOptions.editgroup.text_availablepackages'] = "Paket yang tersedia";
$lang['AdminPackageOptions.editgroup.field_editgroupsubmit'] = "Perbaharui Grup";
$lang['AdminPackageOptions.add.field_editable'] = "Klien dapat Mengedit";
?>