<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminPackages.index.boxtitle_packages'] = "Paket";
$lang['AdminPackages.index.categorylink_createpackage'] = "Membuat Paket";
$lang['AdminPackages.index.heading_name'] = "Nama";
$lang['AdminPackages.index.heading_module'] = "Module";
$lang['AdminPackages.index.heading_options'] = "Pilihan";
$lang['AdminPackages.index.category_active'] = "Aktif";
$lang['AdminPackages.index.category_restricted'] = "Terbatas";
$lang['AdminPackages.index.category_inactive'] = "Non-aktif";
$lang['AdminPackages.index.option_edit'] = "Edit";
$lang['AdminPackages.add.boxtitle_newpackage'] = "Paket baru";
$lang['AdminPackages.add.heading_basic'] = "Dasar";
$lang['AdminPackages.add.heading_module'] = "Pilihan modul ";
$lang['AdminPackages.add.heading_pricing'] = "Harga";
$lang['AdminPackages.add.heading_email'] = "Welcome Email";
$lang['AdminPackages.add.field_module'] = "Modul";
$lang['AdminPackages.add.field_packagename'] = "Nama Paket";
$lang['AdminPackages.add.field_activation'] = "Aktivasi Instant";
$lang['AdminPackages.add.field_description'] = "Deskripsi";
$lang['AdminPackages.add.field_description_text'] = "Teks";
$lang['AdminPackages.add.field_description_html'] = "HTML";
$lang['AdminPackages.add.text_term'] = "Periode";
$lang['AdminPackages.add.text_currency'] = "Mata uang";
$lang['AdminPackages.add.text_setup'] = "Biaya Pengaturan";
$lang['AdminPackages.add.text_cancellation'] = "Biaya pembatalan";
$lang['AdminPackages.add.text_options'] = "Pilihan";
$lang['AdminPackages.add.text_remove'] = "Hapus";
$lang['AdminPackages.add.text_tags'] = "Tags:";
$lang['AdminPackages.add.text_membergroups'] = "Anggota Grup";
$lang['AdminPackages.add.text_availablegroups'] = "Grup yang tersedia";
$lang['AdminPackages.add.field_email'] = "E-mail Selamat Datang ";
$lang['AdminPackages.add.field_packagesubmit'] = "Buat Paket";
$lang['AdminPackages.add.categorylink_addprice'] = "Tambah Harga Tambahan";
$lang['AdminPackages.edit.field_module'] = "Modul";
$lang['AdminPackages.edit.field_packagename'] = "Nama paket";
$lang['AdminPackages.edit.field_term'] = "Periode";
$lang['AdminPackages.edit.field_setupfee'] = "Biaya Setup";
$lang['AdminPackages.edit.field_cancelfee'] = "Biaya Pembatalan";
$lang['AdminPackages.edit.field_email'] = "E-mail Selamat Datang";
$lang['AdminPackages.edit.field_packagesubmit'] = "Perbarui Paket";
$lang['AdminPackages.groups.categorylink_creategroup'] = "Membuat grup";
$lang['AdminPackages.groups.no_results'] = "Tidak ada grup paket.";
$lang['AdminPackages.addgroup.boxtitle_addgroup'] = "Paket Grup Baru";
$lang['AdminPackages.addgroup.field_name'] = "Nama";
$lang['AdminPackages.addgroup.text_parentgroups'] = "Grup Induk";
$lang['AdminPackages.addgroup.field_addgroupsubmit'] = "Buat Grup";
$lang['AdminPackages.!success.package_updated'] = "Paket telah berhasil di update";
$lang['AdminPackages.!success.package_deleted'] = "Paket itu berhasil dihapus.";
$lang['AdminPackages.index.page_title'] = "Paket";
$lang['AdminPackages.index.heading_qty'] = "Kuantitas";
$lang['AdminPackages.index.option_delete'] = "Hapus";
$lang['AdminPackages.index.qty_unlimited'] = "Unlimited";
$lang['AdminPackages.packagepricing.heading_term'] = "Periode";
$lang['AdminPackages.packagepricing.pricing_no_results'] = "Paket ini tidak memiliki rincian harga.";
$lang['AdminPackages.add.page_title'] = "Paket Baru";
$lang['AdminPackages.add.field_qty_unlimited'] = "Unlimited";
$lang['AdminPackages.add.field_taxable'] = "Kena Pajak";
$lang['AdminPackages.add.field_select_group_type'] = "Pilih dari Grup Tersedia";
$lang['AdminPackages.add.text_group_name'] = "Nama standar Paket Grup";
$lang['AdminPackages.edit.field_qty_unlimited'] = "Tak terbatas";
$lang['AdminPackages.edit.field_description_text'] = "Teks";
$lang['AdminPackages.edit.field_description_html'] = "HTML";
$lang['AdminPackages.edit.field_taxable'] = "Kena Pajak";
$lang['AdminPackages.edit.field_modulegroup_any'] = "Apa saja";
$lang['AdminPackages.edit.text_term'] = "Periode";
$lang['AdminPackages.edit.text_currency'] = "Mata uang";
$lang['AdminPackages.edit.text_price'] = "Harga";
$lang['AdminPackages.edit.text_cancellation'] = "Biaya Pembatalan";
$lang['AdminPackages.edit.text_remove'] = "hapus";
$lang['AdminPackages.edit.text_group'] = "Sebuah paket harus milik setidaknya satu kelompok untuk digunakan.";
$lang['AdminPackages.edit.text_membergroups'] = "Anggota Grup";
$lang['AdminPackages.edit.text_availablegroups'] = "Grup yang tersedia";
$lang['AdminPackages.edit.categorylink_addprice'] = "Tambahkan Harga Tambahan";
$lang['AdminPackages.groups.category_addon'] = "Tambahan";
$lang['AdminPackages.groups.boxtitle_packagegroups'] = "Paket Grup";
$lang['AdminPackages.addgroup.page_title'] = "Grup Paket Baru";
$lang['AdminPackages.editgroup.page_title'] = "Perbarui Group Paket";
$lang['AdminPackages.editgroup.field_type'] = "Jenis";
$lang['AdminPackages.editgroup.field_editgroupsubmit'] = "Perbarui Grup";
$lang['AdminPackages.!success.package_added'] = "Paket berhasil dibuat.";
$lang['AdminPackages.index.heading_package'] = "ID Paket";
$lang['AdminPackages.packagepricing.heading_pricing'] = "Harga";
$lang['AdminPackages.groups.heading_name'] = "Nama";
$lang['AdminPackages.groups.option_edit'] = "Edit";
$lang['AdminPackages.groups.heading_parent_groups'] = "Grup Utama";
$lang['AdminPackages.groups.heading_packages'] = "Paket Anggota";
$lang['AdminPackages.groups.heading_package_name'] = "Nama Paket";
$lang['AdminPackages.groups.packages_no_results'] = "Kelompok Paket tidak ditetapkan pada paket ini";
$lang['AdminPackages.groups.option_delete'] = "Hapus";
$lang['AdminPackages.add.field_configurable_options'] = "Pilihan dikonfigurasi";
$lang['AdminPackages.add.field_single_term'] = "Batalkan pada akhir masa";
$lang['AdminPackages.edit.field_configurable_options'] = "Pilihana bisa dikonfigurasi";
$lang['AdminPackages.edit.field_single_term'] = "Batal pada akhir masa";
$lang['AdminPackages.!tooltip.prorata'] = "Pro rata memungkinkan hari tertentu dari bulan yang akan ditetapkan untuk pembaharuan layanan dibuat dengan paket ini. hanya Periode bulanan dan tahunan akan dipengaruhi oleh pilihan ini.";
$lang['AdminPackages.!tooltip.prorata_day'] = "Hari dan bulan layanan ini akan ditetapkan, untuk memperbarui saat order";
$lang['AdminPackages.add.field_prorata'] = "Aktifkan Pro rata";
$lang['AdminPackages.add.field_prorata_day'] = "Hari Pro rata";
$lang['AdminPackages.add.text_none'] = "Tak satupun";
$lang['AdminPackages.edit.field_prorata'] = "Aktifkan Pro rata";
$lang['AdminPackages.edit.field_prorata_day'] = "Pro rata Day";
$lang['AdminPackages.edit.text_none'] = "Tak satupun";
$lang['AdminPackages.addgroup.field_description'] = "Deskripsi";
$lang['AdminPackages.editgroup.field_description'] = "Deskripsi";
?>