<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyPlugins.!success.upgraded'] = "Plugin berhasil ditingkatkan.";
$lang['AdminCompanyPlugins.available.btn_install'] = "Install";
$lang['AdminCompanyPlugins.installed.text_author'] = "Penulis:";
$lang['AdminCompanyPlugins.installed.confirm_uninstall'] = "Benar-benar uninstall plugin ini?";
$lang['AdminCompanyPlugins.installed.btn_manage'] = "Kelola";
$lang['AdminCompanyPlugins.installed.text_none'] = "Tidak ada plugin diinstal.";
$lang['AdminCompanyPlugins.installed.page_title'] = "Pengaturan > Perusahaan > Plugin > Terpasang";
$lang['AdminCompanyPlugins.available.text_version'] = "(ver %1\$s)"; // %1$s is the version number of the plugin
$lang['AdminCompanyPlugins.!success.enabled'] = "Plugin berhasil diaktifkan.";
$lang['AdminCompanyPlugins.installed.confirm_disable'] = "Benar-benar menonaktifkan plugin ini?";
$lang['AdminCompanyPlugins.installed.btn_enable'] = "Enable";
$lang['AdminCompanyPlugins.!tab.installed'] = "Dipasang";
?>