<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSystemBackup.!success.backup_updated'] = "Pengaturan Backup berhasil diperbarui!";
$lang['AdminSystemBackup.!success.backup_uploaded'] = "Backup tersebut berhasil dikirim ke layanan remote yang dikonfigurasi !";
$lang['AdminSystemBackup.ftp.boxtitle_backup'] = "Secure FTP";
$lang['AdminSystemBackup.ftp.field_port'] = "Port";
$lang['AdminSystemBackup.ftp.field_username'] = "Nama Pengguna";
$lang['AdminSystemBackup.ftp.field_password'] = "Kata sandi";
$lang['AdminSystemBackup.ftp.field_rate'] = "Backup Setiap";
$lang['AdminSystemBackup.ftp.page_title'] = "Pengaturan > Sistem> Backup>  SFTP";
$lang['AdminSystemBackup.amazon.field_accesskey'] = "Akses Key";
$lang['AdminSystemBackup.amazon.field_secretkey'] = "Secret Key";
$lang['AdminSystemBackup.amazon.field_rate'] = "Backup Setiap";
$lang['AdminSystemBackup.amazon.field_backupsubmit'] = "Pembaruan Pengaturan";
$lang['AdminSystemBackup.index.page_title'] = "Settings > System > Backup > On Demand";
$lang['AdminSystemBackup.amazon.field_region'] = "Wilayah";
?>