<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMain.index.customize_dashboard'] = "Sesuaikan Dashboard";
$lang['AdminMain.!error.delete_event.staff_id'] = "Hanya pembuat acara yang dapat menghapus acara ini.";
$lang['AdminMain.!error.event_editable'] = "Hanya pembuat acara memungkinlan menghapus acara itu.";
$lang['AdminMain.!success.event_added'] = "Acara ini telah berhasil ditambahkan!";
$lang['AdminMain.index.page_title'] = "Dasbor";
$lang['AdminMain.calendar.page_title'] = "Kalender";
$lang['AdminMain.calendar.boxtitle_calendar'] = "Kalender";
$lang['AdminMain.calendar.category_month'] = "Bulan";
$lang['AdminMain.calendar.category_week'] = "Minggu";
$lang['AdminMain.addevent.boxtitle_addevent'] = "Buat Acara";
$lang['AdminMain.addevent.field_title'] = "Judul";
$lang['AdminMain.addevent.field_end_date'] = "Tanggal Akhir";
$lang['AdminMain.addevent.field_shared'] = "Buat acara ini bisa dilihat oleh staf lain";
$lang['AdminMain.addevent.field_addeventsubmit'] = "Buat Acara";
$lang['AdminMain.editevent.boxtitle_editevent'] = "edit Acara";
$lang['AdminMain.editevent.field_title'] = "Judul";
$lang['AdminMain.editevent.field_start_date'] = "tanggal Mulai ";
$lang['AdminMain.editevent.field_end_date'] = "Tanggal akhir";
$lang['AdminMain.editevent.field_shared'] = "Buat acara ini supaya dapat dilihat oleh staf lainnya";
?>