<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSystemHelp.index.heading_user_manual'] = "User Manual";
$lang['AdminSystemHelp.index.text_user_manual'] = "Ingin tahu bagaimana untuk mengkonfigurasi Blesta, atau mengambil keuntungan dari beberapa fitur yang lebih canggih? Periksa manual user.";
$lang['AdminSystemHelp.index.text_dev_manual'] = "Disesuaikan dengan kebutuhan pengembang, manual pengembang berisi segala sesuatu yang perlu diketahui tentang pengembangan untuk platform Blesta.";
$lang['AdminSystemHelp.index.heading_forums'] = "Forum Komunitas";
$lang['AdminSystemHelp.index.page_title'] = "Pengaturan> System> Bantuan> Sumber Daya";
?>