<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminTools.getlognames.text_email'] = "Email";
$lang['AdminTools.getlognames.text_users'] = "Login pengguna";
$lang['AdminTools.getlognames.text_contacts'] = "Kontak";
$lang['AdminTools.getlognames.text_accountaccess'] = "Akses akun";
$lang['AdminTools.convertcurrency.boxtitle_currency'] = "Konversi Mata Uang";
$lang['AdminTools.convertcurrency.field_amount'] = "Jumlah";
$lang['AdminTools.convertcurrency.field_from'] = "Dari";
$lang['AdminTools.logmodule.text_staffname'] = "Staf";
$lang['AdminTools.logmodule.text_date'] = "Tanggal";
$lang['AdminTools.moduleloglist.text_direction'] = "Arah";
$lang['AdminTools.moduleloglist.text_data'] = "Data";
$lang['AdminTools.moduleloglist.text_date'] = "Tanggal";
$lang['AdminTools.moduleloglist.text_status'] = "Status";
$lang['AdminTools.moduleloglist.text_input'] = "Masukan";
$lang['AdminTools.moduleloglist.text_error'] = "Error";
$lang['AdminTools.moduleloglist.text_success'] = "Sukses";
$lang['AdminTools.moduleloglist.no_results'] = "Tidak ada data log untuk modul ini.";
$lang['AdminTools.loggateway.text_name'] = "Nama";
$lang['AdminTools.loggateway.text_staffname'] = "Staf";
$lang['AdminTools.gatewayloglist.text_direction'] = "arah";
$lang['AdminTools.gatewayloglist.text_date'] = "Tanggal";
$lang['AdminTools.gatewayloglist.text_input'] = "Masukan";
$lang['AdminTools.gatewayloglist.text_output'] = "Keluaran";
$lang['AdminTools.logemail.text_summary'] = "Ringkasan";
$lang['AdminTools.logemail.text_to'] = "Untuk";
$lang['AdminTools.logemail.text_from'] = "Dari";
$lang['AdminTools.logemail.text_sent'] = "Dikirim";
$lang['AdminTools.logemail.text_unsent'] = "Tidak terkirim";
$lang['AdminTools.logusers.text_username'] = "Nama Pengguna";
$lang['AdminTools.logusers.text_type'] = "Jenis";
$lang['AdminTools.logusers.text_ipaddress'] = "Alamat IP";
$lang['AdminTools.logusers.text_date'] = "Tanggal";
$lang['AdminTools.logusers.text_staff'] = "Staff";
$lang['AdminTools.logusers.text_client'] = "Klien";
$lang['AdminTools.logusers.no_results'] = "tidak ada log user yang login";
$lang['AdminTools.logaccountaccess.name'] = "Staf";
$lang['AdminTools.logaccountaccess.text_cc'] = "Kartu kredit";
$lang['AdminTools.logaccountaccess.text_ach'] = "ACH";
$lang['AdminTools.accountaccess.name'] = "Nama";
$lang['AdminTools.accountaccess.type'] = "Jenis";
$lang['AdminTools.accountaccess.type_cc'] = "%1\$s - %2\$s"; // %1$s is the account type (Credit Card) and %2$s is the type of account (MasterCard, Visa, etc.)
$lang['AdminTools.accountaccess.no_results'] = "Tidak ada rincian akun untuk catatan ini.";
$lang['AdminTools.logcron.start_date'] = "Tanggal Mulai ";
$lang['AdminTools.logcron.output'] = "Hasil";
$lang['AdminTools.logcron.no_output'] = "Ada output yang tercatat untuk log ini.";
$lang['AdminTools.logcron.no_results'] = "Tidak ada log cron.";
$lang['AdminTools.getlognames.text_transactions'] = "Transaksi";
$lang['AdminTools.convertcurrency.page_title'] = "Alat Konversi Mata Uang";
$lang['AdminTools.logs.page_title'] = "Alat Log";
$lang['AdminTools.logmodule.page_title'] = "Alat Log";
$lang['AdminTools.logemail.page_title'] = "Alat Log";
$lang['AdminTools.logcontacts.text_name'] = "Nama";
$lang['AdminTools.logcontacts.text_date'] = "Tanggal";
$lang['AdminTools.logcontacts.text_previous'] = "Nilai Sebelumnya";
$lang['AdminTools.logtransactions.page_title'] = "Alat Log";
$lang['AdminTools.logtransactions.text_new'] = "Nilai baru";
$lang['AdminTools.logtransactions.no_results'] = "Tidak ada log transaksi";
$lang['AdminTools.logaccountaccess.page_title'] = "Alat Log";
$lang['AdminTools.loginvoicedelivery.invoice_id_code'] = "Faktur #";
$lang['AdminTools.loginvoicedelivery.no_results'] = "Tidak ada log pengiriman faktur.";
$lang['AdminTools.logusers.text_location'] = "Tempat";
?>