<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyGroups.!success.edit_updated'] = "%1\$s telah berhasil diedit!"; // %1$s is the name of the client group
$lang['AdminCompanyGroups.index.boxtitle_groups'] = "Grup klien";
$lang['AdminCompanyGroups.index.categorylink_addgroup'] = "Buat Grup";
$lang['AdminCompanyGroups.index.text_name'] = "Nama";
$lang['AdminCompanyGroups.index.text_description'] = "Deskripsi";
$lang['AdminCompanyGroups.index.text_clients'] = "Jumlah Klien";
$lang['AdminCompanyGroups.index.text_options'] = "Pilihan";
$lang['AdminCompanyGroups.index.option_edit'] = "Mengedit";
$lang['AdminCompanyGroups.index.option_delete'] = "Hapus";
$lang['AdminCompanyGroups.index.no_results'] = "Tidak ada kelompok klien.";
$lang['AdminCompanyGroups.add.boxtitle_addgroup'] = "Buat Grup";
$lang['AdminCompanyGroups.add.heading_payment'] = "Pemberitahuan pembayaran jatuh tempo";
$lang['AdminCompanyGroups.add.field_color'] = "Warna";
$lang['AdminCompanyGroups.add.text_addsubmit'] = "Buat Kelompok";
$lang['AdminCompanyGroups.edit.heading_payment'] = "Pemberitahuan Pembayaran Jatuh Tempo";
$lang['AdminCompanyGroups.edit.field_description'] = "Deskripsi";
$lang['AdminCompanyGroups.edit.field_delivery_methods'] = "Metode Pengiriman Faktur";
$lang['AdminCompanyGroups.edit.field_company_settings'] = "Gunakan Pengaturan Perusahaan  (jangan centang untuk menentukan bawah)";
$lang['AdminCompanyGroups.edit.text_editsubmit'] = "Mengedit Grup";
$lang['AdminCompanyGroups.index.page_title'] = "Pengaturan> Perusahaan> Grup Klien";
$lang['AdminCompanyGroups.add.page_title'] = "Pengaturan> Perusahaan> Grup klien> Buat Grup";
$lang['AdminCompanyGroups.edit.page_title'] = "Pengaturan> Perusahaan> Grup Client> Edit Grup";
?>