<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyAutomation.index.boxtitle_automation'] = "Otomatisasi";
$lang['AdminCompanyAutomation.index.field_enabled'] = "Diaktifkan";
$lang['AdminCompanyAutomation.index.text_interval'] = "Selang";
$lang['AdminCompanyAutomation.index.text_starttime'] = "Waktu mulai";
$lang['AdminCompanyAutomation.index.no_results'] = "Tidak ada tugas cron.";
$lang['AdminCompanyAutomation.index.no_cron_lastran'] = "Tak pernah";
$lang['AdminCompanyAutomation.index.text_cron_last_ran'] = "Cron terakhir berlari pada %1\$s."; // %1$s is the date that the cron last ran
$lang['AdminCompanyAutomation.getintervals.text_hour'] = "jam";
?>