<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyThemes.!error.import_file.theme_type_client'] = "Tema yang diimpor bukan tema untuk antarmuka klien.";
$lang['AdminCompanyThemes.!success.themes_updated'] = "Tema telah berhasil diperbarui.";
$lang['AdminCompanyThemes.index.page_title'] = "Pengaturan> Perusahaan> Tampilan dan Nuansa> Tema";
$lang['AdminCompanyThemes.index.option_export'] = "Export";
$lang['AdminCompanyThemes.index.no_results'] = "Tidak ada tema jenis ini.";
$lang['AdminCompanyThemes.!theme.tooltip_theme_navigation_background_color'] = "Mengatur warna latar belakang menu navigasi ini.";
$lang['AdminCompanyThemes.!theme.tooltip_theme_subnavigation_bg_color'] = "Atur header subnavigation gradien warna latar belakangnya";
$lang['AdminCompanyThemes.!theme.tooltip_theme_subnavigation_text_color'] = "Mengatur warna teks judul subnavigation.";
$lang['AdminCompanyThemes.!theme.tooltip_theme_widget_heading_bg_color'] = "Atur  gradien warna latar belakang.kotak widget";
$lang['AdminCompanyThemes.!theme.tooltip_theme_box_text_color'] = "Mengatur warna teks dalam Kotak widget";
$lang['AdminCompanyThemes.!theme.tooltip_theme_highlight_bg_color'] = "Atur warna highligh / sorot (oleh mouse) untuk halamaan dan baris tabel";
$lang['AdminCompanyThemes.!theme.tooltip_theme_page_title_text_color'] = "Mengatur warna teks judul halaman.";
$lang['AdminCompanyThemes.!theme.tooltip_theme_page_background_color'] = "Set warna background pada area konten";
$lang['AdminCompanyThemes.!theme.tooltip_theme_link_color'] = "Mengatur warna link.";
$lang['AdminCompanyThemes.!theme.tooltip_theme_link_settings_color'] = "Mengatur warna link dalam pengaturan bagian sidebar.";
$lang['AdminCompanyThemes.!theme.tooltip_theme_panel_header_background_color'] = "Mengatur gradien warna background header Halaman";
$lang['AdminCompanyThemes.!theme.tooltip_theme_panel_header_text_color'] = "Mengatur warna latar belakang header di halaman konten";
$lang['AdminCompanyThemes.!theme.tooltip_theme_highlight_hover_color'] = "Mengatur sorot (mouse-over) warna berbagai bagian.";
$lang['AdminCompanyThemes.add.page_title'] = "Pengaturan> Perusahaan> Tampilan dan Nuansa> Tema Baru";
$lang['AdminCompanyThemes.add.boxtitle_addtheme'] = "Tema baru";
$lang['AdminCompanyThemes.add.heading_import'] = "Impor Tema";
$lang['AdminCompanyThemes.add.add_type_import'] = "Impor tema";
$lang['AdminCompanyThemes.add.field_import_file'] = "Impor Berkas Tema";
$lang['AdminCompanyThemes.add.field_addthemesubmit'] = "Buat Tema";
$lang['AdminCompanyThemes.add.field_theme_navigation_background_color'] = "Warna Latar Belakang Navigasi";
$lang['AdminCompanyThemes.add.field_theme_widget_icon_heading_bg_color'] = "Warna Background Icon Kotak Heading Widget";
$lang['AdminCompanyThemes.add.field_theme_text_shadow'] = "Warna Bayangan Teks";
$lang['AdminCompanyThemes.add.field_theme_actions_text_color'] = "Warna teks link";
$lang['AdminCompanyThemes.add.field_theme_highlight_bg_color'] = "Highlight Warna Latar Belakang";
$lang['AdminCompanyThemes.add.field_theme_navigation_text_color'] = "Warna Teks Navigasi ";
$lang['AdminCompanyThemes.add.field_logo_url'] = "Logo Header";
$lang['AdminCompanyThemes.add.field_theme_page_title_background_color'] = "Latar Belakang Warna Judul Halaman";
$lang['AdminCompanyThemes.add.field_theme_page_title_text_color'] = "Warna Teks Judul Halaman";
$lang['AdminCompanyThemes.add.field_theme_page_background_color'] = "Warbna Background Halaman";
$lang['AdminCompanyThemes.add.field_theme_link_color'] = "Warna teks link";
$lang['AdminCompanyThemes.add.field_theme_panel_header_background_color'] = "Warna Latar Belakang header Halaman Konten ";
$lang['AdminCompanyThemes.add.field_theme_panel_header_text_color'] = "Warna Teks header Halaman Konten ";
$lang['AdminCompanyThemes.add.field_theme_highlight_hover_color'] = "Sorot/Highlight Warna Background";
$lang['AdminCompanyThemes.edit.boxtitle_edittheme'] = "Ubah Tema";
$lang['AdminCompanyThemes.edit.field_name'] = "Nama";
$lang['AdminCompanyThemes.edit.field_editthemesubmit'] = "Perbarui Tema";
$lang['AdminCompanyThemes.edit.field_theme_header_text_color'] = "Warna teks header";
$lang['AdminCompanyThemes.edit.field_theme_navigation_text_hover_color'] = "Warna hover teks navigasi";
$lang['AdminCompanyThemes.edit.field_theme_subnavigation_text_color'] = "Warna Teks Subnavigasi";
$lang['AdminCompanyThemes.edit.field_theme_subnavigation_text_active_color'] = "Subnavigation Warna Teks Aktif";
$lang['AdminCompanyThemes.edit.field_theme_widget_heading_bg_color'] = "Warna Latar Belakang Kotak Widget";
$lang['AdminCompanyThemes.edit.field_theme_box_text_color'] = "Warna Kotak teks ";
$lang['AdminCompanyThemes.edit.field_theme_text_shadow'] = "Warna Bayangan Teks";
$lang['AdminCompanyThemes.edit.field_theme_actions_text_color'] = "Warna teks link";
$lang['AdminCompanyThemes.edit.field_theme_highlight_bg_color'] = "Sorot / Highlight Warna Latar Belakang";
$lang['AdminCompanyThemes.edit.field_theme_navigation_text_color'] = "Warna Teks Navigasi";
$lang['AdminCompanyThemes.edit.field_theme_page_title_background_color'] = "Warna Belakang Judul Halaman";
$lang['AdminCompanyThemes.edit.field_theme_page_title_text_color'] = "Warna Teks Judul  Halaman ";
$lang['AdminCompanyThemes.edit.field_theme_navigation_text_active_color'] = "Warna Teks Aktif Navigasi";
$lang['AdminCompanyThemes.edit.field_theme_page_background_color'] = "Warna Background Halaman";
$lang['AdminCompanyThemes.edit.field_theme_link_settings_color'] = "Pengaturan Warna Teks Tautan";
$lang['AdminCompanyThemes.edit.field_theme_panel_header_text_color'] = "Warna Teks Header Halaman Konten ";
?>