<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyLookandfeel.!success.template_updated'] = "Template Klien berhasil diperbarui.";
$lang['AdminCompanyLookandfeel.template.page_title'] = "Pengaturan> Perusahaan> Tampilan dan Nuansa> Template";
$lang['AdminCompanyLookandfeel.template.box_title'] = "Template";
$lang['AdminCompanyLookandfeel.template.text_submit'] = "Simpan";
?>