<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyGateways.!success.manage_updated'] = "Gateway telah berhasil diperbaharui";
$lang['AdminCompanyGateways.!success.upgraded'] = "Gateway berhasil ditingkatkan";
$lang['AdminCompanyGateways.available.heading_merchant'] = "Merchant";
$lang['AdminCompanyGateways.available.heading_nonmerchant'] = "Non-Merchant";
$lang['AdminCompanyGateways.available.text_supports'] = "Supports:";
$lang['AdminCompanyGateways.available.text_merchantachoffsite'] = "ACH offsite";
$lang['AdminCompanyGateways.available.text_merchantccoffsite'] = "Kartu Kredit offsite";
$lang['AdminCompanyGateways.installed.heading_merchant'] = "Merchant/Pedagang";
$lang['AdminCompanyGateways.installed.text_author_url'] = "URL Penulis";
$lang['AdminCompanyGateways.installed.text_supports'] = "Supports:";
$lang['AdminCompanyGateways.installed.text_merchantach'] = "ACH";
$lang['AdminCompanyGateways.installed.text_merchantachoffsite'] = "ACH offsite";
$lang['AdminCompanyGateways.installed.text_merchantccoffsite'] = "Kartu Kredit offsite";
$lang['AdminCompanyGateways.installed.text_nonmerchant_none'] = "Tidak ada gateway non-merchant.yang diinstal ";
$lang['AdminCompanyGateways.installed.btn_uninstall'] = "Uninstall";
$lang['AdminCompanyGateways.manage.heading_gateway'] = "Pilihan Gateway";
$lang['AdminCompanyGateways.manage.heading_currencies'] = "Mata Uang Yang Diterima";
$lang['AdminCompanyGateways.manage.text_addcurrency'] = "menambahkan mata uang";
$lang['AdminCompanyGateways.manage.update_settings'] = "Pembaruan Pengaturan ";
$lang['AdminCompanyGateways.available.page_title'] = "Pengaturan> Perusahaan> Gateways> Tersedia";
$lang['AdminCompanyGateways.available.signup_url'] = "Daftar";
$lang['AdminCompanyGateways.installed.page_title'] = "Pengaturan> Perusahaan> Gateway> Terpasang";
$lang['AdminCompanyGateways.manage.page_title'] = "Pengaturan> Perusahaan> Gateways> Kelola %1\$s"; // %1$s is the name of the gateway
$lang['AdminCompanyGateways.available.text_version'] = "(ver %1\$s)"; // %1$s is the version number of this gateway
$lang['AdminCompanyGateways.manage.text_in_use_by'] = "digunakan oleh";
?>