<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminReportsCustomize.!success.added'] = "Laporan ini telah ditambahkan.";
$lang['AdminReportsCustomize.!success.deleted'] = "Laporan berhasil dihapus.";
$lang['AdminReportsCustomize.index.page_title'] = "Laporan penagihan";
$lang['AdminReportsCustomize.index.table_created'] = "Tanggal telah dibuat";
$lang['AdminReportsCustomize.index.table_option_delete'] = "Hapus";
$lang['AdminReportsCustomize.index.no_custom_reports'] = "Tidak ada laporan kustom";
$lang['AdminReportsCustomize.add.field_name'] = "Nama";
$lang['AdminReportsCustomize.add.heading_fields'] = "Bidang";
$lang['AdminReportsCustomize.add.table_label'] = "Label";
$lang['AdminReportsCustomize.add.field_regex'] = "Kustom Regex";
$lang['AdminReportsCustomize.edit.field_query'] = "Pertanyaan/Query";
$lang['AdminReportsCustomize.edit.table_options'] = "Pilihan";
?>