<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminBilling.invoices.boxtitle_invoices'] = "Faktur";
$lang['AdminBilling.invoices.heading_invoice'] = "Faktur #";
$lang['AdminBilling.invoices.heading_recurinvoice'] = "Berulang #";
$lang['AdminBilling.invoices.heading_client'] = "Klien #";
$lang['AdminBilling.invoices.heading_amount'] = "Jumlah";
$lang['AdminBilling.invoices.heading_paid'] = "Dibayar";
$lang['AdminBilling.invoices.heading_due'] = "Karena";
$lang['AdminBilling.invoices.heading_dateclosed'] = "Tanggal Ditutup";
$lang['AdminBilling.invoices.heading_datebilled'] = "Tanggal Ditagih";
$lang['AdminBilling.invoices.heading_datedue'] = "Tanggal jatuh tempo";
$lang['AdminBilling.invoices.heading_options'] = "Pilihan";
$lang['AdminBilling.invoices.heading_term'] = "Istilah";
$lang['AdminBilling.invoices.heading_duration'] = "Lamanya";
$lang['AdminBilling.invoices.heading_count'] = "Menghitung";
$lang['AdminBilling.invoices.category_open'] = "Terbuka";
$lang['AdminBilling.invoices.category_drafts'] = "Konsep";
$lang['AdminBilling.invoices.category_closed'] = "Tertutup";
$lang['AdminBilling.invoices.category_voided'] = "Voided";
$lang['AdminBilling.invoices.category_pastdue'] = "Past Due";
$lang['AdminBilling.invoices.category_recurring'] = "Berulang";
$lang['AdminBilling.invoices.option_edit'] = "Sunting";
$lang['AdminBilling.invoices.option_view'] = "Lihat";
$lang['AdminBilling.invoices.option_pay'] = "Membayar";
$lang['AdminBilling.invoices.subtotal_w_tax'] = "var1} +pajak"; // %1$s is the sub total amount
$lang['AdminBilling.invoices.term_day'] = "%1\$s hari"; // %1$s is the term (an integer)
$lang['AdminBilling.invoices.term_week'] = "%1\$s minggu"; // %1$s is the term (an integer)
$lang['AdminBilling.invoices.term_month'] = "%1\$s Bulan"; // %1$s is the term (an integer)
$lang['AdminBilling.invoices.term_year'] = "%1\$s tahun"; // %1$s is the term (an integer)
$lang['AdminBilling.invoices.term_day_plural'] = "%1\$s hari"; // %1$s is the term (an integer)
$lang['AdminBilling.invoices.term_week_plural'] = "%1\$s minggu"; // %1$s is the term (an integer)
$lang['AdminBilling.invoices.term_month_plural'] = "%1\$s bulan"; // %1$s is the term (an integer)
$lang['AdminBilling.invoices.term_year_plural'] = "%1\$s tahun"; // %1$s is the term (an integer)
$lang['AdminBilling.invoices.duration_finite'] = "%1\$s kali"; // %1$s is the number of times the recurring invoice will be created
$lang['AdminBilling.invoices.no_results'] = "Tidak ada faktur dengan status ini.";
$lang['AdminBilling.services.boxtitle_services'] = "Layanan";
$lang['AdminBilling.services.heading_term'] = "Istilah";
$lang['AdminBilling.services.heading_dateadded'] = "Tanggal Ditambahkan";
$lang['AdminBilling.services.heading_daterenews'] = "Tanggal Memperbarui";
$lang['AdminBilling.services.heading_datesuspended'] = "Tanggal tersuspend";
$lang['AdminBilling.invoices.category_pending'] = "Tertunda";
$lang['AdminBilling.transactions.boxtitle_transactions'] = "Transaksi";
$lang['AdminBilling.transactions.heading_client'] = "Klien #";
$lang['AdminBilling.transactions.heading_type'] = "Jenis";
$lang['AdminBilling.transactions.heading_amount'] = "Jumlah";
$lang['AdminBilling.transactions.heading_credit'] = "Dikreditkan";
$lang['AdminBilling.transactions.heading_applied'] = "Terapan";
$lang['AdminBilling.transactions.heading_number'] = "Nomor";
$lang['AdminBilling.transactions.heading_date'] = "Tanggal";
$lang['AdminBilling.transactions.heading_options'] = "Pilihan";
$lang['AdminBilling.transactions.category_approved'] = "Disetujui";
$lang['AdminBilling.transactions.category_declined'] = "Ditolak";
$lang['AdminBilling.transactions.category_voided'] = "Dibatalkan";
$lang['AdminBilling.transactions.category_error'] = "Error";
$lang['AdminBilling.transactions.category_pending'] = "Tertunda";
$lang['AdminBilling.transactions.category_refunded'] = "Dikembalikan";
$lang['AdminBilling.transactions.category_returned'] = "Kembali";
$lang['AdminBilling.transactions.option_edit'] = "Sunting";
$lang['AdminBilling.transactions.no_results'] = "Tidak ada transaksi dengan status ini.";
$lang['AdminBilling.transactions.headingexpand_invoice'] = "Faktur";
$lang['AdminBilling.transactions.headingexpand_amount'] = "Jumlah";
$lang['AdminBilling.transactions.headingexpand_appliedon'] = "Terapan di";
$lang['AdminBilling.transactions.applied_no_results'] = "Transaksi ini belum diterapkan untuk setiap faktur.";
$lang['AdminBilling.invoices.headingexpand_paymenttype'] = "Jenis Pembayaran";
$lang['AdminBilling.invoices.headingexpand_amount'] = "Jumlah";
$lang['AdminBilling.invoices.headingexpand_applied'] = "Terapan";
$lang['AdminBilling.invoices.headingexpand_appliedon'] = "Terapan On / Applied On";
$lang['AdminBilling.invoices.headingexpand_options'] = "Pilihan";
$lang['AdminBilling.invoices.applied_no_results'] = "Faktur ini tidak memiliki transaksi untuk diterapkan";
$lang['AdminBilling.invoices.text_edit'] = "Sunting";
$lang['AdminBilling.!success.invoices_marked_printed'] = "Faktur terpilih telah ditandai untuk dicetak.";
$lang['AdminBilling.!error.no_invoices_selected'] = "Tidak ada faktur ini dipilih.";
$lang['AdminBilling.index.open_parethesis'] = "(";
$lang['AdminBilling.index.closed_parethesis'] = ")";
$lang['AdminBilling.index.page_title'] = "Ikhtisar penagihan";
$lang['AdminBilling.index.manage_widgets'] = "Mengelola Widget";
$lang['AdminBilling.index.customize_dashboard'] = "Sesuaikan Ikhtisar";
$lang['AdminBilling.index.heading_actions'] = "Aksi Item";
$lang['AdminBilling.index.no_actions'] = "Tidak ada item tindakan tertunda.";
$lang['AdminBilling.index.action_printqueue'] = "Item Pending Cetak";
$lang['AdminBilling.index.action_batch'] = "Item Pending Batch";
$lang['AdminBilling.updatedashboard.text_layout'] = "Pilih layout bawah untuk menyesuaikan gambaran penagihan.";
$lang['AdminBilling.managewidgets.text_widgets'] = "Tarik widget dari kanan ke kiri untuk menambahkannya ke ikhtisar penagihan, atau dari kiri ke kanan untuk menghapusnya.";
$lang['AdminBilling.managewidgets.text_version'] = "ver %1\$s"; // %1$s is the version number of the plugin
$lang['AdminBilling.managewidgets.text_author'] = "Penulis:";
$lang['AdminBilling.invoices.page_title'] = "Faktur Penagihan";
$lang['AdminBilling.services.page_title'] = "Penagihan Jasa";
$lang['AdminBilling.services.heading_package'] = "Paket";
$lang['AdminBilling.services.heading_label'] = "Label";
$lang['AdminBilling.services.heading_datecanceled'] = "Tanggal Dibatalkan";
$lang['AdminBilling.services.category_active'] = "Aktif";
$lang['AdminBilling.services.category_canceled'] = "Dibatalkan";
$lang['AdminBilling.services.category_suspended'] = "Tersuspend";
$lang['AdminBilling.services.category_pending'] = "Tertunda";
$lang['AdminBilling.services.text_never'] = "Tak pernah";
$lang['AdminBilling.services.no_results'] = "Tidak ada layanan dengan status ini.";
$lang['AdminBilling.transactions.page_title'] = "Transaksi Penagihan";
$lang['AdminBilling.printqueue.page_title'] = "cetak Antrian Penagihan ";
$lang['AdminBilling.printqueue.category_to_print'] = "Mencetak";
$lang['AdminBilling.printqueue.category_printed'] = "Sebelumnya Dicetak";
$lang['AdminBilling.printqueue.boxtitle_printqueue'] = "Cetak Antrian";
$lang['AdminBilling.printqueue.no_results_printed'] = "Tidak ada faktur dicetak sebelumnya.";
$lang['AdminBilling.printqueue.no_results_to_print'] = "Tidak ada antrian faktur untuk dicetak.";
$lang['AdminBilling.printqueue.heading_invoice'] = "Faktur #";
$lang['AdminBilling.printqueue.heading_client'] = "Klien #";
$lang['AdminBilling.printqueue.heading_amount'] = "Jumlah";
$lang['AdminBilling.printqueue.heading_paid'] = "Dibayar";
$lang['AdminBilling.printqueue.heading_due'] = "yg harus dibayar";
$lang['AdminBilling.printqueue.heading_datebilled'] = "Tanggal Ditagih";
$lang['AdminBilling.printqueue.heading_datedue'] = "Tanggal jatuh tempo";
$lang['AdminBilling.printqueue.heading_deliverydatesent'] = "Tanggal Terkirim";
$lang['AdminBilling.printqueue.text_printsubmit'] = "cetak";
$lang['AdminBilling.printqueue.text_marksubmit'] = "Tandai telah dicetak";
$lang['AdminBilling.batch.page_title'] = "Penagihan Batch";
$lang['AdminBilling.batch.boxtitle_batch'] = "Setumpuk / Batch";
$lang['AdminBilling.batch.no_passphrase'] = "Proses Batch manual tidak diaktifkan.";
$lang['AdminBilling.batch.field_passphrase'] = "Passphrase";
$lang['AdminBilling.batch.text_batchsubmit'] = "Proses Batch";
$lang['AdminBilling.services.heading_client'] = "Klien #";
$lang['AdminBilling.services.heading_options'] = "Pilihan";
$lang['AdminBilling.services.option_manage'] = "Mengelola";
$lang['AdminBilling.services.category_in_review'] = "Dalam Ulasan";
$lang['AdminBilling.services.category_scheduled_cancellation'] = "Dijadwalkan";
$lang['AdminBilling.serviceinfo.no_results'] = "Layanan ini tidak memiliki rincian.";
$lang['AdminBilling.!error.invalid_passphrase'] = "Passphrase yang dimasukkan tidak valid.";
$lang['AdminBilling.services.option_delete'] = "Hapus";
$lang['AdminBilling.services.confirm_delete'] = "Apakah Anda yakin ingin menghapus layanan ini?";
$lang['AdminBilling.batch.text_description'] = "Masukkan kata sandi Anda untuk secara manual proses batch semua faktur dijadwalkan untuk auto debet dengan rekening pembayaran disimpan secara lokal.";
$lang['AdminBilling.invoices.duration_infinite'] = "?";
$lang['AdminBilling.!success.services_scheduled_cancel'] = "Layanan yang terpilih berhasil di tambahkan ke jadwal pembatalan.";
$lang['AdminBilling.!success.services_scheduled_uncancel'] = "Layanan yang dipilih tidak lagi dijadwalkan untuk dibatalkan.";
$lang['AdminBilling.!error.future_cancel_date'] = "

The scheduled cancellation date must not be in the past.
";
$lang['AdminBilling.services.action.schedule_cancellation'] = "Jadwal Pembatalan
";
$lang['AdminBilling.services.action.field_action_type_term'] = "Ahir jangka waktu";
$lang['AdminBilling.services.action.field_action_type_date'] = "Tanggal spesifik";
$lang['AdminBilling.services.action.field_action_type_none'] = "Jangan di batalkan";
$lang['AdminBilling.services.field_actionsubmit'] = "Submit";
?>