<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyModules.!success.upgraded'] = "Modul berhasil diupgrade";
$lang['AdminCompanyModules.!success.installed'] = "Modul berhasil diinstal.";
$lang['AdminCompanyModules.!success.uninstalled'] = "Modul itu berhasil dihapus.";
$lang['AdminCompanyModules.!success.group_added'] = "Kelompok telah ditambahkan.";
$lang['AdminCompanyModules.!success.group_updated'] = "Kelompok ini berhasil diperbarui.";
$lang['AdminCompanyModules.!success.group_deleted'] = "Kelompok ini berhasil dihapus.";
$lang['AdminCompanyModules.available.text_author'] = "Penulis:";
$lang['AdminCompanyModules.installed.text_author'] = "Penulis:";
$lang['AdminCompanyModules.installed.btn_uninstall'] = "Uninstall";
$lang['AdminCompanyModules.installed.btn_manage'] = "Mengelola";
$lang['AdminCompanyModules.installed.btn_upgrade'] = "tingkatkan";
$lang['AdminCompanyModules.installed.confirm_uninstall'] = "Apakah Anda yakin ingin menghapus modul ini?";
$lang['AdminCompanyModules.manage.boxtitle_manage'] = "Mengelola %1\$s"; // %1$s is the name of the module
$lang['AdminCompanyModules.addgroup.boxtitle_add'] = "Tambahkan %1\$s %2\$s Group"; // %1$s is the module name, %2$s is the module row noun (e.g. Server)
$lang['AdminCompanyModules.addgroup.assigned'] = "Ditugaskan %1\$s"; // %1$s is the module row noun in plural form (e.g. Servers)
$lang['AdminCompanyModules.addgroup.text_order'] = "Tambahkan pesanan";
$lang['AdminCompanyModules.editgroup.btn_edit'] = "Pembaruan Grup";
$lang['AdminCompanyModules.editgroup.available'] = "Tersedia %1\$s"; // %1$s is the module row noun in plural form (e.g. Servers)
$lang['AdminCompanyModules.editgroup.text_order'] = "Tambahkan Pesanan";
$lang['AdminCompanyModules.addgroup.page_title'] = "Settings > Perusahaan > Modul > Tambah %1\$s %2\$s Group"; // %1$s is the module name, %2$s is the module row noun (e.g. Server)
$lang['AdminCompanyModules.addrow.page_title'] = "Pengaturan > Perusahaan > Modul > tambah %1\$s %2\$s"; // %1$s is the module name, %2$s is the module row noun (e.g. Server)
$lang['AdminCompanyModules.editrow.page_title'] = "Pengaturan> Perusahaan> Modul> Edit %1\$s %2\$s"; // %1$s is the module name, %2$s is the module row noun (e.g. Server)
$lang['AdminCompanyModules.available.text_version'] = "(ver %1\$s)"; // %1$s is the module's version number
?>