<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyTaxes.!success.taxrule_created'] = "Aturan pajak telah berhasil dibuat!";
$lang['AdminCompanyTaxes.countries.all'] = "--Semua--";
$lang['AdminCompanyTaxes.basic.boxtitle_basic'] = "Pengaturan Pajak Dasar";
$lang['AdminCompanyTaxes.rules.categorylink_addrule'] = "Tambahkan Tax Rule";
$lang['AdminCompanyTaxes.rules.heading_level1'] = "Aturan Level 1";
$lang['AdminCompanyTaxes.rules.text_type'] = "Jenis";
$lang['AdminCompanyTaxes.rules.text_amount'] = "Jumlah";
$lang['AdminCompanyTaxes.rules.text_country'] = "Negara";
$lang['AdminCompanyTaxes.rules.text_state'] = "State/Propinsi";
$lang['AdminCompanyTaxes.rules.option_edit'] = "Edit";
$lang['AdminCompanyTaxes.add.boxtitle_add'] = "Tambahkan Peraturan Pajak";
$lang['AdminCompanyTaxes.add.field_taxtype'] = "Jenis Pajak";
$lang['AdminCompanyTaxes.add.field_country'] = "Negara";
$lang['AdminCompanyTaxes.add.field_state'] = "Negara Bagian / Provinsi";
$lang['AdminCompanyTaxes.add.field_addsubmit'] = "Buat Aturan / Rule";
$lang['AdminCompanyTaxes.edit.boxtitle_edit'] = "Edit aturan pajak";
$lang['AdminCompanyTaxes.edit.field_taxtype'] = "Jenis Pajak";
$lang['AdminCompanyTaxes.edit.field_level1'] = "Level 1";
$lang['AdminCompanyTaxes.edit.field_name'] = "Nama Pajak";
$lang['AdminCompanyTaxes.edit.field_amount'] = "Jumlah";
$lang['AdminCompanyTaxes.edit.field_country'] = "Negara";
$lang['AdminCompanyTaxes.edit.field_state'] = "Provinsi";
$lang['AdminCompanyTaxes.edit.field_editsubmit'] = "Edit Rule";
$lang['AdminCompanyTaxes.basic.page_title'] = "Pengaturan> Perusahaan> Pajak> Pengaturan Pajak Dasar";
$lang['AdminCompanyTaxes.edit.page_title'] = "Pengaturan> Perusahaan> Pajak> Sunting Aturan Pajak";
$lang['AdminCompanyTaxes.basic.note_enable_tax'] = "Periksa opsi ini untuk mengaktifkan pajak untuk perusahaan ini.";
$lang['AdminCompanyTaxes.basic.note_cascade_tax'] = "Jika diaktifkan, pajak tingkat 1  akan dinilai pertama pada total faktur, dan pajak tingkat 2 akan dinilai pada jumlah baru ini termasuk tingkat pajak 1. hasil ini dalam pajak atas pajak. Othewise pajak tingkat  1 dan pajak tingkat 2 dinilai hanya pada Total tagihaan pra-pajak ";
$lang['AdminCompanyTaxes.basic.note_setup_fee_tax'] = "Jika diaktifkan, biaya setup apapun akan dikenai pajak.";
$lang['AdminCompanyTaxes.basic.note_cancelation_fee_tax'] = "Jika diaktifkan, biaya pembatalan akan dikenakan pajak.";
$lang['AdminCompanyTaxes.!tooltip.note_taxtype'] = "Inklusif akan menampilkan pajak sebagai bagian dari total. Eksklusif akan membuat daftar pajak secara terpisah dan tidak termasuk dalam total.";
$lang['AdminCompanyTaxes.!success.rule_deleted'] = "Aturan pajak telah berhasil dihapus.";
$lang['AdminCompanyTaxes.rules.option_delete'] = "Hapus";
$lang['AdminCompanyTaxes.rules.confirm_delete'] = "Apakah Anda yakin ingin menghapus aturan pajak ini?";
?>