<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyClientOptions.customfields.boxtitle_browse'] = "Jelajahi Bidang Kustom Klien";
$lang['AdminCompanyClientOptions.editcustomfield.field_encrypted'] = "Enkripsikan Nilai";
$lang['AdminCompanyClientOptions.editcustomfield.field_checkbox_value'] = "Nilai";
$lang['AdminCompanyClientOptions.requiredfields.field_company'] = "Perusahaan / Org.";
?>