<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyCurrencies.!success.setup_updated'] = "Pengaturan Mata berhasil diperbarui!";
$lang['AdminCompanyCurrencies.!success.delete_deleted'] = "mata uang %1\$s berhasil dihapus!"; // %1$s is the currency code
$lang['AdminCompanyCurrencies.setup.field_default_currency'] = "Standar Mata Uang";
$lang['AdminCompanyCurrencies.setup.field_show_currency_code'] = "Tampilkan Kode Mata uang";
$lang['AdminCompanyCurrencies.setup.heading_multicurrency'] = "Mata Uang Beragam";
$lang['AdminCompanyCurrencies.setup.field_multi_currency_package'] = "Gunakan Harga Paket pada Layanan Baru saja";
$lang['AdminCompanyCurrencies.setup.field_setupsubmit'] = "Pembaruan Pengaturan ";
$lang['AdminCompanyCurrencies.active.no_results'] = "Tidak ada mata uang yang aktif.";
$lang['AdminCompanyCurrencies.active.text_currency_code'] = "Kode Mata Uang (ISO 4217)";
$lang['AdminCompanyCurrencies.active.text_format'] = "Format";
$lang['AdminCompanyCurrencies.active.text_exchange_rate'] = "Kurs";
$lang['AdminCompanyCurrencies.active.text_options'] = "Pilihan";
$lang['AdminCompanyCurrencies.active.option_edit'] = "Mengedit";
$lang['AdminCompanyCurrencies.active.confirm_delete'] = "Apakah Anda yakin ingin menghapus mata uang ini?";
$lang['AdminCompanyCurrencies.add.boxtitle_add'] = "Tambah Mata Uang";
$lang['AdminCompanyCurrencies.add.field_code'] = "Kode Mata Uang (ISO 4217)";
$lang['AdminCompanyCurrencies.add.field_format'] = "Format";
$lang['AdminCompanyCurrencies.add.field_prefix'] = "Simbol Awalan";
$lang['AdminCompanyCurrencies.add.field_suffix'] = "Simbol Akhiran";
$lang['AdminCompanyCurrencies.add.field_exchange_rate'] = "Kurs";
$lang['AdminCompanyCurrencies.add.field_addsubmit'] = "Buat Mata Uang";
$lang['AdminCompanyCurrencies.edit.field_format'] = "Format";
$lang['AdminCompanyCurrencies.edit.field_prefix'] = "Simbol Awalan";
$lang['AdminCompanyCurrencies.edit.field_suffix'] = "Simbol Akhiran";
$lang['AdminCompanyCurrencies.edit.field_exchange_rate'] = "Kurs";
$lang['AdminCompanyCurrencies.edit.field_editsubmit'] = "Sunting Mata Uang";
$lang['AdminCompanyCurrencies.!cancel.field_cancel'] = "Membatalkan";
$lang['AdminCompanyCurrencies.setup.no_exchange_updated'] = "Tak Pernah";
$lang['AdminCompanyCurrencies.active.page_title'] = "Pengaturan> Perusahaan> Mata uang> Mataa uang Aktif";
$lang['AdminCompanyCurrencies.active.text_exchange_updated'] = "Terakhir Diperbarui";
$lang['AdminCompanyCurrencies.edit.page_title'] = "Pengaturan> Perusahaan> Mata uang > Edit Mata uang";
$lang['AdminCompanyCurrencies.!tooltip.precision'] = "Presisi adalah jumlah digit yang signifikan setelah tempat desimal yang mendukung mata uang.";
?>