<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyBilling.!success.notices_updated'] = "Pemberitahuan  Pembayaran Jatuh Tempo Karena berhasil diperbarui!";
$lang['AdminCompanyBilling.!success.acceptedtypes_updated'] = "Pengaturan Jenis Pembayaran Yang Diterima berhasil diperbarui!";
$lang['AdminCompanyBilling.!success.deliverymethods_updated'] = "Pengaturan Pengiriman Faktur berhasil diperbarui!";
$lang['AdminCompanyBilling.!success.customization_updated'] = "Pengaturan Faktur Kustomisasi berhasil diperbarui!";
$lang['AdminCompanyBilling.invoices.boxtitle_invoices'] = "Pilihan Faktur dan Biaya ";
$lang['AdminCompanyBilling.invoices.field_invoicedays'] = "faktur berapa Hari Sebelum Renewal";
$lang['AdminCompanyBilling.invoices.field_client_invoice'] = "Biarkan Client untuk mengautur Metode Faktur";
$lang['AdminCompanyBilling.invoices.field_suspend_services'] = "Faktur Layanan ditangguhkan";
$lang['AdminCompanyBilling.invoices.field_cancel_services'] = "Perbolehkan klien untuk Membatalkan Layanan";
$lang['AdminCompanyBilling.invoices.field_invoicessubmit'] = "Pembaruan Pengaturan ";
$lang['AdminCompanyBilling.notices.text_before'] = "Sebelum";
$lang['AdminCompanyBilling.notices.text_inv_duedate'] = "Tanggal Faktur Jatuh Tempo";
$lang['AdminCompanyBilling.notices.text_duedate'] = "Tanggal Jatuh Tempo";
$lang['AdminCompanyBilling.notices.text_disabled'] = "Disabled";
$lang['AdminCompanyBilling.notices.text_edit_template'] = "Edit Template Email";
$lang['AdminCompanyBilling.notices.field_second_notice'] = "Pemberitahuan kedua";
$lang['AdminCompanyBilling.notices.field_noticessubmit'] = "Update Pengaturan";
$lang['AdminCompanyBilling.coupons.categorylink_addcoupon'] = "Tambahkan Kupon";
$lang['AdminCompanyBilling.coupons.text_code'] = "Kode";
$lang['AdminCompanyBilling.coupons.text_max'] = "Max";
$lang['AdminCompanyBilling.coupons.text_start_date'] = "Tanggal Mulai ";
$lang['AdminCompanyBilling.coupons.text_end_date'] = "Tanggal Akhir";
$lang['AdminCompanyBilling.coupons.option_delete'] = "Hapus";
$lang['AdminCompanyBilling.coupons.confirm_delete'] = "Apakah Anda yakin ingin menghapus kupon ini?";
$lang['AdminCompanyBilling.addcoupon.heading_basic'] = "Dasar";
$lang['AdminCompanyBilling.addcoupon.field_recurring_no'] = "Terapkan hanya ketika layanan ditambahkan";
$lang['AdminCompanyBilling.addcoupon.field_recurring_yes'] = "Terapkan ketika layanan ditambahkan atau memperbaharui";
$lang['AdminCompanyBilling.addcoupon.text_generate_code'] = "Menghasilkan kode";
$lang['AdminCompanyBilling.addcoupon.field_start_date'] = "Tanggal Mulai ";
$lang['AdminCompanyBilling.addcoupon.field_end_date'] = "Tanggal akhir";
$lang['AdminCompanyBilling.addcoupon.field_max_qty'] = "Kuantitas";
$lang['AdminCompanyBilling.addcoupon.heading_discount'] = "Pilihan diskon";
$lang['AdminCompanyBilling.addcoupon.categorylink_addcurrency'] = "Tambahkan Mata Uang Tambahan";
$lang['AdminCompanyBilling.addcoupon.text_type'] = "Jenis";
$lang['AdminCompanyBilling.addcoupon.text_value'] = "Nilai";
$lang['AdminCompanyBilling.addcoupon.option_remove'] = "Menghapus";
$lang['AdminCompanyBilling.addcoupon.heading_packages'] = "Paket";
$lang['AdminCompanyBilling.editcoupon.boxtitle_edit'] = "edit Kupon";
$lang['AdminCompanyBilling.editcoupon.heading_basic'] = "Dasar";
$lang['AdminCompanyBilling.editcoupon.field_recurring_no'] = "Terapkan hanya ketika layanan ditambahkan";
$lang['AdminCompanyBilling.editcoupon.field_code'] = "Kode Kupon";
$lang['AdminCompanyBilling.editcoupon.text_generate_code'] = "Hasilkan kode";
$lang['AdminCompanyBilling.editcoupon.field_start_date'] = "Tanggal Mulai ";
$lang['AdminCompanyBilling.editcoupon.heading_discount'] = "Pilihan diskon";
$lang['AdminCompanyBilling.editcoupon.categorylink_addcurrency'] = "Tambah Mata Uang Tambahan";
$lang['AdminCompanyBilling.editcoupon.text_currency'] = "Mata uang";
$lang['AdminCompanyBilling.editcoupon.text_type'] = "Jenis";
$lang['AdminCompanyBilling.editcoupon.text_value'] = "Nilai";
$lang['AdminCompanyBilling.editcoupon.option_remove'] = "Menghapus";
$lang['AdminCompanyBilling.editcoupon.heading_packages'] = "Paket";
$lang['AdminCompanyBilling.editcoupon.field_couponsubmit'] = "Sunting Kupon";
$lang['AdminCompanyBilling.editcoupon.text_assigned_packages'] = "Paket yang dialokasikan";
$lang['AdminCompanyBilling.editcoupon.text_available_packages'] = "Paket yang tersedia";
$lang['AdminCompanyBilling.editcoupon.text_used_qty'] = "(digunakan %1\$s)"; // %1$s is the number of used coupons
$lang['AdminCompanyBilling.customization.boxtitle_customization'] = "Kustomisasi Faktur ";
$lang['AdminCompanyBilling.customization.heading_general'] = "Pilihan Dasar";
$lang['AdminCompanyBilling.customization.field_inv_start'] = "Faktur Mulai dari Nilai";
$lang['AdminCompanyBilling.customization.field_inv_logo'] = "Logo";
$lang['AdminCompanyBilling.customization.field_inv_paper_size'] = "Ukuran Kertas";
$lang['AdminCompanyBilling.customization.field_inv_display_logo'] = "Logo";
$lang['AdminCompanyBilling.customization.field_inv_display_company'] = "Nama Perusahaan / Alamat";
$lang['AdminCompanyBilling.customization.field_inv_mimetype'] = "Jenis File Invoice";
$lang['AdminCompanyBilling.customization.remove'] = "Hapus";
$lang['AdminCompanyBilling.customization.field_customizationsubmit'] = "Pengaturan pembaruan";
$lang['AdminCompanyBilling.acceptedtypes.field_ach'] = "Automated Clearing House";
$lang['AdminCompanyBilling.deliverymethods.heading_basic'] = "Pilihan Dasar";
$lang['AdminCompanyBilling.deliverymethods.heading_interfax'] = "Interfax";
$lang['AdminCompanyBilling.deliverymethods.interfax_desc'] = "Interfax memungkinkan Anda untuk faks faktur melalui internet. <a href=\"http://www.interfax.net/\" target=\"_blank\"> Daftar </a> untuk account Interfax dan mulai fax faktur hari ini.";
$lang['AdminCompanyBilling.deliverymethods.heading_postalmethods'] = "Mode Pos";
$lang['AdminCompanyBilling.deliverymethods.field_interfax_username'] = "Nama pengguna";
$lang['AdminCompanyBilling.deliverymethods.field_interfax_password'] = "Kata Sandi";
$lang['AdminCompanyBilling.deliverymethods.field_postalmethods_testmode'] = "Mode Tes";
$lang['AdminCompanyBilling.notices.field_notice_pending_autodebit'] = "Pemberitahuan Auto-Debit yang tertunda";
$lang['AdminCompanyBilling.coupons.page_title'] = "Pengaturan> Perusahaan> Penagihan / Pembayaran> Kupon";
$lang['AdminCompanyBilling.addcoupon.page_title'] = "Pengaturan> Perusahaan> Billing / Pembayaran> Kupon Baru";
$lang['AdminCompanyBilling.addcoupon.text_all'] = "Semua";
$lang['AdminCompanyBilling.editcoupon.text_all'] = "Semua";
$lang['AdminCompanyBilling.customization.note_inv_pad_str'] = "Nomor faktur yang karakter panjangnya kurang dari ukuran padding faktur, akan geser ke kiri dengan karakter yang diberikan.";
$lang['AdminCompanyBilling.deliverymethods.field_postalmethods_apikey'] = "API Key";
$lang['AdminCompanyBilling.!notice.group_settings'] = "CATATAN: Pengaturan ini hanya berlaku untuk Grup Client yang menggunakan pengaturan mereka dari Perusahaan.";
$lang['AdminCompanyBilling.invoices.text_day'] = "%1\$s Hari "; // %1$s is the number 1
$lang['AdminCompanyBilling.notices.text_day'] = "%1\$s hari"; // %1$s is the number 1
$lang['AdminCompanyBilling.addcoupon.field_package_group_id'] = "Paket Grup Filter";
$lang['AdminCompanyBilling.invoices.field_autodebit_attempts'] = "Upaya Auto Debit";
$lang['AdminCompanyBilling.invoices.note_autodebit_attempts'] = "Sejumlah kegagalan untuk memproses rekening pembayaran, sebelumnya rekening pembayaran telah dinonaktifkan dari debet otomatis.";
$lang['AdminCompanyBilling.customization.field_inv_font'] = "Font Family";
$lang['AdminCompanyBilling.customization.field_inv_proforma_start'] = "Faktur Pro Forma Mulai dari Nilai";
$lang['AdminCompanyBilling.customization.note_inv_proforma_start'] = "Nomor faktur dimulai dari (dan bertambah) dari nomor berikut";
$lang['AdminCompanyBilling.!tooltip.send_payment_notices'] = "Opsi ini menetapkan apakah klien dapat dikirimi salah satu pemberitahuan pembayaran yang tersedia.";
$lang['AdminCompanyBilling.invoices.field_autodebit'] = "Aktifkan Auto Debit";
$lang['AdminCompanyBilling.notices.field_send_payment_notices'] = "Biarkan Pemberitahuan Pembayaran akan terkirim";
$lang['AdminCompanyBilling.customization.field_inv_display_payments'] = "Pembayaran / Kredit";
$lang['AdminCompanyBilling.invoices.field_cancel_service_changes_days'] = "Perubahan Pembatalan Layanan Hari Setelah Jatuh Tempo";
$lang['AdminCompanyBilling.invoices.field_process_paid_service_changes'] = "Antrian Layanan Perubahan Sampai Dibayar";
$lang['AdminCompanyBilling.customization.field_inv_display_due_date_draft'] = "Tanggal jatuh tempo - Konsep";
$lang['AdminCompanyBilling.customization.note_inv_format'] = "Tags tersedia meliputi: {num} -nomor faktur (diperlukan); {year} - tahun empat digit; {month} -bulan dua digit; {day} - hari dua digit / bulan.";
$lang['AdminCompanyBilling.customization.note_inv_proforma_format'] = "Tags tersedia meliputi: {num} - nomor faktur (diperlukan);  {year} - empat digit; {month} - dua digit ;{day} -dua digit ";
$lang['AdminCompanyBilling.invoices.note_inv_group_services'] = "Buat satu invoice untuk layanan yang diperbarui oleh klien di hari yang sama. Bila tidak diceklis maka masing-masing layanan akan memiliki invoice tersendiri.";
?>