<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyEmails.!success.edittemplate_updated'] = "Pengaturan Template email berhasil diperbarui!";
$lang['AdminCompanyEmails.!success.addsignature_created'] = "Tanda tangan email telah berhasil dibuat!";
$lang['AdminCompanyEmails.!success.deletesignature_deleted'] = "Tanda tangan email telah berhasil dihapus!";
$lang['AdminCompanyEmails.!success.mail_updated'] = "Pengaturan Mail telah berhasil diperbarui!";
$lang['AdminCompanyEmails.!cancel.field_cancel'] = "batalkan";
$lang['AdminCompanyEmails.templates.boxtitle_templates'] = "Template Email";
$lang['AdminCompanyEmails.templates.heading_staff'] = "Email Staf";
$lang['AdminCompanyEmails.templates.heading_shared'] = "Email bersama";
$lang['AdminCompanyEmails.templates.heading_plugins'] = "Email Plugin";
$lang['AdminCompanyEmails.templates.text_name'] = "Nama";
$lang['AdminCompanyEmails.templates.text_description'] = "Deskripsi";
$lang['AdminCompanyEmails.templates.option_edit'] = "Edit";
$lang['AdminCompanyEmails.templates.payment_cc_approved_desc'] = "Pemberitahuan dikirim setelah pembayaran kartu kredit berhasil disetujui.
";
$lang['AdminCompanyEmails.templates.payment_cc_declined_name'] = "Pembayaran Ditolak (Kartu Kredit)";
$lang['AdminCompanyEmails.templates.payment_cc_declined_desc'] = "Pemberitahuan dikirim setelah upaya pembayaran kartu kredit ditolak.";
$lang['AdminCompanyEmails.templates.payment_cc_error_name'] = "Kesalahan Pembayaran (Kartu Kredit)";
$lang['AdminCompanyEmails.templates.payment_ach_approved_name'] = "Pembayaran Disetujui (ACH)";
$lang['AdminCompanyEmails.templates.payment_ach_declined_name'] = "Pembayaran Ditolak (ACH)";
$lang['AdminCompanyEmails.templates.payment_ach_declined_desc'] = "Pemberitahuan dikirim setelah upaya pembayaran ACH ditolak.";
$lang['AdminCompanyEmails.templates.credit_card_expiration_name'] = "Kadaluarsa Kartu Kredit ";
$lang['AdminCompanyEmails.templates.credit_card_expiration_desc'] = "Pemberitahuan dikirim bila kartu kredit aktif akan berakhir.";
$lang['AdminCompanyEmails.templates.invoice_delivery_paid_desc'] = "Pemberitahuan berisi salinan PDF dari Invoice berbayar.";
$lang['AdminCompanyEmails.templates.invoice_notice_first_name'] = "Pemberitahuan Invoice (1)";
$lang['AdminCompanyEmails.templates.invoice_notice_first_desc'] = "Pemberitahuan faktur pertama, pengingat untuk membayar atau akhir pemberitahuan.";
$lang['AdminCompanyEmails.templates.invoice_notice_second_name'] = "Invoice pemberitahuan (2)";
$lang['AdminCompanyEmails.templates.invoice_notice_second_desc'] = "Pemberitahuan tagihan kedua, sebagai pengingat untuk pembayaran atau pemberitahuan terakhir";
$lang['AdminCompanyEmails.templates.invoice_notice_third_name'] = "Peringatan invoice ketiga";
$lang['AdminCompanyEmails.templates.invoice_notice_third_desc'] = "Peringatan Tagihan ketiga, baik sebagai pengingat untuk membayar maupun pemberitahuan akhir.";
$lang['AdminCompanyEmails.templates.reset_password_name'] = "Reset Kata sandi";
$lang['AdminCompanyEmails.templates.service_suspension_name'] = "Layanan ditangguhkan";
$lang['AdminCompanyEmails.templates.account_welcome_name'] = "Pendaftaran akun";
$lang['AdminCompanyEmails.templates.account_welcome_desc'] = "Pemberitahuan Selamat datang dikirim untuk pendaftaran akun baru.";
$lang['AdminCompanyEmails.templates.service_suspension_error_desc'] = "Pemberitahuan dikirim setelah usaha yang gagal untuk menangguhkan layanan.";
$lang['AdminCompanyEmails.templates.service_unsuspension_error_desc'] = "Pemberitahuan dikirim setelah usaha yang gagal untuk unsuspend layanan.";
$lang['AdminCompanyEmails.templates.service_cancel_error_desc'] = "Pemberitahuan dikirim setelah usaha yang gagal untuk membatalkan layanan.";
$lang['AdminCompanyEmails.templates.auto_debit_pending_name'] = "Auto-debit Tertunda";
$lang['AdminCompanyEmails.templates.auto_debit_pending_desc'] = "Pemberitahuan dikirim yang menunjukkan pembayaran otomatis akan segera diupayakan";
$lang['AdminCompanyEmails.templates.staff_reset_password_name'] = "Reset Password";
$lang['AdminCompanyEmails.edittemplate.text_none'] = "Tidak ada";
$lang['AdminCompanyEmails.edittemplate.field_from_name'] = "Dari Nama";
$lang['AdminCompanyEmails.edittemplate.field_from'] = "Email Dari ";
$lang['AdminCompanyEmails.edittemplate.field_subject'] = "Subjek";
$lang['AdminCompanyEmails.edittemplate.field_tags'] = "Tags Tersedia ";
$lang['AdminCompanyEmails.edittemplate.field_email_signature_id'] = "Tanda tangan";
$lang['AdminCompanyEmails.signatures.boxtitle_signatures'] = "Signatures";
$lang['AdminCompanyEmails.signatures.no_results'] = "Tidak ada tanda tangan email.";
$lang['AdminCompanyEmails.signatures.text_options'] = "Pilihan";
$lang['AdminCompanyEmails.signatures.option_edit'] = "Edit";
$lang['AdminCompanyEmails.addsignature.field_name'] = "Nama";
$lang['AdminCompanyEmails.addsignature.field_text'] = "Text";
$lang['AdminCompanyEmails.addsignature.field_html'] = "HTML";
$lang['AdminCompanyEmails.addsignature.field_addsignaturesubmit'] = "Buat Signature";
$lang['AdminCompanyEmails.addsignature.text_signatures'] = "Tanda tangan yang digunakan untuk template email, sehingga lebih mudah untuk mengubah tanda tangan email dalam jumlah besar";
$lang['AdminCompanyEmails.editsignature.boxtitle_editsignature'] = "edit Signature";
$lang['AdminCompanyEmails.editsignature.field_text'] = "Teks";
$lang['AdminCompanyEmails.editsignature.field_html'] = "HTML";
$lang['AdminCompanyEmails.mail.text_section'] = "Bagian ini mengontrol bagaimana email dikirim dari Blesta. PHP adalah metode pengiriman yang paling sederhana, tetapi SMTP umumnya lebih cepat dan lebih dapat diandalkan.";
$lang['AdminCompanyEmails.mail.field_html_email'] = "Aktifkan HTML";
$lang['AdminCompanyEmails.mail.field_mail_delivery'] = "Metode Pengiriman";
$lang['AdminCompanyEmails.mail.field_smtp_host'] = "SMTP Host";
$lang['AdminCompanyEmails.mail.field_smtp_user'] = "SMTP User";
$lang['AdminCompanyEmails.mail.field_smtp_password'] = "SMTP Password";
$lang['AdminCompanyEmails.getRequiredMethods.php'] = "PHP";
$lang['AdminCompanyEmails.getRequiredMethods.smtp'] = "SMTP";
$lang['AdminCompanyEmails.edittemplate.page_title'] = "Pengaturan> Perusahaan> Email> Edit Template Email";
$lang['AdminCompanyEmails.addsignature.page_title'] = "Pengaturan> Perusahaan> Email> tambah Signature";
$lang['AdminCompanyEmails.mail.page_title'] = "Pengaturan> Perusahaan> Email> Pengaturan Mail";
$lang['AdminCompanyEmails.mail.field_smtp_security'] = "SMTP Security";
$lang['AdminCompanyEmails.getsmtpsecurityoptions.none'] = "Tidak ada";
$lang['AdminCompanyEmails.getsmtpsecurityoptions.ssl'] = "SSL";
$lang['AdminCompanyEmails.getsmtpsecurityoptions.tls'] = "TLS";
$lang['AdminCompanyEmails.templates.service_unsuspension_desc'] = "Pemberitahuan unsuspended layanan, dikirim bila layanan secara otomatis unsuspended.";
$lang['AdminCompanyEmails.templates.service_creation_error_desc'] = "Pemberitahuan dikirim setelah usaha yang gagal untuk penyediaan layanan.";
$lang['AdminCompanyEmails.edittemplate.field_include_attachments'] = "Sertakan Setiap Lampiran";
$lang['AdminCompanyEmails.edittemplate.note_include_attachments'] = "Hapus tanda centang untuk menonaktifkan masuknya lampiran yang seharusnya dikirim ke email menggunakan template ini.";
$lang['AdminCompanyEmails.templates.report_ar_desc'] = "Tiga puluh, Enam Puluh, Sembilan Puluh hari Laporan Faktur, disampaikan sekali per bulan.";
$lang['AdminCompanyEmails.templates.report_tax_liability_name'] = "Laporan Kewajiban Pajak";
$lang['AdminCompanyEmails.templates.report_tax_liability_desc'] = "Sebuah Laporan bulanan Kewajiban Pajak, dihasilkan untuk bulan sebelumnya.";
$lang['AdminCompanyEmails.templates.payment_nonmerchant_approved_desc'] = "Pemberitahuan dikirim setelah pembayaran diterima dari gateway non-merchant.";
?>