<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ApiKeys.!error.key.generate'] = "Kuncinya gagal dihasilkan.";
$lang['ApiKeys.!error.company_id.exists'] = "Perusahaan yang diberikan tidak ada.";
$lang['ApiKeys.!error.user.valid'] = "Pengguna API atau kunci tampaknya tidak valid.";
$lang['ApiKeys.!error.user.unique'] = "Pengguna API sudah ada untuk perusahaan tertentu.";
?>