<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AppController.lang.dir'] = "ltr";
$lang['AppController.modal.text_close'] = "Tutup";
$lang['AppController.structure.text_myinfo'] = "Info saya";
$lang['AppController.structure.text_logout'] = "Keluar";
$lang['AppController.!error.invalid_csrf'] = "Bentuk token tidak valid.";
$lang['AppController.message.close'] = "×";
$lang['AppController.structure.text_maintenance'] = "Maintenance Mode saat diaktifkan dan klien mungkin tidak bisa masuk. Klik di sini untuk merubah.";
$lang['AppController.structure.text_search_placeholder'] = "%1\$s..."; // %1$s is the search type
$lang['AppController.client_structure.default_title'] = "Akun saya";
$lang['AppController.client_structure.text_return_to_portal'] = "Kembali ke Portal";
$lang['AppController.dates.day_mon'] = "Senin";
$lang['AppController.dates.day_wed'] = "Rabu";
$lang['AppController.dates.day_thu'] = "Kamis";
$lang['AppController.dates.day_sat'] = "Sabtu";
$lang['AppController.dates.dayabbr_mon'] = "Senin";
$lang['AppController.dates.dayabbr_tue'] = "Selasa";
$lang['AppController.dates.dayabbr_wed'] = "Rabu";
$lang['AppController.dates.dayabbr_thur'] = "Kamis";
$lang['AppController.dates.month_feb'] = "Februari";
$lang['AppController.dates.month_mar'] = "Maret";
$lang['AppController.dates.month_aug'] = "Agustus";
$lang['AppController.dates.month_sep'] = "Bulan September";
$lang['AppController.dates.month_oct'] = "Bulan Oktober";
$lang['AppController.dates.month_nov'] = "November";
$lang['AppController.dates.month_dec'] = "Desember";
$lang['AppController.dates.monthabbr_jan'] = "Januari";
$lang['AppController.dates.monthabbr_feb'] = "Feb";
$lang['AppController.dates.monthabbr_apr'] = "April";
$lang['AppController.dates.monthabbr_may'] = "Mei";
$lang['AppController.dates.monthabbr_jun'] = "Juni";
$lang['AppController.dates.monthabbr_oct'] = "Okt";
$lang['AppController.!success.license_updated'] = "Lisensi Anda berhasil divalidasi ulang. Silakan login.";
$lang['AppController.!success.license_key_updated'] = "Kunci lisensi Anda telah berhasil diperbarui. Silakan login.";
$lang['AppController.select.please'] = "-- Mohon pilih --";
$lang['AppController.sreader.dropdown'] = "Toggle Dropdown";
$lang['AppController.sreader.navigation'] = "PIndah Navigasi";
$lang['AppController.client_structure.staff_as_client_note'] = "Kembali ke Portal Staf";
?>