<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Backup.!error.driver.support'] = "Driver database tidak didukung.";
$lang['Backup.!error.temp_dir.writable'] = "Direktori temp tidak dapat ditulis.";
$lang['Backup.frequencies.day'] = "Hari";
$lang['Backup.frequencies.days'] = "%1\$s hari"; // %1$s is the number of days
$lang['Backup.!error.amazons3_failed'] = "AmazonS3 gagal backup";
$lang['Backup.frequencies.never'] = "Tak pernah";
$lang['Backup.!error.ftp_failed'] = "SFTP backup gagal.";
?>