<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['CalendarEvents.!error.company_id.exists'] = "ID perusahaan tidak valid.";
$lang['CalendarEvents.!error.staff_id.exists'] = "Staf ID tidak cocok";
$lang['CalendarEvents.!error.title.empty'] = "Silahkan masukkan judul.";
$lang['CalendarEvents.!error.start_date.order'] = "Tanggal mulai harus sebelum tanggal akhir.";
?>