<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientLogin.!error.unknown_user'] = "Username tidak dikenali atau password tidak bisa direset.";
$lang['ClientLogin.!success.reset_sent'] = "Sebuah email konfirmasi telah dikirim ke alamat yang ada pada catatan.";
$lang['ClientLogin.index.field_password'] = "Kata sandi";
$lang['ClientLogin.reset.page_title'] = "Reset Password";
$lang['ClientLogin.reset.field_resetsubmit'] = "Reset Password";
$lang['ClientLogin.confirmreset.reset_heading'] = "Konfirmas Reseti Password";
$lang['ClientLogin.confirmreset.field_new_password'] = "kata sandi baru";
$lang['ClientLogin.confirmreset.field_confirm_password'] = "Konfirmasi Password Baru";
$lang['ClientLogin.confirmreset.field_resetsubmit'] = "Set Password";
$lang['ClientLogin.confirmreset.link_login'] = "Batal, Log In";
$lang['ClientLogin.reset.description'] = "Masukkan nama pengguna untuk meminta link reset password.";
$lang['ClientLogin.index.page_title'] = "Masuk";
$lang['ClientLogin.index.login_heading'] = "Masuk";
$lang['ClientLogin.index.field_loginsubmit'] = "Masuk";
$lang['ClientLogin.otp.field_otp'] = "Password sekali pakai";
$lang['ClientLogin.otp.field_submit'] = "Masuk";
?>