<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientServices.index.page_title'] = "Klien #%1\$s Jasa"; // %1$s is the client ID number
$lang['ClientServices.index.category_pending'] = "Tertunda";
$lang['ClientServices.index.category_suspended'] = "Ditangguhkan";
$lang['ClientServices.index.heading_package'] = "Paket";
$lang['ClientServices.index.heading_term'] = "Istilah";
$lang['ClientServices.index.heading_options'] = "Pilihan";
$lang['ClientServices.index.no_results'] = "Anda tidak memiliki %1\$s Jasa."; // %1$s is the language for the services category type (e.g. Active, Pending)
$lang['ClientServices.serviceinfo.no_results'] = "Layanan ini tidak ada penjelasan.";
$lang['ClientServices.index.heading_status'] = "Status";
$lang['ClientServices.index.heading_datesuspended'] = "Tanggal Ditangguhkan";
$lang['ClientServices.index.heading_datecanceled'] = "Tanggal Dibatalkan";
$lang['ClientServices.manage.tab_service_info'] = "Informasi";
$lang['ClientServices.!success.service_schedule_canceled'] = "Layanan ini dijadwalkan akan dibatalkan pada akhir masa periode";
$lang['ClientServices.cancel.heading_cancel'] = "Batalkan Layanan";
$lang['ClientServices.cancel.field_term_date'] = "Akhir Term  (%1\$s)"; // %1$s is the date the service's term ends
$lang['ClientServices.cancel.field_now'] = "Segera";
$lang['ClientServices.cancel.confirm_cancel_now'] = "Apakah Anda yakin ingin membatalkan layanan ini?";
$lang['ClientServices.cancel.confirm_cancel_now_fee'] = "Membatalkan layanan ini akan dikenakan biaya pembatalan%1\$s."; // %1$s is the formatted amount of the cancelation fee
$lang['ClientServices.!error.password_mismatch'] = "Sandi tidak cocok dengan password login anda";
$lang['ClientServices.!success.service_not_canceled'] = "Layanan ini tidak akan dibatalkan";
$lang['ClientServices.!success.addon_service_created'] = "Layanan addon telah berhasil dibuat. Namun, tidak akan diaktifkan sampai setelah pembayaran telah diterima.";
$lang['ClientServices.manage.tab_addons'] = "Addons";
$lang['ClientServices.manage.button_active'] = "Active";
$lang['ClientServices.manage.button_pending'] = "Tertunda";
$lang['ClientServices.manage.button_suspended'] = "ditangguhkan";
$lang['ClientServices.manage.button_in_review'] = "Dalam Ulasan";
$lang['ClientServices.manage.button_cancel'] = "Batalkan pilihan";
$lang['ClientServices.manage.heading_package'] = "Paket";
$lang['ClientServices.manage.heading_date_added'] = "Tanggal pembuatan";
$lang['ClientServices.manage.heading_package_term'] = "Siklus penagihan";
$lang['ClientServices.manage.heading_date_next_invoice'] = "Faktur Berikutnya";
$lang['ClientServices.manage.heading_config_options'] = "Pilihan dikonfigurasi";
$lang['ClientServices.cancel.field_do_not'] = "Jangan batalkan";
$lang['ClientServices.cancel.field_password'] = "Password Log In untuk Konfirmasi Perubahan";
$lang['ClientServices.cancel.field_cancel_cancel'] = "batalkan, tidak berubah";
$lang['ClientServices.addons.page_title'] = "Klien #%1\$s Addons"; // %1$s is the client ID number
$lang['ClientServices.addons.boxtitle_addons'] = "Tambahan untuk %1\$s - %2\$s"; // %1$s is the package name, %2$s is the service name
$lang['ClientServices.addaddon.header_add'] = "Addons";
$lang['ClientServices.addaddon.term_price'] = "%1\$s - %2\$s"; // %1$s is the package term, (e.g. 1 Month), %2$s is the formatted package price
$lang['ClientServices.configure_addon.header_options'] = "Pilihan bisa dikonfigurasi"; // %1$s is the module name
$lang['ClientServices.!error.invoices_upgrade_package'] = "Paket ini tidak dapat diubah sampai semua faktur yang berisi layanan ini telah dibayar.";
$lang['ClientServices.!warning.invoices_upgrade_package'] = "Paket tidak dapat diubah sampai semua faktur untuk layanan ini telah dibayar.";
$lang['ClientServices.manage.button_change_service_term'] = "Ubah Term/syarat";
$lang['ClientServices.manage.text_price'] = "%1\$sx %2\$s"; // %1$s is the service quantity, %2$s is the package price
$lang['ClientServices.manage.text_date_suspended'] = "Layanan ini ditangguhkan pada %1\$s."; // %1$s is the date the service was suspended
$lang['ClientServices.cancel.field_cancel_submit'] = "Simpan";
$lang['ClientServices.get_package_terms.term'] = "%1\$s %2\$s - %3\$s"; // %1$s is the pricing term, %2$s is the pricing period, and %3$s is the formatted price
$lang['ClientServices.get_package_terms.term_onetime'] = "%1\$s - %2\$s"; // %1$s is the pricing period, and %2$s is the formatted price
$lang['ClientServices.upgrade.btn_make_payment'] = "Buat pembayaran";
$lang['ClientServices.upgrade.current_package'] = "%1\$s (%2\$s %3\$s - %4\$s)"; // %1$s is the package name, %2$s is the pricing term, %3$s is the pricing period, and %4$s is the formatted price
$lang['ClientServices.!notice.queued_service_change'] = "Layanan ini telah tertunda yang perubahan. Perubahan tambahan tidak dapat dilakukan sampai perubahan tertunda yang saat ini telah diproses.";
$lang['ClientServices.!success.service_term_updated'] = "Periode layanan telah diperbarui dan akan berlaku pada tanggal memperbaharui berikutnya.";
$lang['ClientServices.manage.heading_price_onetime'] = "Jumlah";
$lang['ClientServices.manage.heading_recurring_coupon'] = "Kupon berulang";
$lang['ClientServices.change_term.boxtitle'] = "Ubah Term untuk %1\$s - %2\$s"; // %1$s is the package name, %2$s is the service name
$lang['ClientServices.change_term.cancel'] = "batalkan";
$lang['ClientServices.change_term.review'] = "Ulasan";
$lang['ClientServices.manageoptions.page_title'] = "Klien #%1\$s Mengelola Pilihan Di konfigurasi"; // %1$s is the client ID number
$lang['ClientServices.manageoptions.heading_current'] = "Pilihan Sekarang";
$lang['ClientServices.review.heading_updated_service'] = "Layanan Diperbaharui";
$lang['ClientServices.review.heading_label'] = "Pilihan";
$lang['ClientServices.review.heading_old_value'] = "Nilai sekarang";
$lang['ClientServices.review.heading_new_value'] = "Nilai baru";
$lang['ClientServices.review.none'] = "-";
$lang['ClientServices.totals.total'] = "Total:";
$lang['ClientServices.review.boxtitle_review'] = "Tinjau Perubahan ke %1\$s - %2\$s"; // %1$s is the package name, %2$s is the service name
?>