<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientTransactions.index.page_title'] = "Transaksi Klien #%1\$s"; // %1$s is the client ID number
$lang['ClientTransactions.index.category_approved'] = "Disetujui";
$lang['ClientTransactions.index.heading_type'] = "Jenis";
$lang['ClientTransactions.index.heading_amount'] = "Jumlah";
$lang['ClientTransactions.index.heading_credited'] = "Dikreditkan";
$lang['ClientTransactions.index.heading_applied'] = "Terapan";
$lang['ClientTransactions.index.heading_number'] = "Nomor";
$lang['ClientTransactions.index.heading_date'] = "Tanggal";
$lang['ClientTransactions.applied.no_results'] = "Transaksi ini belum diterapkan untuk setiap faktur.";
?>