<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientContacts.!success.contact_deleted'] = "Kontak  %1\$s %2\$s berhasil dihapus!"; // %1$s is the contact's first name, %2$s is the contact's last name
$lang['ClientContacts.!success.contact_updated'] = "Kontak berhasil diperbarui!";
$lang['ClientContacts.!success.contact_added'] = "Kontak berhasil dibuat!";
$lang['ClientContacts.index.page_title'] = "Kontak Klien #%1\$s "; // %1$s is the client ID number
$lang['ClientContacts.index.create_contact'] = "Tambah Kontak
";
$lang['ClientContacts.index.boxtitle_contacts'] = "Kontak";
$lang['ClientContacts.index.heading_name'] = "Nama";
$lang['ClientContacts.index.heading_options'] = "Pilihan";
$lang['ClientContacts.index.option_edit'] = "Edit";
$lang['ClientContacts.index.option_delete'] = "Hapus";
$lang['ClientContacts.add.page_title'] = "Klien #%1\$s Tambah Kontak"; // %1$s is the client ID number
$lang['ClientContacts.edit.boxtitle_edit'] = "edit kontak";
$lang['ClientContacts.edit.field_editsubmit'] = "Perbarui Kontak";
$lang['ClientContacts.setcontactview.text_none'] = "Tidak Satupun";
$lang['ClientContacts.contact_info.field_first_name'] = "Nama Depan";
$lang['ClientContacts.contact_info.field_company'] = "Perusahaan";
$lang['ClientContacts.contact_info.field_address2'] = "Alamat 2";
$lang['ClientContacts.contact_info.field_zip'] = "Zip / kode pos";
$lang['ClientContacts.contact_info.field_email'] = "Email";
$lang['ClientContacts.phone_numbers.heading_phone'] = "Nomor telefon";
$lang['ClientContacts.phone_numbers.field_phonenumber'] = "Nomor";
$lang['ClientContacts.phone_numbers.text_remove'] = "Menghapus";
$lang['ClientContacts.index.no_results'] = "Anda tidak memiliki kontak. Untuk menambahkan kontak pertama Anda, klik tombol Tambah Kontak di atas.";
$lang['ClientContacts.phone_numbers.field_phoneoptions'] = "Pilihan";
$lang['ClientContacts.phone_numbers.categorylink_number'] = "Tambahkan Tambahan";
$lang['ClientContacts.add.heading_contact'] = "informasi Kontak";
$lang['ClientContacts.add.field_enable_login'] = "Aktifkan Login";
$lang['ClientContacts.add.field_username'] = "Username";
$lang['ClientContacts.add.field_confirm_password'] = "Konfirmasi Kata Sandi";
$lang['ClientContacts.add.heading_permissions'] = "Perizinan";
$lang['ClientContacts.edit.heading_contact'] = "informasi Kontak";
$lang['ClientContacts.edit.heading_authentication'] = "Pembuktian keaslian";
$lang['ClientContacts.edit.field_username'] = "Nama pengguna";
$lang['ClientContacts.edit.field_new_password'] = "kata sandi baru";
$lang['ClientContacts.edit.heading_permissions'] = "Perizinan";
$lang['ClientContacts.tooltip.client_invoices'] = "Tampilan Faktur pada dashboard, pengingat tanda pembayaran serta setiap ";
$lang['ClientContacts.tooltip.client_accounts'] = "Biarkan Account Pembayaran untuk dikelola.";
$lang['ClientContacts.tooltip._invoice_delivery'] = "Biarkan metode pengiriman invoice dilihat dan diubah.";
?>