<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Clients.!error.client_group_id.exists'] = "ID kelompok klien yang tidak valid.";
$lang['Clients.!error.client_id.exists'] = "ID pelanggan tidak valid";
$lang['Clients.!error.id_format.empty'] = "Tidak ada format ID yang ditetapkan untuk klien.";
$lang['Clients.!error.user_id.unique'] = "ID pengguna klien %1\$s telah terdaftar"; // %1$s is the client user ID number
$lang['Clients.!error.name.empty'] = "Masukkan nama.";
$lang['Clients.!error.is_lang.format'] = "is_lang harus berupa angka.";
$lang['Clients.!error.type.format'] = "Jenis tidak valid.";
$lang['Clients.!error.show_client.format'] = "Tampilkan client harus berupa angka.";
$lang['Clients.!error.encrypted.format'] = "Enskripsi harus berupa angka.";
$lang['Clients.!error.staff_id.exists'] = "ID staf tidak valid.";
$lang['Clients.!error.title.empty'] = "Harap masukkan judul.";
$lang['Clients.!error.note_id.exists'] = "Catatan ID salah";
$lang['Clients.getStatusTypes.inactive'] = "Tidak aktif";
$lang['Clients.getStatusTypes.fraud'] = "Penipuan";
$lang['Clients.!error.autodebit.format'] = "Nilai autodebet keliru";
$lang['Clients.!error.default_currency.valid'] = "Mata uang yang tidak valid.";
$lang['Clients.!error.inv_method.valid'] = "Metode pengiriman tagihan tidak valid.";
$lang['Clients.!error.inv_method.editable'] = "Metode pengiriman faktur tidak dapat diperbarui.";
$lang['Clients.!error.values.format'] = "Nilai dalam format yang tidak valid.";
$lang['Clients.!error.read_only.length'] = "Read only panjangnya tidak boleh melebihi 1 karakter.";
$lang['Clients.!error.value.required'] = "%1\$s dalam format yang tidak valid."; // %1$s is the name of the custom field
$lang['Clients.!error.value.valid'] = "%1\$s diatur ke nilai yang tidak valid."; // %1$s is the name of the custom field
$lang['Clients.!error.is_lang.length'] = "is_lang Tidak boleh memiliki karakter yang panjang";
$lang['Clients.setDebitAccountFailure.note_title'] = "Debit otomatis dinonaktifkan untuk rekening pembayaran.";
?>