<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientInvoices.index.page_title'] = "Faktur Klien  #%1\$s "; // %1$s is the client ID number
$lang['ClientInvoices.index.heading_invoice'] = "Tagihan #";
$lang['ClientInvoices.index.heading_due'] = "Jatuh Tempo";
$lang['ClientInvoices.index.heading_dateclosed'] = "Tanggal Ditutup";
$lang['ClientInvoices.index.heading_datebilled'] = "Tanggal Ditagih";
$lang['ClientInvoices.index.option_view'] = "Lihat";
$lang['ClientInvoices.index.option_pay'] = "bayar";
$lang['ClientInvoices.index.no_results'] = "Anda tidak memiliki Faktur %1\$s "; // %1$s is the language for the invoice category type (e.g. Open, Closed)
$lang['ClientInvoices.applied.heading_paymenttype'] = "Tipe pembayaran";
$lang['ClientInvoices.applied.heading_amount'] = "Jumlah";
$lang['ClientInvoices.applied.heading_appliedon'] = "Terapan Pada";
?>