<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Companies.!error.company_id.in_use'] = "Perusahaan sedang dalam digunakan sehingga tidak dapat dihapus.";
$lang['Companies.!error.name.length'] = "panjang Nama tidak boleh melebihi 64 karakter.";
$lang['Companies.!error.hostname.unique'] = "Hostname telah diambil oleh perusahaan lain.";
$lang['Companies.!error.inv_draft_format.format'] = "Format Draft Faktur tidak dapat bertentangan dengan Format Faktur.";
$lang['Companies.!error.inv_draft_format.contains'] = "Format Draft Faktur harus berisi {num}.";
$lang['Companies.!error.inv_increment.number'] = "Faktur Kenaikan Nilai harus berupa angka.";
$lang['Companies.!error.inv_pad_size.number'] = "Ukuran Padding Faktur harus berupa angka.";
$lang['Companies.!error.hostname.valid'] = "Masukkan hostname yang valid.";
$lang['Companies.!error.inv_proforma_start.number'] = "Nilai permulaan faktur pro forma harus berupa angka.";
?>