<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Contacts.!error.user_id.exists'] = "ID pengguna tidak valid.";
$lang['Contacts.!error.first_name.empty'] = "Masukkan nama pertama.";
$lang['Contacts.!error.last_name.empty'] = "Masukkan nama terakhir.";
$lang['Contacts.!error.email.format'] = "Alamat email salah.";
$lang['Contacts.!error.state.length'] = "Panjang negara tidak boleh melebihi 3 karakter.";
$lang['Contacts.!error.state.country_exists'] = "Silakan pilih negara yang sesuai dengan negara yang dipilih.";
$lang['Contacts.!error.contact_id.exists'] = "ID kontak tidak valid.";
$lang['Contacts.!error.location.format'] = "Lokasi tidak valid";
$lang['Contacts.!error.id.exists'] = "Nomor ID kontak tidak valid.";
$lang['Contacts.!error.company_id.format'] = "ID perusahaan tidak valid.";
$lang['Contacts.!error.name.empty'] = "Silakan masukkan nama.";
$lang['Contacts.getnumbertypes.fax'] = "Fax";
$lang['Contacts.getnumberlocations.home'] = "Home";
$lang['Contacts.getnumberlocations.work'] = "Jalan";
$lang['Contacts.getnumberlocations.mobile'] = "Mobil";
$lang['Contacts.!error.contact_type.inv_address_to'] = "Faktur sudah ditetapkan untuk ditujukan kepada kontak ini dan harus diubah sebelum memperbarui kontak ini.";
$lang['Contacts.getPermissionOptions.client_invoices'] = "Faktur";
$lang['Contacts.getPermissionOptions.client_transactions'] = "Transaksi";
$lang['Contacts.getPermissionOptions.client_contacts'] = "Kontak";
$lang['Contacts.getPermissionOptions._invoice_delivery'] = "Pengiriman Faktur";
$lang['Contacts.!error.state.empty'] = "Silahkan pilih provinsi";
?>