<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Countries.!error.alpha2.in_use'] = "Kode negara Alpha2, %1\$s, sudah diambil."; // %1$s is the alpha2 country code
$lang['Countries.!error.alpha3.in_use'] = "Kode negara Alpha3, %1\$s,  sudah diambil."; // %1$s is the alpha3 country code
$lang['Countries.!error.name.format'] = "Silakan masukkan nama.";
?>