<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Coupons.getAmountTypes.amount'] = "Jumlah";
$lang['Coupons.!error.code.empty'] = "Harap masukkan kode kupon.";
$lang['Coupons.!error.used_qty.format'] = "Kuantitas yang digunakan harus berupa angka.";
$lang['Coupons.!error.used_qty.length'] = "Panjang kuantitas tidak boleh melebihi 10 karakter.";
$lang['Coupons.!error.max_qty.format'] = "Kuantitas Max. harus berupa angka.";
$lang['Coupons.!error.max_qty.length'] = "Panjang kuantitas maksimal tidak boleh melebihi 10 karakter.";
$lang['Coupons.!error.status.format'] = "Status tidak valid.";
$lang['Coupons.!error.recurring.format'] = "Berulang harus berupa angka.";
$lang['Coupons.!error.recurring.length'] = "Panjang (berulang) tidak boleh melebihi 1 karakter.";
$lang['Coupons.!error.amounts.exists'] = "Hanya satu mata uang yang berlaku sebagai diskon untuk kupon ini.";
$lang['Coupons.!error.amounts[][currency].length'] = "Kode mata uang harus 3 karakter.";
$lang['Coupons.!error.amounts[][type].format'] = "Jenis jumlah yang tidak valid.";
$lang['Coupons.!error.max_qty.exceeded'] = "Jumlah yang digunakan tidak boleh melebihi jumlah maksimal.";
?>