<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Currencies.!error.code.length'] = "Kode mata uang harus 3 karakter alpha seperti yang didefinisikan dalam ISO 4217.";
$lang['Currencies.!error.prefix.length'] = "Awalan mata uang tidak boleh melebihi 10 karakter.";
$lang['Currencies.!error.suffix.length'] = "Akhiran mata uang tidak boleh melebihi 10 karakter.";
$lang['Currencies.!error.currency_code.is_default'] = "Mata uang %1\$s adalah mata uang default dan tidak dapat dihapus."; // %1$s is the currency code
$lang['Currencies.!error.processor.invalid'] = "Proses Nilai tukar tidak benar";
?>