<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Emails.!error.company_id.exists'] = "ID perusahaan tidak valid.";
$lang['Emails.!error.email_signature_id.in_use'] = "Tanda tangan email yang digunakan saat ini dan tidak dapat dihapus.";
$lang['Emails.!error.name.empty'] = "Masukkan nama tanda tangan.";
$lang['Emails.!error.email_signature_id.exists'] = "email ID signature tidak valid.";
$lang['Emails.!error.lang.empty'] = "Silakan masukkan bahasa.";
$lang['Emails.!error.from.format'] = "Masukkan alamat valid ";
$lang['Emails.!error.from_name.empty'] = "Masukkan nama dari.";
$lang['Emails.!error.subject.empty'] = "Silakan masukkan subjek.";
$lang['Emails.!error.email_id.exists'] = "ID email tidak valid.";
$lang['Emails.!error.company_id.unique'] = "Kelompok ID email dan ID perusahaan untuk bahasa yang diberikan sudah diambil.";
$lang['Emails.getStatusTypes.active'] = "Tidak";
$lang['Emails.!error.cc_addresses.format'] = "Setidaknya satu alamat email CC yang diberikan bukan alamat email yang valid.";
$lang['Emails.!error.attachments.exist'] = "Setidaknya salah satu lampiran yang disediakan tidak ada pada sistem file.";
$lang['Emails.!error.email.failed_to_send'] = "Email gagal untuk dikirim karena masalah konfigurasi.";
$lang['Emails.!error.reply_to.format'] = "Masukkan balasan yang valid - ke alamat";
$lang['Emails.!error.html.parse'] = "Template kesalahan parse: %1\$s"; // %1$s is the parse error
$lang['Emails.!error.include_attachments'] = "Apakah akan menyertakan lampiran? harus diatur ke 0 atau 1.";
?>