<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['EmailGroups.!error.action.length'] = "Panjang tindakan tidak boleh melebihi 64 karakter.";
$lang['EmailGroups.!error.notice_type.valid'] = "Jenis pemberitahuan harus diatur baik bcc atau kepada siapa.";
?>