<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Encryption.!error.private_key_passphrase.empty'] = "Masukkan private key passphrase baru";
$lang['Encryption.!error.confirm_new_passphrase.matches'] = "Passphrase baru tidak cocok.";
?>