<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['GatewayPayments.!error.gateway.exists'] = "Gateway tidak ada atau tidak diaktifkan.";
$lang['GatewayPayments.!error.transaction_id.exists'] = "Transaksi tidak dapat ditemukan untuk klien tersebut";
$lang['GatewayPayments.!error.contact_id.exists'] = "Kontak untuk klien tersebut tidak dapat ditemukan";
$lang['GatewayPayments.!error.type.instance'] = "Gateway tidak mendukung pembayaran dengan cara ini.";
$lang['GatewayPayments.!error.reference_id.update'] = "Gateway pembayaran tidak bisa memperbarui rekening pembayaran.";
$lang['GatewayPayments.!error.reference_id.remove'] = "Gateway pembayaran tidak bisa menghapus akun pembayaran.";
$lang['GatewayPayments.!error.gateway.error'] = "Gateway pembayaran kembal menemukan kesalahan saat memproses permintaan.";
?>