<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Invoices.getPricingPeriods.day'] = "Hari";
$lang['Invoices.getPricingPeriods.week'] = "Minggu";
$lang['Invoices.getPricingPeriods.month'] = "Bulan";
$lang['Invoices.getDeliveryMethods.interfax'] = "Interfax";
$lang['Invoices.getDeliveryMethods.postalmethods'] = "Metode Pengiriman";
$lang['Invoices.!error.invoice_id.exists'] = "ID faktur tidak sah.";
$lang['Invoices.!error.invoice_recur_id.exists'] = "ID faktur berulang tidak valid.";
$lang['Invoices.!error.delivery.empty'] = "Silakan masukkan metode pengiriman faktur.";
$lang['Invoices.!error.delivery.length'] = "metode pengiriman faktur panjangnya tidak boleh melebihi 32 karakter.";
$lang['Invoices.!error.id_value.valid'] = "Tidak dapat menentukan nilai ID faktur";
$lang['Invoices.!error.client_id.exists'] = "ID klien yang tidak valid.";
$lang['Invoices.!error.date_due.format'] = "Format tanggal jatuh tempo tidak valid.";
$lang['Invoices.!error.date_autodebit.format'] = "Tanggal jatuh tempo dalam format tanggal yang tidak valid.";
$lang['Invoices.!error.delivery.exists'] = "Metode pengiriman yang diberikan tidak ada.";
$lang['Invoices.!error.term.format'] = "Periode harus berupa angka";
$lang['Invoices.!error.term.bounds'] = "Periode harus antara 1 dan 65535.";
$lang['Invoices.!error.period.format'] = "Periode tidak valid.";
$lang['Invoices.!error.duration.format'] = "Durasi tidak valid.";
$lang['Invoices.!error.date_last_renewed.format'] = "Memperbaharui tanggal faktur berulang terakhir harus denga format tanggal yang valid.";
$lang['Invoices.!error.invoice_id.draft'] = "Faktur yang diberikan bukan draft faktur, dan karena itu tidak dapat dihapus.";
$lang['Invoices.!error.lines[][id].exists'] = "baris ID item tidak valid.";
$lang['Invoices.!error.lines[][qty].minimum'] = "Masukkan jumlah 1 atau lebih.";
$lang['Invoices.!error.lines[][amount].format'] = "Unit biaya harus berupa angka.";
$lang['Invoices.!error.lines[][tax].format'] = "Pajak item baris harus menjadi 'benar' atau 'salah'";
$lang['Invoices.!line_item.service_setup_fee_description'] = "Pemasangan %1\$s - %2\$s "; // %1$s is the name of the package, %2$s is the name of the service
$lang['Invoices.!line_item.coupon_line_item_description_amount'] = "Kupon %1\$s"; // %1$s is the coupon code
$lang['Invoices.!error.date_due.after_billed'] = "Tanggal jatuh tempo harus pada atau setelah tanggal ditagih.";
$lang['Invoices.!line_item.recurring_renew_description'] = "%1\$s (%2\$s - %3\$s)"; // %1$s is the line item description, %2$s is the invoice's renew date, %3$s is the invoice's next renew date
$lang['Invoices.status.active'] = "Aktif";
$lang['Invoices.status.void'] = "Batal";
$lang['Invoices.!line_item.service_renew_description'] = "%5\$s%1\$s - %2\$s (%3\$s - %4\$s)"; // %1$s is the name of the package, %2$s is the name of the service, %3$s is the service's renew date, %4$s is the service's next renew date, %5$s is the addon identifier set only for addon services
$lang['Invoices.status.proforma'] = "Secara proforma";
$lang['Invoices.types.proforma'] = "Secara proforma";
$lang['Invoices.!line_item.service_option_prorated_addition_description'] = "↳ Penambahan prorata dari %1\$s %2\$s (%3\$s - %4\$s)"; // %1$s is the service option label name, %2$s is the service option value, %3$s is the current date, %4$s is the service's next renew date
$lang['Invoices.!line_item.service_option_prorated_addition_description_onetime'] = "↳ Penambahan prorata dari  %1\$s %2\$s"; // %1$s is the service option label name, %2$s is the service option value
?>