<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Languages.!error.code.format'] = "Kode bahasa tidak diformat dengan benar.";
$lang['Languages.!error.code.unique'] = "kode bahasa tersebut sudah ada untuk perusahaan ini.";
$lang['Languages.!error.company_id.format'] = "ID perusahaan tampaknya tidak valid.";
$lang['Languages.!error.name.format'] = "Nama bahasa mungkin tidak kosong.";
?>