<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Logs.!error.company_id.exists'] = "ID perusahaan tidak valid.";
$lang['Logs.!error.from_address.empty'] = "Hilang dari alamat.";
$lang['Logs.!error.staff_id.empty'] = "ID staff belum ada";
$lang['Logs.!error.gateway_id.exists'] = "ID gatewaya tidak sah";
$lang['Logs.!error.direction.format'] = "Jenis arah tidak valid.";
$lang['Logs.!error.group.maxlength'] = "Panjang kelompok tidak boleh melebihi 8 karakter.";
$lang['Logs.!error.ip_address.empty'] = "Alamat IP tidak ada.";
$lang['Logs.!error.last_name.empty'] = "Nama terakhir tidak boleh kosong.";
$lang['Logs.!error.run_id.exists'] = "Tugas ID cron tidak valid.";
$lang['Logs.!error.event.maxlength'] = "Panjang kegiatan tidak dapat melebihi 32 karakter.";
$lang['Logs.!error.group.unique'] = "Tugas cron ID dan kelompok telah diambil.";
$lang['Logs.!error.group.betweenlength'] = "Panjang grup harus antara 1 hingga 32 karakter.";
$lang['Logs.!error.start_date.format'] = "Format tanggal mulai tidak valid.";
$lang['Logs.!error.end_date.format'] = "Format tanggal akhir tidak valid.";
$lang['Logs.!error.user_log_exists.empty'] = "Pengguna di alamat IP yang diberikan tidak ada.";
$lang['Logs.!error.result.format'] = "Hasil Login harus 'sukses' atau 'gagal'.";
?>