<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ModuleManager.!error.name.valid'] = "Nama tidak valid.";
$lang['ModuleManager.!error.version.valid'] = "Versi tidak valid.";
$lang['ModuleManager.!error.name.empty'] = "Anda harus menentukan nama untuk grup.";
$lang['ModuleManager.!error.module_rows[].valid'] = "Satu atau lebih dari baris yang ditentukan tidak termasuk modul ini.";
$lang['ModuleManager.!error.module_row_id.assigned_package'] = "Baris tidak dapat dihapus karena itu milik satu atau lebih paket.";
$lang['ModuleManager.!error.module_row_id.assigned_service'] = "Baris itu tidak dapat dihapus karena itu milik satu atau beberapa layanan.";
$lang['ModuleManager.!error.module_id.assigned_package'] = "Modul ini tidak dapat dihapus karena digunakan oleh satu atau lebih paket aktif";
?>