<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Navigation.getprimary.nav_home'] = "Home";
$lang['Navigation.getprimary.nav_billing_invoices'] = "Faktur";
$lang['Navigation.getprimary.nav_billing_transactions'] = "Transaksi";
$lang['Navigation.getprimary.nav_billing_services'] = "Jasa";
$lang['Navigation.getprimary.nav_billing_reports'] = "Laporan";
$lang['Navigation.getprimary.nav_tools'] = "Alat";
$lang['Navigation.getprimary.nav_tools_currency'] = "Konversi Mata Uang";
$lang['Navigation.getprimary.nav_settings_system'] = "Sistem";
$lang['Navigation.getcompany.nav_general'] = "Umum";
$lang['Navigation.getcompany.nav_general_localization'] = "Lokalisasi";
$lang['Navigation.getcompany.nav_general_encryption'] = "Enkripsi";
$lang['Navigation.getcompany.nav_general_contacttypes'] = "Jenis kontak";
$lang['Navigation.getcompany.nav_automation'] = "Otomatisasi";
$lang['Navigation.getcompany.nav_billing_invoices'] = "Pilihan Faktur dan Biaya ";
$lang['Navigation.getcompany.nav_billing_deliverymethods'] = "Pengiriman Tagihan";
$lang['Navigation.getcompany.nav_billing_acceptedtypes'] = "Jenis Pembayaraan Yang Diterima";
$lang['Navigation.getcompany.nav_taxes'] = "Pajak";
$lang['Navigation.getcompany.nav_taxes_basictax'] = "Pengaturan Pajak dasar";
$lang['Navigation.getcompany.nav_emails_mail'] = "Pengaturan Mail";
$lang['Navigation.getcompany.nav_emails_templates'] = "Email Template";
$lang['Navigation.getcompany.nav_emails_signatures'] = "Signature";
$lang['Navigation.getcompany.nav_plugins'] = "Plugin";
$lang['Navigation.getsystem.nav_general_basic'] = "Setting Dasar";
$lang['Navigation.getsystem.nav_general_geoip'] = "Pengaturan GeoIP";
$lang['Navigation.getsystem.nav_general_maintenance'] = "Pemeliharaan";
$lang['Navigation.getsystem.nav_general_license'] = "lisensi Key";
$lang['Navigation.getsystem.nav_automation'] = "Otomatisasi";
$lang['Navigation.getsystem.nav_backup_ftp'] = "FTP Mode Aman";
$lang['Navigation.getsystem.nav_backup_index'] = "On Demand";
$lang['Navigation.getsystem.nav_staff'] = "Staf";
$lang['Navigation.getsystem.nav_staff_manage'] = "Mengelola Staf";
$lang['Navigation.getsystem.nav_staff_groups'] = "Staf Grup";
$lang['Navigation.getsystem.nav_api'] = "API Access";
$lang['Navigation.getsystem.nav_upgrade'] = "Pilihan Upgrade";
$lang['Navigation.getsystem.nav_help_notes'] = "Catatan Rilis";
$lang['Navigation.getsystem.nav_help_about'] = "Tentang Blesta";
$lang['Navigation.getprimary.nav_billing_printqueue'] = "Antrian Cetak";
$lang['Navigation.getprimaryclient.nav_paymentaccounts'] = "Account Pembayaran";
$lang['Navigation.getsearchoptions.smart'] = "Smart Search";
$lang['Navigation.getsearchoptions.clients'] = "Cari Klien";
$lang['Navigation.getsearchoptions.transactions'] = "Pencarian Transaksi";
$lang['Navigation.getprimaryclient.nav_contacts_add'] = "Tambahkan kontak";
$lang['Navigation.getcompany.nav_lookandfeel'] = "Tampilan";
$lang['Navigation.getcompany.nav_lookandfeel_customize'] = "Menyesuaikan";
?>