<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['NonmerchantGateway.!error.invalid'] = "Respons pembayaran yang error atau tidak sah telah diterima";
$lang['NonmerchantGateway.!error.transaction_not_found'] = "Transaksi tidak valid atau tidak lagi tersedia untuk memproses tindakan itu.";
$lang['NonmerchantGateway.!error.unsupported'] = "gateway tidak mendukung tindakan tersebut";
$lang['NonmerchantGateway.!error.general'] = "Terjadi kesalahan saat memproses permintaan dengan gateway.";
?>