<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PackageOptions.!error.company_id.exists'] = "ID perusahaan tidak valid.";
$lang['PackageOptions.!error.label.empty'] = "Masukkan label.";
$lang['PackageOptions.!error.label.length'] = "Label tidak boleh melebihi 128 karakter.";
$lang['PackageOptions.!error.name.length'] = "Nama tidak boleh melebihi 128 karakter.";
$lang['PackageOptions.!error.values[][min].valid'] = "Nilai batas minimum hanya dapat ditetapkan untuk jenis kuantitas, dan harus menjadi nilai 0 atau lebih besar.";
$lang['PackageOptions.!error.values[][name].empty'] = "Silakan masukkan nama untuk nilai pilihan.";
$lang['PackageOptions.!error.values[][name].length'] = "Nama nilai opsi tidak boleh melebihi 128 karakter.";
$lang['PackageOptions.!error.option_id.exists'] = "ID pilihan paket yang tidak valid.";
$lang['PackageOptions.!error.values[][pricing][][term].length'] = "Panjang periode tidak boleh melebihi 5 karakter.";
$lang['PackageOptions.!error.values[][pricing][][price].format'] = "Harga harus berupa angka.";
$lang['PackageOptions.gettypes.quantity'] = "Jumlah";
$lang['PackageOptions.gettypes.radio'] = "Radio";
$lang['PackageOptions.getfields.label_quantity_setup'] = "x %1\$s %2\$s + %3\$s setup"; // %1$s is the option value, %2$s is the option price, %3$s is the setup fee
$lang['PackageOptions.getfields.label_radio_setup'] = "%1\$s (%2\$s + %3\$s setup)"; // %1$s is the option value, %2$s is the option price, %3$s is the setup fee
$lang['PackageOptions.getfields.label_select_setup'] = "%1\$s (%2\$s + %3\$s setup)"; // %1$s is the option value, %2$s is the option price, %3$s is the setup fee
$lang['PackageOptions.getfields.label_checkbox'] = "%1\$s (%2\$s)"; // %1$s is the option value, %2$s is the option price
$lang['PackageOptions.gettypes.text'] = "Teks";
?>