<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Packages.!error.taxable.length'] = "Panjang kena pajak tidak boleh melebihi 1 karakter.";
$lang['Packages.!error.groups[].exists'] = "ID grup paket tidak valid.";
$lang['Packages.!error.groups[].valid'] = "Kelompok paket yang dipilih bukan milik perusahaan yang diberikan.";
$lang['Packages.getPricingPeriods.day'] = "Hari";
$lang['Packages.getPricingPeriods.week'] = "Minggu";
$lang['Packages.getPricingPeriods.month'] = "Bulan";
$lang['Packages.getPricingPeriods.onetime'] = "Satu kali";
$lang['Packages.!error.pricing[][term].format'] = "Term harus berupa angka.";
$lang['Packages.!error.pricing[][term].length'] = "Panjang periode tidak boleh melebihi 5 karakter.";
$lang['Packages.!error.pricing[][period].format'] = "Jenis periode tidak valid.";
$lang['Packages.!error.pricing[][price].format'] = "Harga harus berupa angka.";
$lang['Packages.!error.pricing[][currency].format'] = "Kode mata uang harus 3 karakter";
$lang['Packages.getPricingPeriods.day_plural'] = "Hari";
$lang['Packages.getPricingPeriods.month_plural'] = "Bulan";
$lang['Packages.getPricingPeriods.onetime_plural'] = "Satu kali";
$lang['Packages.!error.company_id.exists'] = "Perusahaan yang diberikan tidak valid";
$lang['Packages.!error.module_id.exists'] = "Modul tidak valid";
$lang['Packages.!error.pricing[][term].valid'] = "Istilah harus lebih besar dari 0.";
$lang['Packages.!error.option_groups[].valid'] = "Kelompok pilihan paket yang dikonfigurasi tidak valid";
$lang['Packages.!error.single_term.valid'] = "Istilah tunggal harus 1 atau 0.";
$lang['Packages.!error.pricing[][term].deletable'] = "Periode tidak dapat dihapus karena digunakan oleh satu atau lebih layanan.";
$lang['Packages.!error.prorata_day.format'] = "Hari pro rata harus antara 1 dan 28.";
$lang['Packages.!error.prorata_cutoff.format'] = " pro rata cutoff day harus antara 1 dan 28";
?>