<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PluginManager.!error.dir.empty'] = "Silakan masuk ke direktori Plugin.";
$lang['PluginManager.!error.dir.length'] = "Panjang direktori Plugin tidak boleh melebihi 64 karakter.";
$lang['PluginManager.!error.company_id.exists'] = "ID perusahaan tidak valid.";
$lang['PluginManager.!error.name.empty'] = "Masukkan nama Plugin.";
$lang['PluginManager.!error.event.length'] = "Panjang acara tidak boleh melebihi 32 karakter.";
$lang['PluginManager.!error.callback.empty'] = "Cukup masukkan callback.";
$lang['PluginManager.!error.action.empty'] = "masukkan tindakan.";
$lang['PluginManager.!error.uri.empty'] = "Masukkan URI.";
$lang['PluginManager.!error.name.action_empty'] = "Silakan masukkan nama tindakan.";
?>