<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ReportManager.!error.type.valid'] = "Silakan pilih jenis laporan yang valid.";
$lang['ReportManager.getformats.csv'] = "CSV";
$lang['ReportManager.!error.query.valid'] = "Hanya satu permintaan diperbolehkan, dan itu harus menjadi query SELECT/permintaan terpilih";
$lang['ReportManager.reportfieldtypes.select'] = "Pilih";
?>