<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ServiceChanges.!error.service_id.exists'] = "ID layanan tidak valid.";
$lang['ServiceChanges.!error.status.valid'] = "Silakan pilih status yang sah.";
$lang['ServiceChanges.status.pending'] = "Pending";
$lang['ServiceChanges.status.completed'] = "Selesai";
?>