<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Services.!error.key.empty'] = "Kunci bidang servis tidak boleh kosong.";
$lang['Services.!error.encrypted.format'] = "Format tidak valid untuk dienkripsi.";
$lang['Services.!error.parent_service_id.exists'] = "ID layanan induk tidak valid.";
$lang['Services.!error.parent_service_id.parent'] = "ID layanan pokok/parent sudah ada sebagai sub/child dari layanan lain.";
$lang['Services.!error.id_format.empty'] = "Tidak ada ID Format ditetapkan untuk faktur.";
$lang['Services.!error.id_format.length'] = "format ID untuk faktur tidak boleh melebihi 64 karakter.";
$lang['Services.!error.id_value.valid'] = "Tidak dapat menentukan nilai ID faktur ";
$lang['Services.!error.module_row_id.exists'] = "Baris ID modul tidak valid.";
$lang['Services.!error.qty.format'] = "Jumlah harus berupa angka.";
$lang['Services.!error.qty.length'] = "Jumlah panjang tidak boleh melebihi 10 karakter.";
$lang['Services.!error.status.format'] = "Status tidak valid.";
$lang['Services.!error.date_suspended.format'] = "Format tanggal suspend tidak benar";
$lang['Services.!error.use_module.format'] = "Pengguaan format modul yang tidak valid";
$lang['Services.!error.fields[][key].empty'] = "Key kosong dari bidang layanan.";
$lang['Services.!error.fields[][value].empty'] = "Sebuah nilai kosong dari bidang layanan.";
$lang['Services.getStatusTypes.pending'] = "Tunda";
$lang['Services.getStatusTypes.suspended'] = "Ditangguhkan";
$lang['Services.!error.invoice_method.valid'] = "Anda harus memilih metode faktur valid.";
$lang['Services.getActions.schedule_cancel'] = "Jadwal Pembatalan";
$lang['Services.!error.client_id.exists'] = "Klien tidak ada.";
$lang['Services.!error.date_renews.valid'] = "Tanggaal renew/memperbarui harus lebih besar dari yang terakhir tanggal memperbaharui %1\$s."; // %1$s is the last renew date
$lang['Services.getStatusTypes.in_review'] = "Dalam Ulasan";
$lang['Services.!error.qty.available'] = "Limit Kuantitas tercapai. Jika memungkinkan, silahkan pilih jumlah yang lebih kecil.";
$lang['Services.!error.status.valid'] = "Hanya layanan yang pending atau sedang dalam review dapat dihapus.";
$lang['Services.!error.client_id.allowed'] = "Klien tidak dapat mengakses paket tersebut";
$lang['Services.!error.configoptions.valid'] = "Salah satu pilihan dikonfigurasi terpilih tidak berlaku untuk layanan.";
$lang['Services.!error.pricing_id.overrides'] = "Periode paket tidak dapat diubah bila menimpa harga yang telah ditetapkan.";
$lang['Services.!error.override_price.format'] = "timpa harga harus berupa angka.";
$lang['Services.!error.override_price.override'] = "Kedua harga dan mata uang harus diatur untuk mengesampingkan harga saat ini.";
$lang['Services.!error.override_currency.format'] = "Silakan pilih mata uang yang valid.";
$lang['Services.!error.pricing_id.exists'] = "Silakan pilih periode yang valid.";
?>