<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Staff.!error.user_id.exists'] = "ID pengguna yang tidak valid.";
$lang['Staff.!error.user_id.unique'] = "Staf dengan ID pengguna %1\$s sudah diambil."; // %1$s is the staff user ID number
$lang['Staff.!error.first_name.empty'] = "Masukkan nama pertama.";
$lang['Staff.!error.last_name.empty'] = "Masukkan nama terakhir.";
$lang['Staff.!error.email.format'] = "Silakan masukkan alamat email yang valid.";
$lang['Staff.!error.company_id.format'] = "ID perusahaan haruslah berupa angka.";
$lang['Staff.!error.title.empty'] = "Silakan masukkan judul.";
$lang['Staff.!error.order.length'] = "Panjang urutan tidak boleh melebihi 5 karakter.";
$lang['Staff.!error.staff_group_id.exists'] = "ID kelompok staf tidak valid.";
$lang['Staff.!error.staff_id.exists'] = "ID staf tidak valid.";
?>