<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['StaffGroups.!error.name.length'] = "panjang Nama tidak boleh melebihi 64 karakter.";
$lang['StaffGroups.!error.no_company_id.exists'] = "Tidak dapat masuk, Tidak ada pada perusahaan manapun";
$lang['StaffGroups.permission_group.packages'] = "Paket";
$lang['StaffGroups.permission_group.search'] = "Cari";
$lang['StaffGroups.permission_group.settings'] = "Pengaturan";
$lang['StaffGroups.permissions.admin_clients_add'] = "Tambahkan Client";
$lang['StaffGroups.permissions.admin_clients_viewinvoice'] = "Perlihatkan Faktur";
$lang['StaffGroups.permissions.admin_clients_editinvoice'] = "Mengedit Faktur";
$lang['StaffGroups.permissions.admin_clients_editrecurinvoice'] = "Edit Faktur Berulang";
$lang['StaffGroups.permissions.admin_clients_edittransaction'] = "edit Transaksi";
$lang['StaffGroups.permissions.admin_clients_addservice'] = "Tambahkan Layanan";
$lang['StaffGroups.permissions.admin_clients_deleteservice'] = "Hapus Layanan";
$lang['StaffGroups.permissions.admin_clients_addcontact'] = "Tambah Kontak";
$lang['StaffGroups.permissions.admin_clients_editcontact'] = "Edit kontak";
$lang['StaffGroups.permissions.admin_clients_deletecontact'] = "Hapus Kontak";
$lang['StaffGroups.permissions.admin_clients_quickupdate'] = "Pembaruan Cepat";
$lang['StaffGroups.permissions.admin_clients_accounts'] = "Lihat Akun Pembayaran";
$lang['StaffGroups.permissions.admin_clients_addccaccount'] = "Tambahkan Rekening Pembayaran Kartu Kredit ";
$lang['StaffGroups.permissions.admin_clients_addachaccount'] = "Tambahkan Akun Pembayaran ACH";
$lang['StaffGroups.permissions.admin_clients_editccaccount'] = "Edit Rekening Pembayaran dengan Kartu Kredit ";
$lang['StaffGroups.permissions.admin_clients_editachaccount'] = "Edit Akun Pembayaran ACH";
$lang['StaffGroups.permissions.admin_clients_deleteccaccount'] = "Hapus Rekening Pembayaran Kartu Kredit";
$lang['StaffGroups.permissions.admin_clients_deleteachaccount'] = "Hapus Akun Pembayaran ACH";
$lang['StaffGroups.permissions.admin_clients_addnote'] = "Tambah Catatan";
$lang['StaffGroups.permissions.admin_clients_packages'] = "Atur Paket";
$lang['StaffGroups.permissions.admin_clients_emails'] = "Lihat maillog";
$lang['StaffGroups.permissions.admin_clients_merge'] = "Gabungkan Klien";
$lang['StaffGroups.permissions.admin_clients_delete'] = "Hapus Client";
$lang['StaffGroups.permissions.admin_billing_invoices'] = "Daftar Tagihan";
$lang['StaffGroups.permissions.admin_billing_services'] = "Daftar Layanan";
$lang['StaffGroups.permissions.admin_billing_transactions'] = "Daftar Transaksi ";
$lang['StaffGroups.permissions.admin_tools_convert_currency'] = "Konversi Mata Uang";
$lang['StaffGroups.permissions.admin_tools_logs'] = "Log";
$lang['StaffGroups.permissions.admin_packages_add'] = "Tambahkan Paket";
$lang['StaffGroups.permissions.admin_packages_groups'] = "Lihat Grup Paket";
$lang['StaffGroups.permissions.admin_settings_company'] = "Pengaturan perusahaan";
$lang['StaffGroups.permissions.admin_company_general_localization'] = "Lokalisasi";
$lang['StaffGroups.permissions.admin_company_general_international'] = "Internasionalisasi";
$lang['StaffGroups.permissions.admin_company_billing_invoices'] = "Faktur dan ganti Pilihan";
$lang['StaffGroups.permissions.admin_company_billing_notices'] = "Pemberitahuan Pembayaran Jatuh Tempo";
$lang['StaffGroups.permissions.admin_company_modules_uninstall'] = "Uninstall Module";
$lang['StaffGroups.permissions.admin_company_gateways'] = "Gateway Pembayaran";
$lang['StaffGroups.permissions.admin_company_gateways_manage'] = "Mengelola Gateway";
$lang['StaffGroups.permissions.admin_company_gateways_install'] = "Instal Gateway";
$lang['StaffGroups.permissions.admin_company_gateways_upgrade'] = "Upgrade Gateway";
$lang['StaffGroups.permissions.admin_company_emails_mail'] = "Pengaturan Mail / Surat";
$lang['StaffGroups.permissions.admin_company_emails_signatures'] = "Signatures Email";
$lang['StaffGroups.permissions.admin_company_plugins_manage'] = "Mengelola Plugin";
$lang['StaffGroups.permissions.admin_company_plugins_install'] = "Install Plugin";
$lang['StaffGroups.permissions.admin_company_groups'] = "Grup klien";
$lang['StaffGroups.permissions.admin_settings_system'] = "Pengaturan sistem";
$lang['StaffGroups.permissions.admin_system_general_geoip'] = "Pengaturan GeoIP";
$lang['StaffGroups.permissions.admin_system_general_license'] = "License Key";
$lang['StaffGroups.permissions.admin_system_automation'] = "Otomatisasi";
$lang['StaffGroups.permissions.admin_system_companies'] = "Perusahaan";
$lang['StaffGroups.permissions.admin_system_staff_manage'] = "Mengelola Staf";
$lang['StaffGroups.permissions.admin_system_staff_groups'] = "Grup Staf";
$lang['StaffGroups.permissions.admin_system_api'] = "API Access";
$lang['StaffGroups.permissions.admin_system_upgrade'] = "Pilihan Upgrade";
$lang['StaffGroups.permissions.admin_system_help'] = "Bantuan";
$lang['StaffGroups.permissions.admin_system_marketplace'] = "Marketplace";
$lang['StaffGroups.permission_group.home'] = "Home";
$lang['StaffGroups.permissions.admin_main_calendar'] = "Kalender";
$lang['StaffGroups.permissions.admin_clients_loginasclient'] = "Login sebagai Client";
$lang['StaffGroups.permissions.admin_billing_printqueue'] = "Antrian Cetak ";
$lang['StaffGroups.permissions.admin_company_general_addcontacttype'] = "Tambah Tipe Kontak";
$lang['StaffGroups.permissions.admin_company_general_editcontacttype'] = "Edit Jenis Kontak";
$lang['StaffGroups.permissions.admin_company_general_deletecontacttype'] = "Hapus Jenis Kontak ";
$lang['StaffGroups.permissions.admin_company_billing_acceptedtypes'] = "Jenis Pembayaran Yang Diterima";
$lang['StaffGroups.permissions.admin_system_general_paymenttypes'] = "Jenis pembayaran";
$lang['StaffGroups.permissions.admin_system_general_deletetype'] = "Hapus Jenis Pembayaran";
$lang['StaffGroups.permissions.admin_packages_addgroup'] = "Tambahkan Grup";
$lang['StaffGroups.permissions.admin_package_options'] = "Pilihan dikonfigurasi";
$lang['StaffGroups.permissions.admin_company_general_addtheme'] = "Tambahkan tema";
$lang['StaffGroups.permissions.admin_company_general_deletetheme'] = "Hapus Tema";
$lang['StaffGroups.permissions.admin_company_billing_deletecoupon'] = "Hapus Kupon";
$lang['StaffGroups.permissions.admin_company_taxes'] = "Pajak";
$lang['StaffGroups.permissions.admin_company_emails_addsignature'] = "Tambahkan Email Signature";
$lang['StaffGroups.permissions.admin_company_emails_editsignature'] = "Mengedit Signature Email ";
$lang['StaffGroups.permissions.admin_company_currencies'] = "Mata Uang";
$lang['StaffGroups.permissions.admin_system_backup'] = "Backups";
$lang['StaffGroups.permissions.admin_system_staff_status'] = "Status staf";
$lang['StaffGroups.permissions.admin_system_staff_editgroup'] = "Edit Grup Staf";
$lang['StaffGroups.permissions.admin_system_staff_deletegroup'] = "Hapus Grup Staf ";
$lang['StaffGroups.permissions.admin_company_automation'] = "Otomatisasi";
$lang['StaffGroups.permissions.admin_clients_recordpayment'] = "Rekam Pembayaran";
?>