<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['States.!error.code.format'] = "Kode negara harus alpha-numerik seperti yang didefinisikan dalam ISO 3166-2.";
$lang['States.!error.country_alpha2.in_use'] = "Negara alpha2 kode %1\$s dan kode subdivisi %2\$s sudah diambil."; // %1$s is the alpha2 country code, %2$s is the state code
?>