<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SystemRequirements.!error.php.minimum'] = "versi PHP %1\$s atau lebih diperlukan. versi milik anda %2\$s."; // %1$s is the minimum version of PHP (i.e. 5.1.3), %2$s is the current version
$lang['SystemRequirements.!warning.mcrypt.recommended'] = "Ekstensi mcrypt direkomendasikan untuk kinerja yang lebih baik.";
$lang['SystemRequirements.!warning.gmp.recommended'] = "gmp extension sangat dianjurkan untuk performa yang lebih baik.";
$lang['SystemRequirements.!warning.cache_writable.recommended'] = "Untuk kinerja yang lebih baik memastikan bahwa %1\$s adalah bisa ditulis oleh webserver."; // %1$s is the absolute path to the cache directory
$lang['SystemRequirements.!warning.imap.recommended'] = "imap extension diperlukan untuk mengirim dan menerima email melalui SMTP dan IMAP.";
$lang['SystemRequirements.!warning.mbstring.recommended'] = "Ekstensi mbstring diperlukan oleh beberapa fitur opsional.";
$lang['SystemRequirements.!warning.gd.recommended'] = "Ektensien gd direkomendasi untuk gambar yang lebih baik ketika membuat PDF";
?>