<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Themes.!error.id.exists'] = "Tema yang Anda pilih tidak ada.";
$lang['Themes.!error.company_id.exists'] = "ID perusahaan tidak valid.";
$lang['Themes.!error.name.empty'] = "Masukkan nama tema.";
$lang['Themes.!error.name.length'] = "Nama tema tidak boleh melebihi 64 karakter.";
$lang['Themes.type.admin'] = "Staf";
$lang['Themes.type.client'] = "Klien";
?>