<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Transactions.!error.client_id.exists'] = "ID klien yang tidak valid.";
$lang['Transactions.!error.amount.format'] = "Jumlah harus berupa angka.";
$lang['Transactions.!error.currency.length'] = "Mata uang harus 3 karakter.";
$lang['Transactions.!error.type.format'] = "Jenis transaksi yang tidak valid.";
$lang['Transactions.!error.gateway_id.exists'] = "ID gatewayaa tidak sah";
$lang['Transactions.!error.status.format'] = "Status transaksi tidak valid.";
$lang['Transactions.!error.date.format'] = "Tanggal yang diterapkan tidak valid.";
$lang['Transactions.!error.name.length'] = "Panjang nama tidak boleh melebihi 32 karakter.";
$lang['Transactions.!error.is_lang.format'] = "is_lang haruslah angka.";
$lang['Transactions.!error.type_id.exists'] = "jenis ID  transaksi tidak valid.";
$lang['Transactions.types.other'] = "Yang Lainnya";
$lang['Transactions.status.declined'] = "Ditolak";
$lang['Transactions.status.void'] = "Batal";
$lang['Transactions.!error.currency.missing'] = "Silakan set mata uang.";
$lang['Transactions.!error.currency.mismatch'] = "Mata uang yang diberikan tidak sesuai dengan salah satu tagihan yang terkait";
?>