<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Users.!error.current_password.matches'] = "Kata sandi tidak valid.";
$lang['Users.!error.new_password.matches'] = "Password tidak cocok.";
$lang['Users.!error.two_factor_mode.format'] = "Mode dua faktor yang tidak valid.";
$lang['Users.!error.otp.auth'] = "Satu kali password yang telah dimasukkan tidak benar";
$lang['Users.!error.user_id.exists'] = "ID pengguna yang tidak valid.";
$lang['Users.!error.username.attempts'] = "Terdeteksi !! terlalu banyak upaya login gagal ";
$lang['Users.!error.clients.exist'] = "Pengguna tidak dapat dihapus dikarenakan terdapat setidaknya satu klien yang ditempatkan pada pengguna.";
$lang['Users.!error.two_factor_key.format'] = "Kunci dua faktor yang tidak valid.";
?>