<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMain.index.statistic.revenue_month'] = "Pendapatan Bulan ini";
$lang['AdminMain.index.statistic.invoiced_month'] = "Tagihan Bulan ini";
$lang['AdminMain.index.statistic.balance_outstanding'] = "Saldo luar biasa";
$lang['AdminMain.index.statistic.balance_overdue'] = "Saldo terlambat";
$lang['AdminMain.index.statistic.scheduled_cancelation'] = "Pembatalan terjadwal";
$lang['AdminMain.index.statistic.services_active'] = "Layanan Aktif";
$lang['AdminMain.index.statistic.services_added_today'] = "Layanan Ditambahkan Hari ini";
$lang['AdminMain.index.statistic.services_canceled_today'] = "Layanan Dibatalkan Hari ini";
$lang['AdminMain.settings.text_options'] = "Periksa pilihan yang akan muncul pada Ikhtisar Penagihan.";
$lang['AdminMain.settings.heading_statistics'] = "Statistik";
$lang['AdminMain.settings.heading_graphs'] = "Grafik";
$lang['AdminMain.settings.heading_graph_settings'] = "Pengaturan Grafik";
$lang['AdminMain.settings.revenue_month'] = "Pendapatan Bulan ini";
$lang['AdminMain.settings.invoiced_month'] = "Tagihan Bulan ini";
$lang['AdminMain.settings.balance_outstanding'] = "Saldo luar biasa";
$lang['AdminMain.settings.scheduled_cancelation'] = "Pembatalan terjadwal";
$lang['AdminMain.settings.services_added_today'] = "Layanan Ditambahkan Hari ini";
$lang['AdminMain.settings.graph_invoiced'] = "Grafik Jumlah tagihan";
$lang['AdminMain.settings.show_legend'] = "Tampilkan Legend di Grafik";
$lang['AdminMain.settings.submit_settings'] = "Perbarui Pengaturan";
$lang['AdminMain.settings.submit_cancel'] = "Kembali ke Ikhtisar";
$lang['AdminMain.date_range.days'] = "hari-hari";
$lang['AdminMain.graph_line_name.total'] = "Total";
$lang['AdminMain.graph_line_name.credit'] = "Kartu Kredit";
$lang['AdminMain.graph_line_name.ach'] = "ACH";
$lang['AdminMain.graph_line_name.other'] = "Lain";
$lang['AdminMain.index.statistic.revenue_year'] = "Pendapatan Tahun ini";
$lang['AdminMain.settings.revenue_year'] = "Pendapatan Tahun ini";
$lang['AdminMain.settings.graph_revenue_year'] = "Grafik Pendapatan (Tahun ke Tanggal)";
$lang['AdminMain.graph_name.graph_revenue_year'] = "Pendapatan (Tahun ke Tanggal)";
$lang['AdminMain.settings.graph_revenue'] = "Grafik Pendapatan (Range)";
$lang['AdminMain.settings.credits_month'] = "Kredit Bulan ini";
?>