<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['DirectAdmin.!error.host_name.format'] = "Host Name tampaknya tidak valid.";
$lang['DirectAdmin.!error.user_name.empty'] = "Anda harus memasukkan User Name.";
$lang['DirectAdmin.!error.password.format'] = "Anda harus memasukkan Password.";
$lang['DirectAdmin.!error.use_ssl.format'] = "Gunakan SSL harus benar atau salah.";
$lang['DirectAdmin.!error.account_limit.valid'] = "Batas akun harus dibiarkan kosong (untuk akun unlimited) atau mengatur untuk beberapa nilai integer.";
$lang['DirectAdmin.!error.meta[type].format'] = "Jenis akun harus pengguna atau reseller.";
$lang['DirectAdmin.!error.meta[package].empty'] = "Sebuah paket DirectAdmin diperlukan.";
$lang['DirectAdmin.!error.direct_admin_username.length'] = "Username harus antara 4 dan 8 karakter.";
$lang['DirectAdmin.!error.direct_admin_password.format'] = "Password hanya dapat berisi karakter ASCII.";
$lang['DirectAdmin.!error.direct_admin_password.length'] = "Password harus minimal 5 karakter.";
$lang['DirectAdmin.module_group'] = "Kelompok Server";
$lang['DirectAdmin.servers.no_results'] = "Tidak ada server.";
$lang['DirectAdmin.server_groups.no_results'] = "Tidak ada kelompok server";
$lang['DirectAdmin.service_field.username'] = "Nama Pengguna";
$lang['DirectAdmin.service_field.password'] = "Kata sandi";
$lang['DirectAdmin.service_field.email'] = "Email";
$lang['DirectAdmin.service_info.username'] = "Nama pengguna";
$lang['DirectAdmin.service_info.server'] = "Server";
$lang['DirectAdmin.service_info.option_login'] = "Masuk";
$lang['DirectAdmin.package_fields.type_reseller'] = "Reseller";
$lang['DirectAdmin.package_fields.ip_assign'] = "Menetapkan";
$lang['DirectAdmin.add_module_row'] = "Tambahkan Server";
$lang['DirectAdmin.add_module_group'] = "Tambahkan Kelompok Server";
$lang['DirectAdmin.manage.module_rows_heading.host_name'] = "Host Name";
$lang['DirectAdmin.manage.module_rows_heading.accounts'] = "Akun";
$lang['DirectAdmin.manage.module_rows_heading.options'] = "Pilihan";
$lang['DirectAdmin.manage.module_groups_heading.name'] = "Nama kelompok";
$lang['DirectAdmin.manage.module_groups_heading.servers'] = "Hitungan Server ";
$lang['DirectAdmin.manage.module_rows.count'] = "%1\$s / %2\$s"; // %1$s is the current number of accounts, %2$s is the total number of accounts available
$lang['DirectAdmin.manage.module_rows.edit'] = "Mengedit";
$lang['DirectAdmin.manage.module_groups.edit'] = "Sunting";
$lang['DirectAdmin.manage.module_rows.delete'] = "Hapus";
$lang['DirectAdmin.manage.module_groups.delete'] = "Hapus";
$lang['DirectAdmin.manage.module_groups.confirm_delete'] = "Apakah Anda yakin ingin menghapus kelompok server ini?";
$lang['DirectAdmin.row_meta.password'] = "Sandi";
$lang['DirectAdmin.row_meta.use_ssl'] = "Gunakan SSL saat menghubungkan ke API (dianjurkan)";
$lang['DirectAdmin.row_meta.account_limit'] = "Batas akun";
$lang['DirectAdmin.add_row.box_title'] = "Tambahkan DirectAdmin Server";
$lang['DirectAdmin.add_row.basic_title'] = "Pengaturan Dasar";
$lang['DirectAdmin.add_row.name_server_col'] = "Nama Server";
$lang['DirectAdmin.add_row.remove_name_server'] = "Hapus";
$lang['DirectAdmin.add_row.add_btn'] = "Tambahkan Server";
$lang['DirectAdmin.edit_row.box_title'] = "Sunting DirectAdmin Server";
$lang['DirectAdmin.edit_row.name_servers_title'] = "Nama Server";
$lang['DirectAdmin.edit_row.name_server_host_col'] = "Hostname";
$lang['DirectAdmin.edit_row.remove_name_server'] = "hapus";
$lang['DirectAdmin.edit_row.notes_title'] = "Catatan";
$lang['DirectAdmin.edit_row.add_btn'] = "Edit Server";
$lang['DirectAdmin.tab_client_stats.info_title'] = "Informasi";
?>