<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Skrill.name'] = "Skrill";
$lang['Skrill.secret_word'] = "Kata rahasia";
$lang['Skrill.merchant_id'] = "Merchant ID";
$lang['Skrill.secret_word_note'] = "Masukkan Skrill account Secret Word";
$lang['Skrill.user_email_note'] = "Masukkan alamat email akun Skrill Anda.";
$lang['Skrill.merchant_id_note'] = "Masukkan account ID merchant Skrill Anda.";
$lang['Skrill.mqi_note'] = "Masukkan MQI API password dari akun Skrill anda.";
$lang['Skrill.buildprocess.submit'] = "Bayar dengan Skrill";
$lang['Skrill.!error.user_email.valid'] = "Silakan masukkan alamat email yang valid.";
?>