<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['DefaultInvoice.name'] = "default";
$lang['DefaultInvoice.page_of'] = "Halaman %1\$s of %2\$s"; // %1$s is the current page number, %2$s is the total number of pages
$lang['DefaultInvoice.terms_heading'] = "Persyaratan";
$lang['DefaultInvoice.type_draft'] = "FAKTUR - DRAFT";
$lang['DefaultInvoice.tax_id'] = "ID pajak :";
$lang['DefaultInvoice.date_due'] = "Batas tanggal terakhir:";
$lang['DefaultInvoice.tax_heading'] = "%1\$s (%2\$s%%)"; // %1$s is the tax name, %2$s is the tax rate, %% escapes the percent (%) sign so it can be displayed
$lang['DefaultInvoice.total_heading'] = "Total";
$lang['DefaultInvoice.lines_description'] = "Deskripsi";
$lang['DefaultInvoice.lines_unit_price'] = "Harga per unit";
$lang['DefaultInvoice.client_tax_id'] = "ID Pajak Pelanggan /VATIN";
$lang['DefaultInvoice.type_proforma'] = "FAKTUR PRO FORMA ";
$lang['DefaultInvoice.payments_transaction_id'] = "Nomor Transaksi";
$lang['DefaultInvoice.payments_applied_amount'] = "Jumlah Diterapkan";
$lang['DefaultInvoice.proforma_id_code'] = "Nomor Pro Forma:";
?>