<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Interworx.name'] = "Interworx";
$lang['Interworx.module_row'] = "Server";
$lang['Interworx.tab_stats'] = "Statistika";
$lang['Interworx.add_module_row'] = "Tambahkan Server";
$lang['Interworx.manage.module_rows_title'] = "Server";
$lang['Interworx.manage.module_rows_heading.hostname'] = "Hostname";
$lang['Interworx.manage.module_rows_heading.options'] = "Pilihan";
$lang['Interworx.manage.module_groups_heading.options'] = "Pilihan";
$lang['Interworx.manage.module_rows.count'] = "%1\$s / %2\$s"; // %1$s is the current number of accounts, %2$s is the total number of accounts available
$lang['Interworx.manage.module_rows.edit'] = "Ubah";
$lang['Interworx.manage.module_rows.delete'] = "Hapus";
$lang['Interworx.manage.module_groups.confirm_delete'] = "Apakah Anda yakin ingin menghapus kelompok server ini?";
$lang['Interworx.manage.module_rows_no_results'] = "Tidak ada server.";
$lang['Interworx.add_row.box_title'] = "Tambahkan Server Interworx";
$lang['Interworx.add_row.basic_title'] = "Pengaturan Dasar";
$lang['Interworx.add_row.name_servers_title'] = "Nama Server";
$lang['Interworx.add_row.name_server_host_col'] = "Hostname";
$lang['Interworx.add_row.name_server'] = "Name server %1\$s"; // %1$s is the name server number (e.g. 3)
$lang['Interworx.add_row.remove_name_server'] = "Menghapus";
$lang['Interworx.edit_row.box_title'] = "Sunting Interworx Server";
$lang['Interworx.edit_row.notes_title'] = "Catatan";
$lang['Interworx.edit_row.name_server_col'] = "Nama Server
";
$lang['Interworx.edit_row.name_server'] = "Nama server %1\$s"; // %1$s is the name server number (e.g. 3)
$lang['Interworx.edit_row.remove_name_server'] = "Menghapus";
$lang['Interworx.edit_row.add_btn'] = "Edit Server";
$lang['Interworx.row_meta.server_name'] = "Label Server";
$lang['Interworx.row_meta.host_name'] = "Hostname";
$lang['Interworx.row_meta.port'] = "Nomor Port";
$lang['Interworx.row_meta.default_port'] = "2443";
$lang['Interworx.row_meta.debug.print'] = "Print";
$lang['Interworx.row_meta.use_ssl'] = "Gunakan SSL saat menghubungkan ke API (dianjurkan)";
$lang['Interworx.package_fields.type_standard'] = "Standard";
$lang['Interworx.package_fields.package'] = "Paket Interworx ";
$lang['Interworx.service_field.email'] = "Email";
$lang['Interworx.tab_stats.info_title'] = "Informasi";
$lang['Interworx.tab_stats.info_heading.field'] = "Bidang";
$lang['Interworx.tab_stats.info_heading.value'] = "Nilai";
$lang['Interworx.tab_stats.info.server'] = "Server";
$lang['Interworx.tab_stats.info.domain'] = "Domain";
$lang['Interworx.tab_stats.bandwidth_title'] = "Bandwidth";
$lang['Interworx.tab_stats.bandwidth_heading.used'] = "Digunakan";
$lang['Interworx.tab_stats.disk_heading.used'] = "Digunakan";
$lang['Interworx.tab_stats.package_info.opt_storage'] = "Disk Space";
$lang['Interworx.tab_stats.package_info.opt_mysql_db_users'] = "MySQL User";
$lang['Interworx.tab_stats.package_info.opt_pointer_domains'] = "Redirect Domains";
$lang['Interworx.tab_stats.package_info.opt_slave_domains'] = "Slave Domains";
$lang['Interworx.tab_stats.package_info.opt_cgi_access'] = "CGI Access";
$lang['Interworx.tab_stats.package_info.opt_crontab'] = "Akses cron";
$lang['Interworx.tab_stats.package_info.opt_dns_records'] = "DNS Access";
$lang['Interworx.tab_stats.package_info.opt_resolve_xferlog_dns'] = "Menyelesaikan xferlog DNS";
$lang['Interworx.tab_stats.package_info.opt_ssl'] = "SSL";
$lang['Interworx.tab_stats.package_info.opt_save_xfer_logs'] = "Simpan Xfer Log";
$lang['Interworx.tab_stats.package_info.opt_oversell_bandwidth'] = "Oversell Bandwidth";
$lang['Interworx.tab_stats.package_info.opt_oversell_storage'] = "Oversell Storage";
$lang['Interworx.tab_stats.package_info.opt_unlimited'] = "Unlimited";
$lang['Interworx.service_info.options'] = "Pilihan";
$lang['Interworx.service_info.option_login'] = "masuk";
$lang['Interworx.!error.name_servers_valid'] = "Satu atau lebih, Name server yang dimasukkan tidak valid.";
$lang['Interworx.!error.meta[type].valid'] = "Tipe akun harus berupa standar atau reseller.";
$lang['Interworx.!error.interworx_domain.format'] = "Masukkan nama domain yang valid dalam bentuk: domain.com";
$lang['Interworx.!error.interworx_username.format'] = "username hanya dapat berisi karakter alfanumerik.";
$lang['Interworx.!error.interworx_password.length'] = "Sandi harus minimal 6 karakter.";
$lang['Interworx.!error.interworx_email.format'] = "Silakan isi alamat email.";
$lang['Interworx.!error.api.internal'] = "Sebuah kesalahan internal terjadi, atau server tidak menanggapi permintaan tersebut.";
$lang['Interworx.!error.api.no_action'] = "API ini membutuhkan tindakan yang harus dilewati.";
$lang['Interworx.!error.api.soap_error'] = "Kesalahan SOAP. Periksa untuk memastikan bahwa SOAP telah diinstal dan dikonfigurasi dengan benar. Juga periksa pengaturan HOST dan PORT Anda sudah benar.";
$lang['Interworx.!error.api.no_ips'] = "Mengambil informasi IP, ada IP tersedia untuk Pengguna Interworx";
$lang['Interworx.!error.api.duplicate_domain'] = "Domain Ganda, domain itu sudah ada. Silahkan pilih domain lain.";
$lang['Interworx.!error.api.no_domain'] = "Kolom domain hilang di API. Kolom domain diperlukan";
$lang['Interworx.!error.api.no_reseller_access'] = "Panggilan API ini tidak tersedia untuk Reseller. Anda harus Administrator.";
$lang['Interworx.!error.api.create_reseller.missing_fields'] = "Mebuat Reseller membutuhkan username, email, dan password";
$lang['Interworx.!error.api.no_accounts'] = "Tidak ada Akun ditemukan.";
$lang['Interworx.service_field.confirm_password'] = "Konfirmasi Password";
$lang['Interworx.service_field.tooltip.password'] = "Anda dapat membiarkan (kolom) password kosong untuk secara otomatis dibuat oleh sistem";
$lang['Interworx.!error.libxml_required'] = "libxml extension diperlukan untuk modul ini.";
$lang['Interworx.tab_client_actions'] = "Aksi";
$lang['Interworx.tab_client_actions.change_password'] = "Ganti Kata Sandi";
$lang['Interworx.tab_client_actions.field_interworx_confirm_password'] = "Konfirmasi Kata Sandi";
$lang['Interworx.tab_client_actions.field_password_submit'] = "Perbarui Sandi";
?>