<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['BuycPanel.!error.meta[license_type].valid'] = "Silakan pilih jenis lisensi yang valid.";
$lang['BuycPanel.!error.buycpanel_ipaddress.format'] = "Masukkan alamat IP yang valid.";
$lang['BuycPanel.name'] = "BuycPanel";
$lang['BuycPanel.module_rows.name'] = "Akun";
$lang['BuycPanel.manage.module_rows_title'] = "akun";
$lang['BuycPanel.manage.module_rows_heading.email'] = "Email";
$lang['BuycPanel.manage.module_rows.test_yes'] = "Ya";
$lang['BuycPanel.manage.module_rows_no_results'] = "Tidak ada rekening.";
$lang['BuycPanel.tab_client_ip.current_ipaddress'] = "Alamat IP saat ini";
$lang['BuycPanel.tab_client_ip.field_ipaddress'] = "IP Address Baru";
$lang['BuycPanel.service_fields.ipaddress'] = "IP Address";
$lang['BuycPanel.service_field.tooltip.ipaddress'] = "Masukkan alamat IP yang lisensi akan berlaku untuknya";
$lang['BuycPanel.service_field.tooltip.domain'] = "Masukkan nama domain Anda.";
$lang['BuycPanel.row_meta.key'] = "API Key";
$lang['BuycPanel.row_meta.tooltip.key'] = "Masukan Kode API BuycPanel anda.";
$lang['BuycPanel.row_meta.test_mode'] = "Mode Percobaan";
$lang['BuycPanel.add_row.box_title'] = "Tambahkan Akun BuycPanel";
$lang['BuycPanel.add_row.basic_title'] = "Pengaturan Dasar";
$lang['BuycPanel.add_row.add_btn'] = "Tambahkan akun";
$lang['BuycPanel.edit_row.box_title'] = "Edit Akun BuycPanel";
$lang['BuycPanel.edit_row.basic_title'] = "Pengaturan Dasar";
$lang['BuycPanel.edit_row.add_btn'] = "Perbaharui Akun";
$lang['BuycPanel.license_types.0'] = "cPanel / WHM Plus!";
$lang['BuycPanel.license_types.3'] = "Satu Tahun Lisensi";
$lang['BuycPanel.license_types.4'] = "Lisensi Dua Tahun ";
$lang['BuycPanel.license_types.blesta'] = "Blesta";
$lang['BuycPanel.license_types.cloudlinux'] = "Cloud Linux";
$lang['BuycPanel.license_types.fantastico'] = "Fantastico";
$lang['BuycPanel.license_types.installatronvps'] = "Installatron VPS";
$lang['BuycPanel.license_types.litespeed_cpu'] = "Lite Speed CPU";
$lang['BuycPanel.license_types.rvsitebuildervps'] = "RVSiteBuilder VPS";
$lang['BuycPanel.license_types.rvskin'] = "RVSkin";
$lang['BuycPanel.license_types.solusvmslave'] = "SolusVM Micro Slave";
$lang['BuycPanel.license_types.solusvminislave'] = "SolusVM Mini Slave";
$lang['BuycPanel.license_types.solusvmunslave'] = "SolusVM Slave";
$lang['BuycPanel.license_types.solusvmnovirtual'] = "SolusVM Slave Only Master";
$lang['BuycPanel.license_types.trendyflashvps'] = "TrendySite Builder VPS";
$lang['BuycPanel.license_types.whmsonic'] = "WHMSonic";
?>