<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Authorize_net.name'] = "Authorize.Net";
$lang['Authorize_net.login_id'] = "Login ID";
$lang['Authorize_net.test_mode'] = "Test Mode";
$lang['Authorize_net.apis_cim'] = "CIM (harus diaktifkan oleh Authorize.Net)";
$lang['Authorize_net.validation_mode'] = "Model validasi rekening pembayaran";
$lang['Authorize_net.validation_note'] = "Ini mengontrol validasi jenis apa yang dilakukan ketika akun pembayaran disimpan menggunakan CIM. 'Tidak ada / None' Tidak ada validasi tambahan. 'Test' mengeluarkan transaksi tes yang tidak muncul pada pernyataan pelanggan tetapi akan menghasilkan email ke pedagang/merchan. 'Hidup/live' proses transaksi \$ 0,00 atau \$ 0,01 yang segera dibatalkan. Konsultasikan dengan Akun Provider Merchant Anda sebelum menetapkan nilai ini ke 'Hidup / live', seperti mungkin anda akan dikenakan biaya.";
$lang['Authorize_net.validation_modes_none'] = "Tak satupun";
$lang['Authorize_net.validation_modes_test'] = "Test";
$lang['Authorize_net.validation_modes_live'] = "Live";
$lang['Authorize_net.!error.login_id.format'] = "Login ID sebaiknya tidak lebih dari 20 karakter dan mungkin tidak kosong.";
$lang['Authorize_net.!error.transaction_key.format'] = "Kunci transaksi harus 16 karakter.";
$lang['Authorize_net.dev_mode'] = "Mode pengembang";
?>