<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['GoGetSSL.!error.api_username.empty'] = "Silakan masukkan nama pengguna API.";
$lang['GoGetSSL.!error.api_password.empty'] = "Silakan masukkan sandi API.";
$lang['GoGetSSL.!error.gogetssl_fqdn.format'] = "Masukkan Domain yang valid.";
$lang['GoGetSSL.!error.gogetssl_webserver_type.format'] = "Masukkan  Jenis Webserver yang valid.";
$lang['GoGetSSL.!error.meta[gogetssl_name].empty'] = "ID";
$lang['GoGetSSL.please_select'] = "-- Silakan Pilih --";
$lang['GoGetSSL.name'] = "GoGetSSL";
$lang['GoGetSSL.module_row_plural'] = "Reseller";
$lang['GoGetSSL.manage.module_rows_no_results'] = "Tidak ada reseller.";
$lang['GoGetSSL.manage.module_rows_heading.gogetssl_name'] = "Nama Reseller";
$lang['GoGetSSL.manage.module_rows_heading.options'] = "Pilihan";
$lang['GoGetSSL.row_meta.gogetssl_name'] = "Nama reseller";
$lang['GoGetSSL.row_meta.api_username'] = "Nama pengguna API";
$lang['GoGetSSL.row_meta.sandbox'] = "Sandbox";
$lang['GoGetSSL.add_row.box_title'] = "Tambahkan GoGetSSL Reseller";
$lang['GoGetSSL.add_row.basic_title'] = "Pengaturan Dasar";
$lang['GoGetSSL.edit_row.basic_title'] = "Pengaturan Dasar";
$lang['GoGetSSL.package_fields.product'] = "Produk";
$lang['GoGetSSL.service_field.gogetssl_approver_email'] = "Approver E-Mail";
$lang['GoGetSSL.service_field.gogetssl_lastname'] = "Nama terakhir";
$lang['GoGetSSL.service_field.gogetssl_address1'] = "Alamat baris 1";
$lang['GoGetSSL.service_field.gogetssl_city'] = "Kota";
$lang['GoGetSSL.service_field.gogetssl_zip'] = "ZIP";
$lang['GoGetSSL.service_field.gogetssl_country'] = "Negara";
$lang['GoGetSSL.service_field.gogetssl_organization'] = "Organisasi (isi NA jika tidak ada)";
$lang['GoGetSSL.service_field.gogetssl_fax'] = "Nomor faks (format internasional)";
$lang['GoGetSSL.tab_reissue'] = "Penerbitan kembali / Reissue";
?>