<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ImportManagerManagePlugin.!success.imported'] = "Importir telah diproses.";
$lang['ImportManagerManagePlugin.index.page_title'] = "Import Manager > Import";
$lang['ImportManagerManagePlugin.index.platform'] = "Platform";
$lang['ImportManagerManagePlugin.index.no_migrators'] = "Tidak ada migrator yang tersedia";
$lang['ImportManagerManagePlugin.import.submit'] = "Impor";
?>