<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMain.index.health_excellent'] = "Sistem ini dalam keadaan yang baik dan tampaknya beroperasi secara normal.";
$lang['AdminMain.index.health_good'] = "Secara keseluruhan sistem dalam kesehatan yang baik, tetapi ada beberapa item yang mungkin memerlukan perhatian Anda.";
$lang['AdminMain.index.health_fair'] = "Ada beberapa masalah yang mempengaruhi kemampuan sistem untuk beroperasi secara normal.";
$lang['AdminMain.index.health_poor'] = "Ada masalah serius yang mempengaruhi kemampuan sistem untuk beroperasi secara normal. Ini harus diselesaikan sesegera mungkin.";
$lang['AdminMain.index.cron_minor'] = "Cron belum berjalan dalam 24 jam terakhir.";
$lang['AdminMain.index.cron_configure'] = "Mengkonfigurasi?";
$lang['AdminMain.index.backup_minor'] = "Tidak ada backup telah dijalankan dalam 7 hari terakhir.";
$lang['AdminMain.index.cron_task_stalled_minor'] = "Ada satu atau lebih tugas cron yang telah mengeksekusi selama lebih dari %1\$s menit."; // %1$s is the number of minutes
$lang['AdminMain.index.cron_task_stalled_automation'] = "Lihat Tugas otomatis";
$lang['AdminMain.index.trial_buy'] = "Beli sekarang?";
$lang['AdminMain.index.updates_forever'] = "Dukungan dan update yang baik selamanya.";
?>