<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyEmails.templates.Order.received_name'] = "Pesanan Diterima";
$lang['AdminCompanyEmails.templates.Order.received_mobile_name'] = "Pesanan Diterima (Mobile)";
?>