<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMain.!success.status_updated'] = "Order yang dipilih telah berhasil diperbarui.";
$lang['AdminMain.!success.settings_updated'] = "Pengaturan pemesanan Anda berhasi diperbarui.";
$lang['AdminMain.index.boxtitle_order'] = "Pesanan";
$lang['AdminMain.index.no_results'] = "Tidak ada pesanan dari jenis ini.";
$lang['AdminMain.index.category_fraud'] = "Penipuan";
$lang['AdminMain.index.heading_client_id_code'] = "ID Klien";
$lang['AdminMain.index.heading_invoice_id_code'] = "Faktur #";
$lang['AdminMain.index.heading_date_added'] = "Tanggal pesan";
$lang['AdminMain.index.field_ordersubmit'] = "Perbarui Pesanan";
$lang['AdminMain.orderinfo.fraudreport_heading'] = "Laporan Penipuan ";
$lang['AdminMain.orderinfo.fraudreport_heading_key'] = "Key";
$lang['AdminMain.orderinfo.fraudreport_heading_value'] = "Nilai";
$lang['AdminMain.orderinfo.applied_heading'] = "Transaksi";
$lang['AdminMain.orderinfo.applied_heading_paymenttype'] = "Tipe pembayaran";
$lang['AdminMain.orderinfo.applied_heading_applied'] = "Terapan";
$lang['AdminMain.orderinfo.applied_heading_appliedon'] = "Terapan Pada";
$lang['AdminMain.orderinfo.applied_option_edit'] = "Sunting";
$lang['AdminMain.orderinfo.applied_no_results'] = "Tidak ada transaksi diterapkan untuk pesanan ini";
$lang['AdminMain.orderinfo.services_heading'] = "Layanan";
$lang['AdminMain.orderinfo.services_heading_package'] = "Paket";
$lang['AdminMain.orderinfo.services_heading_label'] = "label";
$lang['AdminMain.orderinfo.services_heading_term'] = "Periode";
$lang['AdminMain.orderinfo.services_text_never'] = "Tak pernah";
$lang['AdminMain.settings.heading_notifications'] = "Pemberitahuan Order";
$lang['AdminMain.settings.field_email_notice'] = "Email";
$lang['AdminMain.settings.field_email_notice_never'] = "Jangan dikirim";
$lang['AdminMain.settings.field_mobile_notice_manual'] = "Hanya mengirim jika persetujuan manual diperlukan";
$lang['AdminMain.settings.submit_cancel'] = "Kembali ke daftar orderan";
$lang['AdminMain.index.category_canceled'] = "Dibatalkan";
$lang['AdminMain.index.field_markas'] = "Tandai sebagai:";
?>