<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminForms.!success.form_added'] = " form telah ditambahkan.";
$lang['AdminForms.!success.form_edited'] = "form berhasil diperbarui.";
$lang['AdminForms.settings.page_title'] = "System Order";
$lang['AdminForms.index.boxtitle_order'] = "Sistem Order";
$lang['AdminForms.index.tab_forms'] = "Form Pesanan";
$lang['AdminForms.index.order_form_add'] = "Tambah Form Order";
$lang['AdminForms.index.order_forms_no_results'] = "Tidak ada formulir pemesanan saat ini.";
$lang['AdminForms.index.heading_name'] = "Nama";
$lang['AdminForms.index.heading_template'] = "Template";
$lang['AdminForms.index.heading_type'] = "Jenis";
$lang['AdminForms.index.heading_date_added'] = "Tanggal Ditambahkan";
$lang['AdminForms.index.heading_options'] = "Pilihan";
$lang['AdminForms.index.option_edit'] = "Edit";
$lang['AdminForms.index.option_delete'] = "Hapus";
$lang['AdminForms.index.text_confirm_delete'] = "Benar-benar menghapus order form ini?";
$lang['AdminForms.index.field_status_inactive'] = "Non-aktif";
$lang['AdminForms.add.boxtitle_order'] = "Sistem Pesanan - Tambah Formulir";
$lang['AdminForms.add.field_label'] = "Label";
$lang['AdminForms.add.field_type'] = "Jenis";
$lang['AdminForms.add.field_allow_coupons'] = "Izinkan Kupon";
$lang['AdminForms.add.field_manual_review'] = "Membutuhkan Pedoman Ulasan dan Persetujuan Semua Pesanan";
$lang['AdminForms.add.field_require_ssl'] = "Paksa koneksi Aman (HTTPS)";
$lang['AdminForms.add.field_require_captcha'] = "Membutuhkan Tantangan Verifikasi Manusia / bukan bot untuk Semua Pendaftaran";
$lang['AdminForms.add.field_template'] = "Template";
$lang['AdminForms.add.field_client_group_id'] = "Klien Grup standar";
$lang['AdminForms.add.field_addsubmit'] = "Tambahkan Form";
$lang['AdminForms.edit.boxtitle_order'] = "Sistem Order - Form Edit";
$lang['AdminForms.edit.field_name'] = "Nama";
$lang['AdminForms.edit.field_label'] = "Label";
$lang['AdminForms.edit.field_type'] = "Jenis";
$lang['AdminForms.edit.field_allow_coupons'] = "Izinkan Kupon";
$lang['AdminForms.edit.field_require_ssl'] = "Paksa Menggunakan Koneksi Aman (HTTPS)";
$lang['AdminForms.edit.field_require_tos'] = "Membutuhkan Kesediaan anda untuk menyetujui persyaratan Layanan";
$lang['AdminForms.edit.field_tos_url'] = "URL Ketentuan Layanan";
$lang['AdminForms.edit.field_status'] = "Status";
$lang['AdminForms.edit.field_status_active'] = "Aktif";
$lang['AdminForms.edit.field_status_inactive'] = "Tidak aktif";
$lang['AdminForms.edit.field_client_group_id'] = "Klien Group Default";
$lang['AdminForms.edit.tooltip_client_group'] = "Kelompok default klien pendaftaran baru dari formulir ini akan ditugaskan untuk.";
$lang['AdminForms.meta.text_membergroups'] = "Ditugaskan Di Grup";
$lang['AdminForms.meta.heading_package_group'] = "Grup Paket";
$lang['AdminForms.meta.heading_currencies'] = "Mata Uang";
$lang['AdminForms.meta.heading_gateways'] = "Gateway";
$lang['AdminForms.settings.field_default_form'] = "Formulir Pemesanan Standar";
$lang['AdminForms.settings.field_captcha'] = "Verifikasi Manusia";
$lang['AdminForms.settings.field_captcha_none'] = "Tidak Ada";
$lang['AdminForms.settings.field_captcha_recaptcha'] = "reCaptcha";
$lang['AdminForms.settings.antifraud_heading'] = "Anti-Fraud";
$lang['AdminForms.settings.field_antifraud'] = "Jenis";
$lang['AdminForms.add.template_preview'] = "Preview";
$lang['AdminForms.edit.template_preview'] = "Pratinjau";
?>