<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Cart.!error.coupon_applied'] = "Kupon tidak bisa diterapkan.";
$lang['Cart.index.totals.subtotal'] = "Subtotal:";
$lang['Cart.index.totals.total'] = "Total Jatuh Tempo :";
?>