<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Checkout.!error.no_payment_info'] = "Anda harus memilih metode pembayaran untuk melanjutkan.";
$lang['Checkout.setcontactview.text_none'] = "Tidak Satupun";
$lang['Checkout.getpaymentaccounts.paymentaccount_ach'] = "Akun ACH";
$lang['Checkout.getpaymentaccounts.account_name'] = "%1\$s %2\$s - %3\$s x%4\$s"; // %1$s is the account first name, %2$s is the account last name, %3$s is the account type (card type or bank account type), %4$s is the last 4 of the account
$lang['Checkout.index.field_agree_tos'] = "Saya telah membaca dan setuju dengan <a href=\"%1\$s\" target=\"_blank\">Syarat dan Ketentuan </a>"; // %1$s is the URI to the terms and conditions
$lang['Checkout.index.totals.setup_fee'] = "Biaya Setup :";
$lang['Checkout.index.totals.subtotal'] = "Sub Total:";
$lang['Checkout.index.totals.tax'] = "%1\$s (%2\$s%%):"; // %1$s is the tax name, %2$s is the tax percentage
$lang['Checkout.contact_info.field_last_name'] = "Nama Belakang";
$lang['Checkout.contact_info.field_address2'] = "alamat 2";
$lang['Checkout.contact_info.field_state'] = "Negara";
$lang['Checkout.cc_info.field_security'] = "Security Code";
$lang['Checkout.cc_info.field_savedetails'] = "Simpan Rincian Pembayaran";
$lang['Checkout.cc_info.tooltip_savedetails'] = "Rincian pembayaran disimpan dapat digunakan untuk melakukan pembayaran di masa depan tanpa harus memasukkan rincian setiap kali.";
$lang['Checkout.ach_info.field_accountnum'] = "Nomor Rekening";
$lang['Checkout.ach_info.field_savedetails'] = "Simpan Rincian Pembayaran";
$lang['Checkout.ach_info.tooltip_savedetails'] = "Rincian pembayaran disimpan dapat digunakan untuk melakukan pembayaran di masa depan tanpa harus memasukkan rincian setiap kali";
$lang['Checkout.complete.order_number'] = "Pesanan #%1\$s"; // %1$s is the order number
$lang['Checkout.complete.almost_complete_description'] = "Pesanan Anda telah diterima, menunggu pembayaran Anda di bawah ini.";
$lang['Checkout.index.totals.credit'] = "Kredit:";
$lang['Checkout.index.totals.paid'] = "Dibayar:";
$lang['Checkout.!error.not_client_owner'] = "Anda harus login sebagai pemilik / client untuk melanjutkan.";
?>