<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['OrderForms.!error.name.empty'] = "Anda harus memasukkan nama untuk formulir.";
$lang['OrderForms.!error.label.empty'] = "Anda harus memasukkan label pada form ini.";
$lang['OrderForms.!error.label.unique'] = "Formulir pemesanan dengan label tersebut sudah ada.";
$lang['OrderForms.!error.client_group_id.valid'] = "kelompok klien tidak ada.";
$lang['OrderForms.getVisibilities.client'] = "Hanya Klien";
?>