<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['OrderPlugin.name'] = "Order System";
$lang['OrderPlugin.admin_main.name'] = "Pesanan";
$lang['OrderPlugin.admin_forms.name'] = "Form Pemesanan";
$lang['OrderPlugin.cron.accept_paid_orders_desc'] = "Secara otomatis menerima pembayaran yang tertunda jika order form mengizinkan.";
?>