<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Signup.!error.captcha.invalid'] = "Captcha tidak cocok. Harap coba lagi.";
$lang['Signup.index.field_taxid'] = "NPWP";
$lang['Signup.index.field_firstname'] = "Nama Depan";
$lang['Signup.index.field_address1'] = "Alamat 1";
$lang['Signup.index.field_address2'] = "Alamat 2";
$lang['Signup.index.field_city'] = "Kota";
$lang['Signup.index.field_zip'] = "Zip / Postal Code";
$lang['Signup.index.field_phone'] = "Telepon";
$lang['Signup.index.field_fax'] = "Fax";
$lang['Signup.index.field_username_type_email'] = "Gunakan email sebagai username";
$lang['Signup.index.field_username_type_username'] = "Tentukan nama pengguna";
$lang['Signup.index.field_username'] = "Nama pengguna";
$lang['Signup.index.field_confirmpassword'] = "konfirmasi sandi";
?>