<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Vpsdotnet.module_row'] = "VPS.NET Master Server";
$lang['Vpsdotnet.order_options.first'] = "non-full server pertama ";
$lang['Vpsdotnet.please_wait'] = "Harap tunggu...";
$lang['Vpsdotnet.add_module_group'] = "Tambah Server Group";
$lang['Vpsdotnet.manage.module_rows_heading.server_label'] = "Label Server";
$lang['Vpsdotnet.manage.module_rows_heading.email'] = "Email";
$lang['Vpsdotnet.manage.module_groups_title'] = "VPS.NET Master Server Groups";
$lang['Vpsdotnet.manage.module_groups_heading.name'] = "Nama Grup";
$lang['Vpsdotnet.manage.module_groups_heading.servers'] = "Hitungan Server ";
$lang['Vpsdotnet.manage.module_groups.edit'] = "Edit";
$lang['Vpsdotnet.manage.module_groups.delete'] = "Hapus";
$lang['Vpsdotnet.manage.module_groups.confirm_delete'] = "Apakah Anda yakin ingin menghapus grup server ini?";
$lang['Vpsdotnet.manage.module_groups_no_results'] = "Tidak ada kelompok server ";
$lang['Vpsdotnet.service_info.vpsdotnet_primary_ip_address'] = " IP Address Utama";
$lang['Vpsdotnet.add_row.box_title'] = "Tambahkan Server VPS.NET";
$lang['Vpsdotnet.edit_row.basic_title'] = "Pengaturan Dasar";
$lang['Vpsdotnet.edit_row.add_btn'] = "Update Serve";
$lang['Vpsdotnet.package_fields.client_set_cloud'] = "Biarkan klien mengatur Cloud / Zone, Sistem Operasi, dan Template";
$lang['Vpsdotnet.package_fields.admin_set_cloud'] = "Pilih Cloud/Zona";
$lang['Vpsdotnet.package_fields.cloud'] = "Cloud / Zona";
$lang['Vpsdotnet.package_fields.template_group'] = "Sistem operasi";
$lang['Vpsdotnet.package_fields.template'] = "Template";
$lang['Vpsdotnet.service_field.vpsdotnet_hostname'] = "Hostname";
$lang['Vpsdotnet.service_field.vpsdotnet_label'] = "Label VPS";
$lang['Vpsdotnet.service_field.vpsdotnet_cloud'] = "Cloud / Zona";
$lang['Vpsdotnet.service_field.vpsdotnet_template_group'] = "Sistem operasi";
$lang['Vpsdotnet.service_field.vpsdotnet_template'] = "Template";
$lang['Vpsdotnet.tab_console'] = "Konsol";
$lang['Vpsdotnet.tab_client_console'] = "Konsol";
$lang['Vpsdotnet.!actions.reboot'] = "Reboot";
$lang['Vpsdotnet.tab_actions.status_online'] = "On line";
$lang['Vpsdotnet.tab_actions.status_offline'] = "Offline";
$lang['Vpsdotnet.tab_actions.status_pending'] = "Pending";
$lang['Vpsdotnet.tab_actions.heading_actions'] = "Tindakan";
$lang['Vpsdotnet.tab_actions.server_status'] = "Status Server";
$lang['Vpsdotnet.tab_actions.heading_reinstall'] = "Instal ulang";
$lang['Vpsdotnet.tab_actions.field_vpsdotnet_template'] = "Template";
$lang['Vpsdotnet.tab_actions.field_confirm'] = "Saya memahami bahwa dengan menginstal ulang, semua data pada server akan dihapus secara permanen, dan sistem operasi yang dipilih dan template yang akan dipasang.";
$lang['Vpsdotnet.tab_actions.field_reinstall_submit'] = "Instal ulang";
$lang['Vpsdotnet.tab_actions.heading_hostname'] = "Ganti Hostname";
$lang['Vpsdotnet.tab_actions.field_vpsdotnet_hostname'] = "Hostname";
$lang['Vpsdotnet.tab_actions.field_hostname_submit'] = "Ubah Hostname";
$lang['Vpsdotnet.tab_actions.field_password_submit'] = "Reset Password";
$lang['Vpsdotnet.tab_client_actions.heading_server_status'] = "Server Status";
$lang['Vpsdotnet.tab_client_actions.status_online'] = "Online";
$lang['Vpsdotnet.tab_client_actions.status_offline'] = "Offline";
$lang['Vpsdotnet.tab_client_actions.heading_reinstall'] = "Instal ulang";
$lang['Vpsdotnet.tab_client_actions.field_vpsdotnet_template_group'] = "Sistem Operasi";
$lang['Vpsdotnet.tab_client_actions.field_confirm'] = "Saya memahami bahwa dengan menginstal ulang, semua data pada server akan dihapus secara permanen, dan sistem operasi dan template yang dipilih yang akan dipasang.";
$lang['Vpsdotnet.tab_client_actions.field_reinstall_submit'] = "Instal ulang";
$lang['Vpsdotnet.tab_client_actions.heading_password'] = "Reset Password";
$lang['Vpsdotnet.tab_client_actions.field_password_submit'] = "Reset Password";
$lang['Vpsdotnet.!error.email.format'] = "Silakan masukkan alamat email yang valid.";
$lang['Vpsdotnet.!error.key.empty'] = "Silakan memasukkan kunci API Anda.";
$lang['Vpsdotnet.!error.key.valid_connection'] = "Sambungan ke server tidak dapat ditentukan. Silakan periksa untuk memastikan bahwa alamat email dan API key sudah benar.";
$lang['Vpsdotnet.!error.confirm.valid'] = "Anda harus mengakui bahwa Anda memahami tindakan untuk melakukan instalasi ulang template yang.ada";
$lang['Vpsdotnet.!error.meta[number_of_nodes].format'] = "Silahkan masukkan jumlah node yang akan dialokasikan.";
$lang['Vpsdotnet.!error.meta[cloud].format'] = "Silahkan pilih cloud yang valid";
$lang['Vpsdotnet.!error.meta[template_group].format'] = "Silakan pilih sistem operasi yang valid.";
$lang['Vpsdotnet.!error.vpsdotnet_hostname.format'] = "Hostname tampaknya tidak valid.";
$lang['Vpsdotnet.!error.vpsdotnet_label.empty'] = "Silakan masukkan label.";
$lang['Vpsdotnet.!error.vpsdotnet_label.format'] = "Label tidak boleh berisi karakter khusus.";
$lang['Vpsdotnet.!error.vpsdotnet_template_group.format'] = "Silakan pilih sistem operasi yang valid.";
$lang['Vpsdotnet.!error.vpsdotnet_template.format'] = "Pilih template yang valid.";
?>