<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Upload.!error.write_failed'] = "File tidak bisa ditulis.";
$lang['Upload.!error.path_created'] = "Tempat upload tidak dapat dibuat.";
?>