<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['DownloadManagerFiles.!error.name.empty'] = "Silakan masukkan nama untuk file ini.";
$lang['DownloadManagerFiles.!error.public.assignment'] = "File harus tersedia baik publik, kelompok klien, atau paket.";
$lang['DownloadManagerFiles.!error.permit_client_groups.format'] = "Pilihan ketersediaan kelompok klien dalam format yang tidak valid.";
$lang['DownloadManagerFiles.!error.permit_packages.format'] = "Pilihan ketersediaan paket dalam format yang tidak valid.";
$lang['DownloadManagerFiles.!error.file_packages.format'] = "Setidaknya satu paket yang dipilih tidak dapat ditambahkan karena tidak ada.";
$lang['DownloadManagerFiles.!error.file_id.exists'] = "File yang diperbarui tidak ada.";
?>