<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['DownloadManagerManagePlugin.!success.category_added'] = "Kategori ini telah berhasil dibuat.";
$lang['DownloadManagerManagePlugin.!success.category_deleted'] = "Kategori telah berhasil dihapus.";
$lang['DownloadManagerManagePlugin.!text.open_parenthesis'] = "(";
$lang['DownloadManagerManagePlugin.!text.forward_slash'] = "/";
$lang['DownloadManagerManagePlugin.modal.delete_file'] = "Apakah Anda yakin ingin menghapus berkas ini?";
$lang['DownloadManagerManagePlugin.index.page_title'] = "Download Manager >Kelola";
$lang['DownloadManagerManagePlugin.index.boxtitle_downloadmanager'] = "Download Manager";
$lang['DownloadManagerManagePlugin.index.add_download'] = "Tambahkan Download Disini";
$lang['DownloadManagerManagePlugin.index.add_category'] = "Tambahkan Kategori disini";
$lang['DownloadManagerManagePlugin.index.go_back'] = "Naik ke tingkat atas";
$lang['DownloadManagerManagePlugin.index.delete'] = "Hapus";
$lang['DownloadManagerManagePlugin.index.no_downloads'] = "Tidak ada download di bagian ini.";
$lang['DownloadManagerManagePlugin.add.boxtitle_root'] = "Simpan unduhan di %1\$s"; // %1$s is the name of the root directory
$lang['DownloadManagerManagePlugin.add.field_public'] = "Tersedia Untuk Publik";
$lang['DownloadManagerManagePlugin.add.field_name'] = "Nama";
$lang['DownloadManagerManagePlugin.add.field_available_to_packages'] = "Tersedia untuk Paket";
$lang['DownloadManagerManagePlugin.add.text_packagegroups'] = "Paket yang dipilih";
$lang['DownloadManagerManagePlugin.add.text_availablepackages'] = "Paket yang tersedia";
$lang['DownloadManagerManagePlugin.add.field_upload'] = "Unggah Berkas";
$lang['DownloadManagerManagePlugin.add.field_path'] = "Tentukan Jalur ke File";
$lang['DownloadManagerManagePlugin.add.field_file_name'] = "Jalur ke file";
$lang['DownloadManagerManagePlugin.edit.field_public'] = "Publik Tersedia";
$lang['DownloadManagerManagePlugin.edit.field_name'] = "Nama";
$lang['DownloadManagerManagePlugin.edit.field_available_to_client_groups'] = "Tersedia untuk Kelompok Klien";
$lang['DownloadManagerManagePlugin.edit.text_availablepackages'] = "Paket yang tersedia";
$lang['DownloadManagerManagePlugin.edit.field_path'] = "Tentukan Jalur ke File";
$lang['DownloadManagerManagePlugin.edit.field_file'] = "Berkas";
$lang['DownloadManagerManagePlugin.edit.submit_edit'] = "Perbarui Unduhan";
$lang['DownloadManagerManagePlugin.addcategory.boxtitle_root'] = "Tambahkan Kategori ke %1\$s"; // %1$s is the name of the root directory
$lang['DownloadManagerManagePlugin.addcategory.boxtitle_addcategory'] = "Tambahkan kategori ke kategori [%1\$s]"; // %1$s is the name of the category that this category is to be nested under
$lang['DownloadManagerManagePlugin.addcategory.field_description'] = "Deskripsi";
$lang['DownloadManagerManagePlugin.addcategory.submit_cancel'] = "Membatalkan";
$lang['DownloadManagerManagePlugin.editcategory.field_description'] = "Deskripsi";
$lang['DownloadManagerManagePlugin.editcategory.submit_edit'] = "Update Kategori";
$lang['DownloadManagerManagePlugin.editcategory.submit_cancel'] = "Membatalkan";
$lang['DownloadManagerManagePlugin.!text.root_directory'] = "Home Directory";
?>