<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['DownloadManagerCategories.!error.parent_id.exists'] = "Kategori induk yang dipilih tidak ada.";
$lang['DownloadManagerCategories.!error.parent_id.loop'] = "Kategori induk yang dipilih mungkin tidak dalam kategori itu sendiri.";
$lang['DownloadManagerCategories.!error.company_id.exists'] = "ID perusahaan tidak valid.";
$lang['DownloadManagerCategories.!error.name.empty'] = "Masukkan nama kategori.";
?>