<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Payza.name'] = "Payza";
$lang['Payza.merchant_id'] = "Email Merchant";
$lang['Payza.api_security_code'] = "API Password";
$lang['Payza.api_password_note'] = "Password API diperlukan untuk memproses pengembalian uang melalui Payza.";
$lang['Payza.test_mode'] = "Modus Sandbox";
$lang['Payza.test_mode_note'] = "Mengaktifkan pilihan ini akan menggunakan Payza Sandbox. Hanya aktifkan pilihan ini jika anda melakukan ujicoba dengan akun sandbox Payza.";
$lang['Payza.!error.merchant_id.valid'] = "Masukkan alamat email account merchant yang valid.";
?>