<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PricingPresenter.description.tax'] = "%1\$s (%2\$s%%)"; // %1$s is the tax name, %2$s is the tax amount
$lang['PricingPresenter.description.package.setup_fee'] = "Biaya Pemasangan %1\$s"; // %1$s is the name of the package
$lang['PricingPresenter.description.package.cancel_fee'] = "%1\$s Biaya Pembatalan"; // %1$s is the name of the package
$lang['PricingPresenter.description.service.option.prorate.remove'] = "Kredit prorata dari  %1\$s - %2\$s (%3\$s - %4\$s)"; // %1$s is the package option label, %2$s is the package option name, %3$s is the prorated start date, %4$s is the prorated end date
$lang['PricingPresenter.description.service.option.qty.prorate.add'] = "Penambahan prorata dari %1\$s - %2\$sx %3\$s (%4\$s - %5\$s)"; // %1$s is the package option label, %2$s is the package option quantity, %3$s is the package option name, %4$s is the prorated start date, %5$s is the prorated end date
?>