<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Enom.name'] = "Enom";
$lang['Enom.module_row'] = "Akun";
$lang['Enom.add_module_row'] = "Tambahkan akun";
$lang['Enom.manage.module_rows_title'] = "Akun";
$lang['Enom.manage.module_rows_heading.user'] = "Pengguna";
$lang['Enom.manage.module_rows.edit'] = "Ubah";
$lang['Enom.manage.module_rows.confirm_delete'] = "Apakah Anda yakin ingin menghapus akun ini?";
$lang['Enom.row_meta.user'] = "Pemakai";
$lang['Enom.row_meta.sandbox'] = "Sandbox";
$lang['Enom.row_meta.sandbox_true'] = "Ya";
$lang['Enom.add_row.box_title'] = "Tambahkan akun Enom";
$lang['Enom.add_row.basic_title'] = "Pengaturan Dasar";
$lang['Enom.add_row.add_btn'] = "Tambah Akun";
$lang['Enom.edit_row.box_title'] = "Edit Akun Enom";
$lang['Enom.edit_row.add_btn'] = "Perbarui Akun";
$lang['Enom.package_fields.type'] = "Jenis";
$lang['Enom.package_fields.type_ssl'] = "SSL Certificate";
$lang['Enom.package_fields.tld_options'] = "TLDs";
$lang['Enom.package_fields.ns3'] = "Nama Server 3";
$lang['Enom.tab_whois.section_Admin'] = "Administratif";
$lang['Enom.tab_whois.field_submit'] = "Perbarui Whois";
$lang['Enom.tab_nameservers.title'] = "Nama Server";
$lang['Enom.tab_nameservers.field_submit'] = "Update Name Server";
$lang['Enom.tab_settings.title'] = "Pengaturan";
$lang['Enom.tab_settings.field_registrar_lock'] = "Registrar Lock";
$lang['Enom.tab_settings.field_registrar_lock_yes'] = "Mengatur kunci registrar (registrar lock). Dianjurkan untuk mencegah perpindahan yang tidak sah.";
$lang['Enom.tab_settings.field_registrar_lock_no'] = "Melepaskan kunci registrar domain sehingga dapat ditransfer.";
$lang['Enom.domain.NumYears'] = "Tahun";
$lang['Enom.nameserver.ns3'] = "Name Server 3";
$lang['Enom.nameserver.ns4'] = "Nama Server 4";
$lang['Enom.whois.RegistrantFirstName'] = "Nama depan";
$lang['Enom.whois.RegistrantLastName'] = "Nama Terakhir";
$lang['Enom.whois.RegistrantAddress1'] = "Alamat 1";
$lang['Enom.whois.RegistrantPostalCode'] = "Kode Pos";
$lang['Enom.whois.TechFirstName'] = "Nama Depan";
$lang['Enom.whois.TechLastName'] = "Nama terakhir";
$lang['Enom.whois.TechAddress1'] = "Alamat 1";
$lang['Enom.whois.TechAddress2'] = "Alamat 2";
$lang['Enom.whois.TechCity'] = "Kota";
$lang['Enom.whois.TechPostalCode'] = "Kode Pos";
$lang['Enom.whois.AdminAddress1'] = "Alamat 1";
$lang['Enom.whois.AdminAddress2'] = "alamat 2";
$lang['Enom.whois.AdminStateProvince'] = "Negara Bagian / Provinsi";
$lang['Enom.whois.AdminPostalCode'] = "Kode Pos";
$lang['Enom.whois.AdminPhone'] = "Telephon";
$lang['Enom.whois.AuxBillingLastName'] = "Nama Belakang";
$lang['Enom.whois.AuxBillingAddress2'] = "Alamat 2";
$lang['Enom.whois.AuxBillingStateProvince'] = "Provinsi";
$lang['Enom.whois.AuxBillingCountry'] = "Negara";
$lang['Enom.whois.AuxBillingEmailAddress'] = "Email";
$lang['Enom.domain.RegistrantNexus.c11'] = "Warga Negara AS";
$lang['Enom.domain.RegistrantNexus.c21'] = "Perkumpulan atau Organisasi Amerika";
$lang['Enom.domain.RegistrantPurpose'] = "Tujuan";
$lang['Enom.domain.RegistrantPurpose.p3'] = "Pribadi";
$lang['Enom.domain.RegistrantPurpose.p4'] = "Pendidikan";
$lang['Enom.domain.RegistrantPurpose.p5'] = "Pemerintah";
$lang['Enom.domain.EUAgreeWhoisPolicy'] = "Kebijakan Whois";
$lang['Enom.domain.EUAgreeWhoisPolicy.yes'] = "Saya setuju bahwa Registry berhak untuk mentransfer data yang terdapat dalam aplikasi ini kepada pihak ketiga (i) jika diperintahkan untuk melakukannya oleh otoritas publik, melaksanakan tugas yang sah; dan (ii) atas permintaan dari Penyedia ADR sebagaimana dimaksud pada ayat 16 dari Syarat dan Ketentuan yang dipublikasikan di www.eurid.eu; dan (iii) sebagaimana ditentukan dalam Bagian 2 ( fasilitas look-up WHOIS) dari WHOIS Domain Kebijakan yang diterbitkan di www.eurid.eu ";
$lang['Enom.domain.EUAgreeDeletePolicy.yes'] = "Saya setuju dan mengakui untuk pembaharuan dan berakhirnya khusus ketentuan yang ditetapkan di bawah ini untuk nama domain ini, termasuk ketentuan yang ditetapkan dalam Perjanjian Pendaftaran. Saya memahami bahwa jika saya telah menetapkan domain ini untuk autorenewal, nama domain ini harus secara eksplisit diperbaharui dengan tanggal kedaluwarsa atau tanggal 20 bulan kadaluwarsa, mana yang lebih cepat. (Misalnya Jika nama berakhir pada 4 September 2008, maka pembaharuan pengguna harus diterima oleh 4 September 2008. Jika nama berakhir pada 27 September 2008, permintaan perpanjangan harus diterima sebelum 20 September 2008). Jika nama tidak diperpanjang secara manual atau ditetapkan sebelumnya untuk autorenew, permintaan penghapusan akan dikeluarkan oleh Enom. Ketika permintaan menghapus dikeluarkan, nama akan tetap berfungsi penuh dalam account saya sampai kadaluarsa, tapi tidak akan lagi terbarukan maupun saya akan dapat membuat modifikasi ke nama. Istilah-istilah ini dapat berubah.";
$lang['Enom.domain.CIRALegalType'] = "Jenis Hukum";
$lang['Enom.domain.RegistrantPurpose.cco'] = "Perusahaan";
$lang['Enom.domain.RegistrantPurpose.res'] = "Penduduk Kanada";
$lang['Enom.domain.RegistrantPurpose.edu'] = "Pendidikan";
$lang['Enom.domain.RegistrantPurpose.ass'] = "Unincorporated Association";
$lang['Enom.domain.RegistrantPurpose.plt'] = "Partai politik";
$lang['Enom.domain.RegistrantPurpose.abo'] = "masyarakat asli";
$lang['Enom.domain.RegistrantPurpose.inb'] = "Band India";
$lang['Enom.domain.RegistrantPurpose.omk'] = "Official Mark";
$lang['Enom.domain.RegistrantPurpose.maj'] = "The Queen";
$lang['Enom.domain.CIRAWhoisDisplay.private'] = "Jadikan Milik Pribadi";
$lang['Enom.domain.CIRALanguage'] = "Bahasa yang diinginkan untuk komunikasi";
$lang['Enom.domain.CIRALanguage.en'] = "Bahasa Inggris";
$lang['Enom.domain.UKLegalType'] = "Jenis Hukum";
$lang['Enom.domain.UKLegalType.ind'] = "UK individu";
$lang['Enom.domain.UKLegalType.ltd'] = "Perseroan Terbatas Inggris";
$lang['Enom.domain.UKLegalType.plc'] = "UK Public Limited Company";
$lang['Enom.domain.UKLegalType.ptnr'] = "Kemitraan UK";
$lang['Enom.domain.UKLegalType.ip'] = "UK Industri / Provident Perusahaan Terdaftar";
$lang['Enom.domain.UKLegalType.rchar'] = "Badan Amal Terdaftar di Inggris";
$lang['Enom.domain.UKLegalType.gov'] = "Badan Pemerintah Inggris";
$lang['Enom.domain.UKLegalType.crc'] = " Korporasi Inggris oleh Royal Charter";
$lang['Enom.domain.UKLegalType.fcorp'] = "Organisasi asing";
$lang['Enom.domain.UKLegalType.stat'] = "menemukan UK Statutory Tubuh";
$lang['Enom.domain.UKCompanyID'] = "Nomor ID Perusahaan";
$lang['Enom.domain.ASIALegalEntityType.corporation'] = "Perusahaan";
$lang['Enom.domain.ASIALegalEntityType.cooperative'] = "Koperasi";
$lang['Enom.domain.ASIALegalEntityType.government'] = "Badan pemerintah";
$lang['Enom.domain.ASIALegalEntityType.politicalParty'] = "Partai politik atau Serikat Pekerja";
$lang['Enom.domain.ASIALegalEntityType.society'] = "Terpercaya, Estates, Asosiasi atau Masyarakat";
$lang['Enom.domain.ASIALegalEntityType.institution'] = "Lembaga";
$lang['Enom.domain.ASIAIdentForm'] = "Bentuk identitas";
$lang['Enom.domain.ASIAIdentForm.certificate'] = "Certificate of Incorporation";
$lang['Enom.domain.ASIAIdentForm.legislation'] = "Piagam";
$lang['Enom.domain.ASIAIdentForm.societyRegistry'] = "Societies Registry";
?>