<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Payumoney.auth_header_note'] = "Header otorisasi dapat ditemukan di dashboard Payumoney di bawah Kelola Akun -> Akun Saya -> Merchant Key-Salt.";
?>