<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['TaxLiability.options.field_start_date'] = "Mulai Tanggal";
$lang['TaxLiability.options.field_end_date'] = "Tanggal Akhir";
$lang['TaxLiability.heading.taxable_amount'] = "Jumlah Kena Pajak";
$lang['TaxLiability.heading.level1_tax_rate'] = "Level 1 Tarif Pajak (%)";
$lang['TaxLiability.heading.level1_tax_amount'] = "Jumlah Pajak Tingkat 1";
$lang['TaxLiability.heading.level2_tax_rate'] = "Level 2 Prosentase Pajak (%)";
$lang['TaxLiability.heading.currency'] = "Mata Uang";
$lang['TaxLiability.heading.date_closed'] = "Tanggal Ditutup";
?>