<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Offline.name'] = "Pembayaran Offline";
$lang['Offline.instructions'] = "Instruksi";
$lang['Offline.!error.instructions.valid'] = "Anda harus memasukkan beberapa petunjuk.";
?>