<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['InvoiceCreation.heading.id_code'] = "Invoice #";
$lang['InvoiceCreation.heading.subtotal'] = "Subtotal";
$lang['InvoiceCreation.heading.total'] = "Total";
$lang['InvoiceCreation.heading.currency'] = "Mata uang";
$lang['InvoiceCreation.heading.date_closed'] = "Tanggal Ditutup";
?>