<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Whmsonic.tab_client_actions'] = "Tindakan";
$lang['Whmsonic.!error.server_name_valid'] = "Anda harus memasukkan Label Server.";
$lang['Whmsonic.!error.meta[bitrate].valid'] = "Silahkan pilih batas bitrate yang benar.";
$lang['Whmsonic.!error.meta[listeners].empty'] = "Harap masukkan Batas Pendengar.";
?>