<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Blue_pay.!error.account_id.empty'] = "Masukkan ID akun Anda.";
$lang['Blue_pay.!error.secret_key.empty'] = "Silahkan isi kata kunci rahasia Anda";
$lang['Blue_pay.name'] = "BluePay";
$lang['Blue_pay.account_id'] = "ID Akun";
$lang['Blue_pay.secret_key'] = "Secret Key";
?>