<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Eway.!error.customer_id.empty'] = "Masukkan ID Eway Anda.";
$lang['Eway.!error.customer_id.length'] = "ID Pelanggan tidak boleh melebihi 8 karakter.";
$lang['Eway.!error.invalid_xml'] = "Gateway menanggapi dengan XML tidak valid.";
$lang['Eway.name'] = "eWAY";
$lang['Eway.developer_mode'] = "Modus pengembang";
$lang['Eway.test_mode'] = "Test Mode";
?>