<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['UniversalModule.name'] = "Modul Universal";
$lang['UniversalModule.module_row_plural'] = "Produk";
$lang['UniversalModule.add_module_row'] = "Tambahkan Produk";
$lang['UniversalModule.manage.module_rows_heading.name'] = "Label Produk";
$lang['UniversalModule.manage.module_rows_heading.options'] = "Pilihan";
$lang['UniversalModule.manage.module_rows.edit'] = "Sunting";
$lang['UniversalModule.manage.module_rows.delete'] = "Hapus";
$lang['UniversalModule.manage.module_rows.confirm_delete'] = "Apakah Anda yakin ingin menghapus produk ini?";
$lang['UniversalModule.add_row.module_title'] = "Pilihan Modul";
$lang['UniversalModule.add_row.name'] = "Nama";
$lang['UniversalModule.add_row.notice_name'] = "Pemberitahuan";
$lang['UniversalModule.add_row.notice_code'] = "Kode HTTP";
$lang['UniversalModule.add_row.notice_response'] = "Respon Berisi";
$lang['UniversalModule.add_row.email_notification'] = "Email Pemberitahuan";
$lang['UniversalModule.add_row.package_title'] = "Paket Pilihan";
$lang['UniversalModule.add_row.package_field_btn'] = "Tambahkan Pilihan Paket";
$lang['UniversalModule.add_row.package_field_name'] = "Nama";
$lang['UniversalModule.add_row.package_field_values'] = "Nilai";
$lang['UniversalModule.add_row.package_field_required'] = "Wajib";
$lang['UniversalModule.add_row.remove_package_field'] = "hapus";
$lang['UniversalModule.add_row.package_email_from'] = "Dari Email";
$lang['UniversalModule.add_row.package_email_subject'] = "Subjek";
$lang['UniversalModule.add_row.package_email_html'] = "HTML";
$lang['UniversalModule.add_row.package_email_text'] = "Teks";
$lang['UniversalModule.add_row.service_title'] = "Pilihan Layanan";
$lang['UniversalModule.add_row.service_field_btn'] = "Tambahkan Opsi/pilihan Layanan";
$lang['UniversalModule.add_row.service_field_label'] = "Label";
$lang['UniversalModule.add_row.service_field_values'] = "Nilai";
$lang['UniversalModule.add_row.service_field_required'] = "Wajib";
$lang['UniversalModule.add_row.service_field_encrypt'] = "Enkripsi";
$lang['UniversalModule.add_row.remove_service_field'] = "hapus";
$lang['UniversalModule.add_row.service_email_from'] = "Pengirim Email";
$lang['UniversalModule.add_row.service_email_html'] = "HTML";
$lang['UniversalModule.add_row.add_btn'] = "Tambah Produk";
$lang['UniversalModule.edit_row.box_title'] = "Edit Produk";
$lang['UniversalModule.edit_row.name'] = "Nama";
$lang['UniversalModule.edit_row.notice_notice'] = "Posting URL / Email";
$lang['UniversalModule.edit_row.notice_code'] = "HTTP Code";
$lang['UniversalModule.edit_row.package_field_label'] = "Label";
$lang['UniversalModule.edit_row.package_field_name'] = "Nama";
$lang['UniversalModule.edit_row.package_field_type'] = "Jenis";
$lang['UniversalModule.edit_row.package_field_encrypt'] = "Encrypt";
$lang['UniversalModule.edit_row.remove_package_field'] = "hapus";
$lang['UniversalModule.edit_row.package_rules'] = "Tambahkan Peraturan";
$lang['UniversalModule.edit_row.package_email_text'] = "Teks";
$lang['UniversalModule.edit_row.service_title'] = "Pilihan layanan";
$lang['UniversalModule.edit_row.service_field_label'] = "Label";
$lang['UniversalModule.edit_row.service_field_name'] = "Nama";
$lang['UniversalModule.edit_row.service_field_type'] = "Jenis";
$lang['UniversalModule.edit_row.service_field_encrypt'] = "Encrypt";
$lang['UniversalModule.edit_row.service_rules'] = "Aturan masukan";
$lang['UniversalModule.edit_row.service_email_from'] = "Email Dari";
$lang['UniversalModule.edit_row.service_email_subject'] = "Subjek";
$lang['UniversalModule.edit_row.service_email_html'] = "HTML";
$lang['UniversalModule.edit_row.add_btn'] = "Mengedit Produk";
$lang['UniversalModule.getpackagenotices.add'] = "Tambah";
$lang['UniversalModule.getservicenotices.cancel'] = "batalkan";
$lang['UniversalModule.getservicenotices.package_change'] = "Perubahan Paket";
$lang['UniversalModule.getfieldtypes.text'] = "Teks";
$lang['UniversalModule.getfieldtypes.textarea'] = "Teks area";
$lang['UniversalModule.getfieldtypes.select'] = "Pilih";
$lang['UniversalModule.getfieldtypes.radio'] = "Radio";
$lang['UniversalModule.getfieldtypes.hidden'] = "Tersembunyi";
$lang['UniversalModule.false'] = "Tidak";
$lang['UniversalModule.!error.package_notice_edit.failed'] = "Modul gagal berkomunikasi dengan remote server ketika berusaha untuk memperbarui paket";
$lang['UniversalModule.!error.service_notice_cancel.failed'] = "Modul gagal berkomunikasi dengan remote server ketika mencoba untuk membatalkan layanan.";
$lang['UniversalModule.!error.service_notice_renew.failed'] = "Modul gagal berkomunikasi dengan server remote ketika mencoba untuk memperbarui layanan.";
$lang['UniversalModule.!error.service_notice_package_change.failed'] = "Modul gagal berkomunikasi dengan server remote ketika mencoba untuk memperbarui paket / periode yang ditugaskan untuk layanan.";
$lang['UniversalModule.!error.package_field.required'] = "%1\$s diperlukan."; // %1$s is the label for the required package field
$lang['UniversalModule.!error.name.empty'] = "Nama produk diperlukan.";
$lang['UniversalModule.!error.package_email_from.required'] = "Alamat dari diperlukan untuk notifikasi email paket.";
$lang['UniversalModule.!error.service_email_from.required'] = "Dari alamat diperlukan untuk notifikasi email mengenai layanan";
$lang['UniversalModule.!error.module_row.invalid'] = "Anda harus menentukan produk modul universal.";
$lang['UniversalModule.manage.module_rows_no_results'] = "Tidak ada produk.";
$lang['UniversalModule.!tooltip.option_heading_field_type'] = "Ini adalah jenis bentuk bidang yang akan ditampilkan.";
$lang['UniversalModule.!tooltip.option_heading_notice_code'] = "Jika posting URL, Anda dapat memasukkan kode HTTP yang menunjuk respon sukses.";
?>