<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Centovacast.manage.module_rows_heading.name'] = "Label Server";
$lang['Centovacast.manage.module_rows_heading.options'] = "Pilihan";
$lang['Centovacast.manage.module_groups.edit'] = "Edit";
$lang['Centovacast.package_fields.servertype'] = "Tipe Server";
$lang['Centovacast.tab_client_actions.action_restart'] = "Restart";
$lang['Centovacast.tab_client_stats.info.sourcepassword'] = "Sumber Password";
$lang['Centovacast.tab_client_stats.usage_unlimited'] = "(%1\$s MB/?)"; // %1$s is the amount of resource usage
$lang['Centovacast.!error.api.internal'] = "Terjadi kesalahan internal, atau server tidak dapat merespon.";
?>