<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMain.index.categorylink_adddocument'] = "Tambahkan Dokumen";
$lang['AdminMain.index.boxtitle_client'] = "Klien #%1\$s - %2\$s %3\$s";
$lang['AdminMain.index.boxtitle_documents'] = "Dokumen";
$lang['AdminMain.index.heading_name'] = "Nama";
$lang['AdminMain.index.heading_description'] = "Deskripsi";
$lang['AdminMain.index.heading_date_added'] = "Tanggal Ditambahkan";
$lang['AdminMain.index.heading_date_options'] = "Pilihan";
$lang['AdminMain.index.option_delete'] = "Hapus";
$lang['AdminMain.index.option_download'] = "Unduh";
$lang['AdminMain.add.field_name'] = "nama";
$lang['AdminMain.add.field_description'] = "Deskripsi";
$lang['AdminMain.add.field_submit'] = "Upload Dokumen";
?>